------------------CREATE APP REPO USER------------------------

CREATE USER APP_GS_IR IDENTIFIED BY "APP_GS_IR" DEFAULT TABLESPACE DATA1;
GRANT CONNECT,CREATE SESSION TO APP_GS_IR;
GRANT CREATE VIEW, CREATE MATERIALIZED VIEW, QUERY REWRITE, CREATE PROCEDURE, CREATE SEQUENCE,
CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE SYNONYM TO APP_GS_IR;
GRANT CREATE JOB TO APP_GS_IR;
GRANT EXECUTE ON DBMS_LOCK TO APP_GS_IR;
ALTER USER APP_GS_IR QUOTA UNLIMITED ON INDEX1;
ALTER USER APP_GS_IR QUOTA UNLIMITED ON DATA1;

CREATE USER APP_GS_GC IDENTIFIED BY "APP_GS_GC" DEFAULT TABLESPACE DATA1;
GRANT CONNECT,CREATE SESSION TO APP_GS_GC;
GRANT CREATE VIEW, CREATE MATERIALIZED VIEW, QUERY REWRITE, CREATE PROCEDURE, CREATE SEQUENCE,
CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE SYNONYM TO APP_GS_GC;
GRANT CREATE JOB TO APP_GS_GC;
GRANT EXECUTE ON DBMS_LOCK TO APP_GS_GC;
ALTER USER APP_GS_GC QUOTA UNLIMITED ON INDEX1;
ALTER USER APP_GS_GC QUOTA UNLIMITED ON DATA1;

CREATE USER AUD_GS_GC IDENTIFIED BY "AUD_GS_GC" DEFAULT TABLESPACE DATA1;
GRANT CONNECT,CREATE SESSION TO AUD_GS_GC;
GRANT CREATE VIEW, CREATE MATERIALIZED VIEW, QUERY REWRITE, CREATE PROCEDURE, CREATE SEQUENCE,
CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE SYNONYM TO AUD_GS_GC;
GRANT CREATE JOB TO AUD_GS_GC;
GRANT EXECUTE ON DBMS_LOCK TO AUD_GS_GC;
ALTER USER AUD_GS_GC QUOTA UNLIMITED ON INDEX1;
ALTER USER AUD_GS_GC QUOTA UNLIMITED ON DATA1;

GRANT CREATE TABLE TO GS_GC;
