set echo on;

-------------- FT_T_CADF Dependent tables and its constraints

--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LAAC MODIFY CAL_ID VARCHAR2(10);

--{$$-STATEMENT-$$}
BEGIN 
 UPDATE   /*+ Parallel(16) */ FT_T_LAAC SET CAL_ID=TRIM(CAL_ID);
COMMIT; 
 END;
 
--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LAAC ADD CONSTRAINT FT_T_LAAC_F002 FOREIGN KEY  (CAL_ID) REFERENCES FT_T_CADF ENABLE NOVALIDATE;


-------------- FT_T_ISTY Dependent tables and its constraints

--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LACD MODIFY ISS_TYP VARCHAR2(8);
--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LACV MODIFY ISS_TYP VARCHAR2(8);

--{$$-STATEMENT-$$}
BEGIN 
 UPDATE   /*+ Parallel(16) */ FT_T_LACD SET ISS_TYP=TRIM(ISS_TYP);
COMMIT; 
 END;
 
 --{$$-STATEMENT-$$}
BEGIN 
 UPDATE   /*+ Parallel(16) */ FT_T_LACV SET ISS_TYP=TRIM(ISS_TYP);
COMMIT; 
 END;

ALTER TABLE FT_T_LACV ADD CONSTRAINT FT_T_LACV_F002 FOREIGN KEY  (ISS_TYP) REFERENCES FT_T_ISTY ENABLE NOVALIDATE;

 
ALTER TABLE FT_T_LAAT ADD CONSTRAINT FT_T_LAAT_F005 FOREIGN KEY  (EXT_RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE; 

-------------------------------- CustomOOB columns Category wise - 'YES' ----------------------------

/* ALTER TABLE	FT_T_CCRF	ADD 	LAAN_OID	CHAR(10);									--Already Present in Oracle V10
ALTER TABLE	FT_T_FLAR	ADD 	BILLS_ANNEX_IND	CHAR(1)	;								--Already Present in Oracle V10
ALTER TABLE	FT_T_FLAR	ADD 	ED_ATE_APPLS_IND	CHAR(1)	;							--Already Present in Oracle V10
ALTER TABLE	FT_T_FLAR	ADD 	GILT_ANNEX_IND	CHAR(1)	;								--Already Present in Oracle V10
ALTER TABLE	FT_T_FLAR	ADD 	EQUITY_ANNEX_IND	CHAR(1)	;							--Already Present in Oracle V10
ALTER TABLE	FT_T_FLAR	ADD 	ITALIAN_ANNEX_IND	CHAR(1)	;							--Already Present in Oracle V10
ALTER TABLE	FT_T_FLAR	ADD 	PRNCPL_TRAN_APPLIES_IND	CHAR(1)	;						--Already Present in Oracle V10 */
ALTER TABLE	FT_T_LAAP	ADD 	COLL_DISPUTE_IND	CHAR(1)	;
ALTER TABLE	FT_T_LAAP	ADD 	THSHLD_METH_STAT_TMS	VARCHAR2(256)	;
ALTER TABLE	FT_T_LAAT	ADD 	THSHLD_CURR_CDE	CHAR(3)	;							--Already Present in Oracle V10
--ALTER TABLE	FT_T_LACD	ADD 	COLL_CALL_FQ_SP_TYP	CHAR(2)	;						--Already Present in Oracle V10
ALTER TABLE	FT_T_LACD	ADD 	COLL_CALL_FQ_QTY	NUMBER(10)	;
/* ALTER TABLE	FT_T_LACD	ADD 	COLL_CALL_FQ_DY_TYP	CHAR(4)	;						--Already Present in Oracle V10
ALTER TABLE	FT_T_LACD	ADD 	COLL_CALL_NOTFCN_TMZ	CHAR(8)	;						--Already Present in Oracle V10 */
	
UPDATE FT_T_LAAP LAAP SET COLL_DISPUTE_IND = (SELECT MAX(LAAN.COL_DISP_IND) FROM FT_T_LAAN LAAN WHERE LAAN.LAAN_OID = LAAP.LAAN_OID) 
WHERE EXISTS (SELECT 1 FROM FT_T_LAAN LAAN WHERE LAAN.LAAN_OID = LAAP.LAAN_OID);

ALTER TABLE FT_T_LAAN DROP COLUMN COL_DISP_IND;

-------------------------------- CustomOOB columns Category wise - 'ALTERNATE AVAILABLE' ----------------------------

--UPDATE FT_T_LAAN SET ANNEX_NEGOTN_INSTRUC_DTE = ANNEX_INSTRCN_DTE ;										-- No data
--UPDATE FT_T_LAAN SET ANNEX_MGT_LOC_TYP = ANNEX_LOC_TXT;													-- No data
--UPDATE FT_T_LAAN SET ANNEX_ID = ANNEX_VERSION;															-- No data
UPDATE FT_T_LAAP SET ANNEX_PRT_MODL_TYP = ANNEX_MODL_TYP;
COMMIT;
UPDATE FT_T_LAAP SET THSHLD_METH_TXT = INDEPENDENT_METH_TXT;
COMMIT;			
UPDATE FT_T_LAAP SET THSHLD_METH_STAT_TMS = INDEPENDENT_STAT_TMS;
COMMIT;
--UPDATE FT_T_LAAT SET ANNEX_PRT_MODL_TYP = ANNEX_MODL_TYP;												-- Already done in LAAP
UPDATE FT_T_LAAT SET THSHLD_CALC_CURR_CDE = CALC_CURR;
COMMIT;
UPDATE FT_T_LAAP LAAP SET EARLY_TERM_PAY_CURR_CDE = (SELECT MAX(EARLY_TER_CURR) FROM FT_T_LAAT LAAT WHERE LAAT.LAAP_OID = LAAP.LAAP_OID) 
WHERE EXISTS (SELECT 1 FROM FT_T_LAAT LAAT WHERE LAAT.LAAP_OID = LAAP.LAAP_OID);
COMMIT;
UPDATE FT_T_LAAP LAAP SET EV_DFLT_CURR_CDE = (SELECT MAX(EOD_TER_CURR) FROM FT_T_LAAT LAAT WHERE LAAT.LAAP_OID = LAAP.LAAP_OID) 
WHERE EXISTS (SELECT 1 FROM FT_T_LAAT LAAT WHERE LAAT.LAAP_OID = LAAP.LAAP_OID);
COMMIT;
UPDATE FT_T_LAAP LAAP SET INST_MNEM = (SELECT MAX(LAAT.INST_MNEM) FROM FT_T_LAAT LAAT WHERE LAAT.LAAP_OID = LAAP.LAAP_OID) 
WHERE EXISTS (SELECT 1 FROM FT_T_LAAT LAAT WHERE LAAT.LAAP_OID = LAAP.LAAP_OID);
COMMIT;
UPDATE FT_T_LAAP LAAP SET INTEREST_ADJ_TYP = (SELECT MAX(LAAT.INT_ADJ_IND) FROM FT_T_LAAT LAAT WHERE LAAT.LAAP_OID = LAAP.LAAP_OID) 
WHERE EXISTS (SELECT 1 FROM FT_T_LAAT LAAT WHERE LAAT.LAAP_OID = LAAP.LAAP_OID);
COMMIT;
UPDATE FT_T_LAAP LAAP SET INTEREST_TSFR_TYP = (SELECT MAX(LAAT.INT_TSFR_IND) FROM FT_T_LAAT LAAT WHERE LAAT.LAAP_OID = LAAP.LAAP_OID) 
WHERE EXISTS (SELECT 1 FROM FT_T_LAAT LAAT WHERE LAAT.LAAP_OID = LAAP.LAAP_OID);
COMMIT;
UPDATE FT_T_LAAT SET THSHLD_CURR_CDE  = THSHLD_CURR;
COMMIT;
UPDATE FT_T_LACD SET MARGIN_CALL_NOTFCN_TME = to_char(COLL_CALL_NOTFCN_TME, 'HH:MI');	-- as data too large for MARGIN_CALL_NOTFCN_TME CHAR(5), trimming it
COMMIT;

UPDATE FT_T_LACD LACD SET LACD.GUNT_OID = 
(SELECT MAX(GUNT.GUNT_OID) FROM FT_T_GUNT GUNT WHERE PRNT_GU_TYP='COUNTRY' AND prnt_gu_cnt=1 AND GUNT.GU_NME=LACD.ISSR_CDE);
UPDATE FT_T_LACD LACD SET LACD.GUNT_OID = 
(SELECT GUNT.GUNT_OID FROM FT_T_GUNT GUNT WHERE PRNT_GU_TYP='COUNTRY' AND prnt_gu_cnt=1 AND GUNT.GU_NME='United States (the)') WHERE LACD.ISSR_CDE = 'United States';
UPDATE FT_T_LACD LACD SET LACD.GUNT_OID = 
(SELECT GUNT.GUNT_OID FROM FT_T_GUNT GUNT WHERE PRNT_GU_TYP='COUNTRY' AND prnt_gu_cnt=1 AND GUNT.GU_NME= 'United Kingdom (the)') WHERE LACD.ISSR_CDE = 'United Kingdom';															
COMMIT;
																			
UPDATE FT_T_LACD SET MATURITY_RULE_MAX_TXT = MATURITY_RULE_TXT_MAX;	
COMMIT;
UPDATE FT_T_LACD SET COLL_TICKER_ID = TICKER_CDE;
COMMIT;
UPDATE FT_T_LACV SET DLR_BR_NME = BRNCH_NME;
COMMIT;
UPDATE FT_T_LAGR SET AGRMNT_NEGOTN_INSTRUC_DTE = AGRMNT_INSTRCN_DTE;
COMMIT;
UPDATE FT_T_LAIP SET NETTING_TYP = TRN_PY_NETTING;														
COMMIT;
UPDATE FT_T_LAGR SET AGRMNT_VERSION_ID = AGRMNT_VERSION;
COMMIT;

-------------------------- Dropping the below columns after data copy to Alternative columns --------------------------
ALTER TABLE FT_T_LAAN DROP COLUMN ANNEX_INSTRCN_DTE;
ALTER TABLE FT_T_LAAN DROP COLUMN ANNEX_LOC_TXT;
ALTER TABLE FT_T_LAAN DROP COLUMN ANNEX_VERSION;
ALTER TABLE FT_T_LAAP DROP COLUMN ANNEX_MODL_TYP;
ALTER TABLE FT_T_LAAT DROP COLUMN ANNEX_MODL_TYP;
ALTER TABLE FT_T_LAAP DROP COLUMN INDEPENDENT_METH_TXT;
ALTER TABLE FT_T_LAAP DROP COLUMN INDEPENDENT_STAT_TMS;
ALTER TABLE FT_T_LAAT DROP COLUMN CALC_CURR;
ALTER TABLE FT_T_LAAT DROP COLUMN EARLY_TER_CURR;
ALTER TABLE FT_T_LAAT DROP COLUMN EOD_TER_CURR;
ALTER TABLE FT_T_LAAT DROP COLUMN INST_MNEM;
ALTER TABLE FT_T_LAAT DROP COLUMN INT_ADJ_IND;
ALTER TABLE FT_T_LAAT DROP COLUMN INT_TSFR_IND;
ALTER TABLE FT_T_LAAT DROP COLUMN THSHLD_CURR;
--ALTER TABLE FT_T_LACD DROP COLUMN COLL_CALL_FQ_DY_TYP;				-- Column with same name is provided in V10 by DM team, so not dropping
--ALTER TABLE FT_T_LACD DROP COLUMN COLL_CALL_FQ_SP_TYP;				-- Column with same name is provided in V10 by DM team, so not dropping
ALTER TABLE FT_T_LACD DROP COLUMN COLL_CALL_NOTFCN_TME;				
ALTER TABLE FT_T_LACD DROP COLUMN ISSR_CDE;							
ALTER TABLE FT_T_LACD DROP COLUMN MATURITY_RULE_TXT_MAX;
ALTER TABLE FT_T_LACD DROP COLUMN TICKER_CDE;
ALTER TABLE FT_T_LACV DROP COLUMN BRNCH_NME;
ALTER TABLE FT_T_LAGR DROP COLUMN AGRMNT_INSTRCN_DTE;
ALTER TABLE FT_T_LAGR DROP COLUMN AGRMNT_VERSION;
ALTER TABLE FT_T_LAIP DROP COLUMN TRN_PY_NETTING;

-------------------------------- CustomOOB columns Category wise - 'NEED INFO' ----------------------------
-------------------------- Dropping the below columns as no need to keep them --------------------------

ALTER TABLE FT_T_LAAT DROP COLUMN MARGIN_CAMT;
ALTER TABLE FT_T_LAAT DROP COLUMN RL_TYP;
ALTER TABLE FT_T_LACV DROP COLUMN ISS_TYP;
ALTER TABLE FT_T_LACV DROP COLUMN ORG_ID;
ALTER TABLE FT_T_LACV DROP COLUMN PRC_SRCE_TYP;

INSERT INTO ft_t_stdf (stat_def_id, start_tms, last_chg_tms, last_chg_usr_id, stat_val_typ, stat_nme, stat_desc, data_stat_typ, data_src_id)
SELECT 'CCALLHOL', SYSDATE, SYSDATE, 'MHI:CSTM', 'CHARACT', 'Collateral call action if holiday', 'Collateral call action if holiday', 'ACTIVE', 'MHI'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_stdf WHERE stat_def_id = 'CCALLHOL' AND end_tms IS NULL);
	   
INSERT INTO ft_t_stdf (stat_def_id, start_tms, last_chg_tms, last_chg_usr_id, stat_val_typ, stat_nme, stat_desc, data_stat_typ, data_src_id)
SELECT 'COLLSDTC', SYSDATE, SYSDATE, 'MHI:CSTM', 'INTEGER', 'Collateral Settlement Date', 'Collateral Settlement Date', 'ACTIVE', 'MHI'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_stdf WHERE stat_def_id = 'COLLSDTC' AND end_tms IS NULL);
	   
INSERT INTO ft_t_stdf (stat_def_id, start_tms, last_chg_tms, last_chg_usr_id, stat_val_typ, stat_nme, stat_desc, data_stat_typ, data_src_id)
SELECT 'COLLVDTC', SYSDATE, SYSDATE, 'MHI:CSTM', 'INTEGER', 'Collateral Value Date offset', 'Collateral Value Date offset', 'ACTIVE', 'MHI'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_stdf WHERE stat_def_id = 'COLLVDTC' AND end_tms IS NULL);
	   
INSERT INTO ft_t_stdf (stat_def_id, start_tms, last_chg_tms, last_chg_usr_id, stat_val_typ, stat_nme, stat_desc, data_stat_typ, data_src_id)
SELECT 'INTRCRTE', SYSDATE, SYSDATE, 'MHI:CSTM', 'AMNT/DEC', 'Interest Rate', 'Interest Rate', 'ACTIVE', 'MHI'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_stdf WHERE stat_def_id = 'INTRCRTE' AND end_tms IS NULL);
COMMIT;

ALTER TABLE FT_T_LACD DROP COLUMN COLL_CALL_ACTION_IF_HOL;
ALTER TABLE FT_T_LACD DROP COLUMN COLL_SETTLE_DTE_OF_CNT;
ALTER TABLE FT_T_LACD DROP COLUMN COLL_VAL_DTE_OF_CNT;
ALTER TABLE FT_T_LACD DROP COLUMN INTRST_CRTE;

-------------------------------- CustomOOB columns Category wise - 'NO' ----------------------------
-------------------------- Dropping the below columns as no need to keep them --------------------------

ALTER TABLE FT_T_FLAR DROP COLUMN ESCROW_MIN_RTNG_CDE;
ALTER TABLE FT_T_FLAR DROP COLUMN ESCROW_MIN_RTNG_SET_OID;
ALTER TABLE FT_T_PRPU
DROP (MHI_BILATERAL,MHI_BLMBRG_CDE,MHI_CASH,MHI_CLEARED,MHI_CSA_FLAG,MHI_DVP,MHI_FUT_AGRMNT,MHI_HO_APPR_RECD,MHI_HO_APPR_REQ,MHI_ISDA_DATE,MHI_ISDA_FLAG,MHI_ISDA_NETTING,MHI_LIMIT_QUALIFIER,MHI_LIMIT_RQST,MHI_REPO_DATE,MHI_REPO_NETTING,MHI_REPO_WRTN_AGRMNT,MHI_RISK_APPR_RECD,MHI_RISK_APPR_REQ,MHI_TENOR,MHI_TRDNG_CDE);
ALTER TABLE FT_T_INLM
DROP (MHI_FUT_AGRMNT,MHI_LIMIT_QUALIFIER,MHI_REPO_NETTING,MHI_REPO_WRTN_AGRMNT,MHI_SWAP_NETTING);

-------------------------------- CustomOOB columns Category wise - 'NOT REQUIRED' ----------------------------
--------------------------------------------- COMPOSITE PK COLUMNS -------------------------------------------

ALTER TABLE FT_T_LAAN DROP COLUMN LEG_AGRMNT_ID;
ALTER TABLE FT_T_LAAN DROP COLUMN ORG_ID;
ALTER TABLE FT_T_LAAP DROP COLUMN MIN_COLL_RTNG_CDE;
ALTER TABLE FT_T_LAAP DROP COLUMN MIN_COLL_RTNG_SET_OID;
ALTER TABLE FT_T_LAAP DROP COLUMN MIN_RTNG_CDE;
ALTER TABLE FT_T_LAAP DROP COLUMN MIN_RTNG_SET_OID;
ALTER TABLE FT_T_LAAT DROP COLUMN EXT_RTNG_CDE;
ALTER TABLE FT_T_LAAT DROP COLUMN INT_RTNG_CDE;
ALTER TABLE FT_T_LACD DROP COLUMN COLL_RTNG_CDE;
ALTER TABLE FT_T_LACD DROP COLUMN COLL_RTNG_SET_OID;
ALTER TABLE FT_T_LACD DROP COLUMN HLD_MIN_INT_RTNG_CDE;
ALTER TABLE FT_T_LACD DROP COLUMN HLD_MIN_INT_RTNG_SET_OID;
ALTER TABLE FT_T_LACD DROP COLUMN HLD_MIN_RTNG_CDE;
ALTER TABLE FT_T_LACD DROP COLUMN HLD_MIN_RTNG_SET_OID;
ALTER TABLE FT_T_LACD DROP COLUMN SEC_MIN_INT_RTNG_CDE;
ALTER TABLE FT_T_LACD DROP COLUMN SEC_MIN_INT_RTNG_SET_OID;
ALTER TABLE FT_T_LACD DROP COLUMN SEC_MIN_RTNG_CDE;
ALTER TABLE FT_T_LACD DROP COLUMN SEC_MIN_RTNG_SET_OID;
ALTER TABLE FT_T_LACV DROP COLUMN PROD_ID;
ALTER TABLE FT_T_LAGR DROP COLUMN PRNT_LEG_AGRMNT_ID;
ALTER TABLE FT_T_LAGR DROP COLUMN PRNT_ORG_ID;
ALTER TABLE FT_T_LAID DROP COLUMN LEG_AGRMNT_ID;
ALTER TABLE FT_T_LAID DROP COLUMN ORG_ID;
ALTER TABLE FT_T_SSIA DROP COLUMN ACCT_ORG_ID;
ALTER TABLE FT_T_EQCH DROP COLUMN FULLY_FUNDED_IND;


-------------------------------- GNCM (LAGR_OID - Cross_ref_id)- Migration -------------------------------

update ft_t_gncm a set cross_ref_id= (select lagr_oid from ft_t_lagr b where a.cross_ref_id=b.leg_agrmnt_id )
where  gncm_tbl_typ='LAGR'
AND  exists (select lagr_oid from ft_t_lagr b where nvl(a.cross_ref_id,'aa')=nvl(b.leg_agrmnt_id,'ss'));
COMMIT;
update ft_t_gncm a set cross_ref_id= (select lagr_oid from ft_t_lagr b where a.cross_ref_id=b.cross_ref_id)
where  gncm_tbl_typ='LAGR' AND  exists (select lagr_oid from ft_t_lagr b where nvl(a.cross_ref_id,'aa')=nvl(b.cross_ref_id,'ss'));
COMMIT;
