update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'AGRMNT_AMEND_DESC_1' where fld_id = 'LAGR0003';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'AGRMNT_APRVL_DTE_1' where fld_id = 'LAGR0001';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'AGRMNT_TERMINTN_DTE_1' where fld_id = 'LAGR0005';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'ANNEX_AMEND_DESC_1' where fld_id = 'LAAN0003';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'ANNEX_APRVL_DTE_1' where fld_id = 'LAAN0002';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'ANNEX_EFF_DTE_1' where fld_id = 'LAAN0009';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'ANNEX_MODL_TYP_1' where fld_id = 'LAAN0008';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'ANNEX_STAT_TYP_1' where fld_id = 'LAAN0001';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'ANNEX_TERMINTN_DTE_1' where fld_id = 'LAAN0007';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'CUST_PROD_NME_1' where fld_id = 'LACV0003';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'CVG_PURP_TYP_1' where fld_id = 'LACV0001';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'MTA_STAT_TMS_1' where fld_id = 'LAAT0001';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'NETTING_DESC_1' where fld_id = 'LAIP0001';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'THSHLD_STAT_TMS_1' where fld_id = 'LAAT0002';
update /*+ Parallel(16) */ ft_t_fldf set ddl_nme = 'THSHLD_CURR_1', fld_nme = 'Threshold Currency 1' where fld_id = 'LAAT0008';
commit;
--FT_T_CADF Dependent tables and its constraints

--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LAAC DROP CONSTRAINT FT_T_LAAC_F002;

--FT_T_ISTY Dependent tables and its constraints

--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LACD DROP CONSTRAINT FT_T_LACD_F013;
--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LACV DROP CONSTRAINT FT_T_LACV_F002;

--FT_T_RTVL Dependent tables and its constraints

--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LAAP DROP CONSTRAINT FT_T_LAAP_F004;
--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LAAP DROP CONSTRAINT FT_T_LAAP_F007;

--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LAAT DROP CONSTRAINT FT_T_LAAT_F003;
--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LAAT DROP CONSTRAINT FT_T_LAAT_F005;

--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LACD DROP CONSTRAINT FT_T_LACD_F004;
--{$$-STATEMENT-$$}
--ALTER TABLE FT_T_LACD DROP CONSTRAINT FT_T_LACD_F006;
--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LACD DROP CONSTRAINT FT_T_LACD_F008;
--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LACD DROP CONSTRAINT FT_T_LACD_F010;
--{$$-STATEMENT-$$}
ALTER TABLE FT_T_LACD DROP CONSTRAINT FT_T_LACD_F012;

ALTER TABLE FT_T_LACD DROP CONSTRAINT FT_T_LACD_F006;

------------ FT_T_RTVL Dropping Composite PK -----------------
--{$$-STATEMENT-$$}
ALTER TABLE FT_T_RTVL DROP CONSTRAINT FT_T_RTVL_PK;

DROP INDEX FT_T_RTVL_PK;

UPDATE FT_T_RTVL SET RTNG_VALUE_OID='PSGMIZ=190' WHERE RTNG_VALUE_OID='MIZRTVL190' AND RTNG_SET_OID='MIZRTNG1 ';
--1 ROWS
UPDATE FT_T_FIRT SET RTNG_VALUE_OID='PSGMIZ=190' WHERE RTNG_VALUE_OID='MIZRTVL190' AND RTNG_SET_OID='MIZRTNG1 ';

--{$$-STATEMENT-$$}
ALTER TABLE FT_T_RTVL ADD CONSTRAINT FT_T_RTVL_PK PRIMARY KEY (RTNG_VALUE_OID) ENABLE NOVALIDATE;

ALTER TABLE FT_T_ACRT ADD CONSTRAINT ACRTF003 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_ACSO ADD CONSTRAINT ACSOF005 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_ASGV ADD CONSTRAINT ASGVF004 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
ALTER TABLE FT_T_BNRT ADD CONSTRAINT BNRTF003 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_COLD ADD CONSTRAINT COLDF007 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
ALTER TABLE FT_T_CURT ADD CONSTRAINT CURTF003 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
ALTER TABLE FT_T_ERVL ADD CONSTRAINT ERVLF001 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
ALTER TABLE FT_T_FIRT ADD CONSTRAINT FIRTF003 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_FLAR ADD CONSTRAINT FLARF004 FOREIGN KEY  (ESCROW_MIN_RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_FNVD ADD CONSTRAINT FNVDF009 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
ALTER TABLE FT_T_FRRT ADD CONSTRAINT FRRTF003 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
ALTER TABLE FT_T_GURT ADD CONSTRAINT GURTF003 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_ICSC ADD CONSTRAINT ICSCF007 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
ALTER TABLE FT_T_INLM ADD CONSTRAINT INLMF018 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
ALTER TABLE FT_T_IRRT ADD CONSTRAINT IRRTF003 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
ALTER TABLE FT_T_ISRT ADD CONSTRAINT ISRTF003 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
 
ALTER TABLE FT_T_LMRT ADD CONSTRAINT LMRTF003 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_LPRT ADD CONSTRAINT LPRTF004 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_MTDI ADD CONSTRAINT MTDIF010 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_PARG ADD CONSTRAINT PARGF002 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_PPRT ADD CONSTRAINT PPRTF003 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_PRRT ADD CONSTRAINT PRRTF002 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_RKSE ADD CONSTRAINT RKSEF018 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_RKWT ADD CONSTRAINT RKWTF008 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
--ALTER TABLE FT_T_RSME ADD CONSTRAINT RSMEF017 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
ALTER TABLE FT_T_RVXR ADD CONSTRAINT RVXRF001 FOREIGN KEY  (RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;
ALTER TABLE FT_T_RVXR ADD CONSTRAINT RVXRF002 FOREIGN KEY  (RLD_RTNG_VALUE_OID) REFERENCES FT_T_RTVL ENABLE NOVALIDATE;

------------------------ FT_T_GUNT Duplicate Data Issue (updating cross_ref_id's) ---------------------------

UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1AN1' WHERE PRNT_GU_ID =' AN' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1AQ1' WHERE PRNT_GU_ID =' AQ' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1BS1' WHERE PRNT_GU_ID =' BS' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1CR1' WHERE PRNT_GU_ID =' CR' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1Df1' WHERE PRNT_GU_ID =' DF' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1MH1' WHERE PRNT_GU_ID =' MH' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1nH1' WHERE PRNT_GU_ID =' NO' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1hO1' WHERE PRNT_GU_ID =' NOHO' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1Qa1' WHERE PRNT_GU_ID =' QA' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1ZC1' WHERE PRNT_GU_ID =' ZC' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';

UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1AN   ' WHERE PRNT_GU_ID ='AN' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1AQ   ' WHERE PRNT_GU_ID ='AQ' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1BS   ' WHERE PRNT_GU_ID ='BS' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1CR   ' WHERE PRNT_GU_ID ='CR' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1Df   ' WHERE PRNT_GU_ID ='DF' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1MH   ' WHERE PRNT_GU_ID ='MH' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1nH   ' WHERE PRNT_GU_ID ='NO' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1hO   ' WHERE PRNT_GU_ID ='NOHO' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1Qa   ' WHERE PRNT_GU_ID ='QA' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
UPDATE FT_T_GUNT SET CROSS_REF_ID = 'GUNT1ZC   ' WHERE PRNT_GU_ID ='ZC' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';

DELETE FROM FT_T_GUNT WHERE CROSS_REF_ID = 'GUNT1AN1' AND PRNT_GU_ID =' AN' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
DELETE FROM FT_T_GUNT WHERE CROSS_REF_ID = 'GUNT1AQ1' AND PRNT_GU_ID =' AQ' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
DELETE FROM FT_T_GUNT WHERE CROSS_REF_ID = 'GUNT1BS1' AND PRNT_GU_ID =' BS' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
DELETE FROM FT_T_GUNT WHERE CROSS_REF_ID = 'GUNT1CR1' AND PRNT_GU_ID =' CR' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
DELETE FROM FT_T_GUNT WHERE CROSS_REF_ID = 'GUNT1Df1' AND PRNT_GU_ID =' DF' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
DELETE FROM FT_T_GUNT WHERE CROSS_REF_ID = 'GUNT1MH1' AND PRNT_GU_ID =' MH' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
DELETE FROM FT_T_GUNT WHERE CROSS_REF_ID = 'GUNT1nH1' AND PRNT_GU_ID =' NO' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
DELETE FROM FT_T_GUNT WHERE CROSS_REF_ID = 'GUNT1hO1' AND PRNT_GU_ID =' NOHO' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
DELETE FROM FT_T_GUNT WHERE CROSS_REF_ID = 'GUNT1Qa1' AND PRNT_GU_ID =' QA' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';
DELETE FROM FT_T_GUNT WHERE CROSS_REF_ID = 'GUNT1ZC1' AND PRNT_GU_ID =' ZC' AND PRNT_GU_TYP ='STATE' AND PRNT_GU_CNT ='1';

------------------------ FT_T_MRKT Duplicate Data Issue (Deleting duplicates) --------------------------------

DELETE FROM FT_T_MKID WHERE mkt_oid = 'MKTMICISEC';
DELETE FROM FT_T_MRKT WHERE mkt_oid = 'MKTMICISEC';
DELETE FROM FT_T_MKID WHERE mkt_oid = 'MRKT003FND';
DELETE FROM FT_T_MRKT WHERE mkt_oid = 'MRKT003FND';

------------------------ FT_T_IDMV Duplicate Data Issue (Deleting duplicates) --------------------------------

DELETE FROM FT_T_IDMV WHERE intrnl_dmn_val_id = '=0000B65FC';
DELETE FROM FT_T_IDMV WHERE intrnl_dmn_val_id = 'FIXBAS659 ';
DELETE FROM FT_T_IDMV WHERE intrnl_dmn_val_id = 'FIXBAS665 ';

------------------------ FT_T_VFMT Duplicate Data Issue (Deleting duplicates) --------------------------------

DELETE FROM ft_cfg_vfmt WHERE vnd_file_nme = 'GISF_ERD_*' AND ROW_SEQ_NUM = 3;
DELETE FROM ft_cfg_vfmt WHERE vnd_file_nme = ' GISF_ERD_*' AND ROW_SEQ_NUM = 2;
commit;

--------------------------------- Handling Customer Table Issue ----------------------------------------------

DROP INDEX FT_X_CSST_MHI1 ;

----------------------------------- Creating Backup Tables ---------------------------------------------------

CREATE TABLE FT_T_EDMV_BEF_MIGR AS SELECT * FROM FT_T_EDMV;
CREATE TABLE FT_T_FFRL_BEF_MIGR AS SELECT * FROM FT_T_FFRL;
CREATE TABLE FT_T_IDMV_BEF_MIGR AS SELECT * FROM FT_T_IDMV;
CREATE TABLE FT_T_MKID_BEF_MIGR AS SELECT * FROM FT_T_MKID;
CREATE TABLE FT_T_MRKT_BEF_MIGR AS SELECT * FROM FT_T_MRKT;
CREATE TABLE FT_T_XELM_BEF_MIGR AS SELECT * FROM FT_T_XELM;

----------------------------------- Handling CustomOOB PRPU and INLM tables ----------------------------------
CREATE TABLE FT_T_PRPU_DATAMIG AS SELECT * FROM FT_T_PRPU;
CREATE TABLE FT_T_INLM_DATAMIG AS SELECT * FROM FT_T_INLM;


