update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/Cancel.xslt' where vnd_rqst_typ='CancelScheduledRequest';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBCorpGovtConvPrfd.xslt' where vnd_rqst_typ='BBCorpGovtConvPrfd';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBGlobalWarrants.xslt' where vnd_rqst_typ='Warrants';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBHQLA.xslt' where vnd_rqst_typ='BBHQLACMOABS';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBHQLA.xslt' where vnd_rqst_typ='BBHQLAEquity';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBHQLA.xslt' where vnd_rqst_typ='BBHQLAFixedIncome';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBIndex.xslt' where vnd_rqst_typ='IndexPricing';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBHQLA.xslt' where vnd_rqst_typ='BBHQLAMBSPools';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBHQLA.xslt' where vnd_rqst_typ='BBHQLAMunicipals';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBGlobalCommodityFutures.xslt' where vnd_rqst_typ='CommodityFutures';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBCommodityOptionsMizuho.xslt' where vnd_rqst_typ='CommodityOptnPX';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBCurrency.xslt' where vnd_rqst_typ='Currency';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBGlobalEquityMizuho.xslt' where vnd_rqst_typ='Equity';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBGlobalEquity.xslt' where vnd_rqst_typ='EquityShortSale';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBGlobalEquity.xslt' where vnd_rqst_typ='EquityShortSaleCircuitBreak';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBGeneric.xslt' where vnd_rqst_typ='Generic';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBMortgagePoolNonPoolMizuho.xslt' where vnd_rqst_typ='Mortgage Non Pool';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBMortgagePoolNonPool.xslt' where vnd_rqst_typ='Mortgage Non PoolAddn';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBMortgagePoolNonPool.xslt' where vnd_rqst_typ='MortgagePools';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBCorpGovtConvPrfd.xslt' where vnd_rqst_typ='Preferreds';
update ft_cfg_vrty set uri='db://resource/xslt/request/bloomberg/BBCorpGovtConvPrfd.xslt' where vnd_rqst_typ='PreferredsAddn';