update ft_t_gunt set gu_nme = prnt_gu_id where gu_nme is null


DO $$
DECLARE
    i integer;
    name_list text[] := ARRAY[
'Delaware',
'Hawaii',
'North Dakota',
'Alaska',
'Luxembourg',
'Oklahoma',
'South Carolina',
'Missouri',
'Western Australia',
'Malta',
'Louisiana',
'Virginia',
'Netherlands (the)',
'Wyoming',
'Kansas',
'Mult',
'North Carolina',
'Indiana',
'United Kingdom (the)',
'Croatia',
'Bulgaria',
'Arizona',
'Wisconsin',
'Ohio',
'EURO CURRENCY ZONE',
'EUROCLEAR/CEDEL',
'INTERNATIONAL ORGS EEC.',
'SIKKIM',
'WESTERN SAMOA',
'Iowa',
'CANTON & ENDERBURY ISLANDS',
'United Arab Emirates - Dubai',
'INTERNATIONAL ORGS OTHER.',
'NOT CURRENTLY IN USE',
'TARGET',
'UNALLOCATED',
'US TRUST TERR. IN THE PACIFIC',
'Europe',
'Beijing',
'Chongqing',
'Fujian',
'Guangdong',
'Gansu',
'Guangxi Zhuang',
'Hebei',
'Heilongjiang',
'Jilin',
'Ningxia Hui',
'Shanxi',
'Tianjin',
'Xinjiang Uygur',
'Zhejiang',
'Anhui',
'Guizhou',
'Henan',
'Hubei',
'Hunan',
'Jiangsu',
'Jiangxi',
'Liaoning',
'Qinghai',
'Shanghai',
'New Jersey',
'California',
'Nebraska',
'Washington',
'Romania',
'Idaho',
'Minnesota',
'West Virginia',
'Azerbaijan',
'Kentucky',
'Ireland',
'Ontario',
'GRCB',
'Connecticut',
'Oregon',
'Rhode Island',
'Montenegro',
'Maine',
'Lithuania',
'Portugal',
'Czech Republic (the)',
'Tennessee',
'Georgia',
'Illinois',
'Latvia',
'Greece',
'Hungary',
'New South Wales',
'Slovenia',
'District Of Columbia',
'Texas',
'Cyprus',
'Supranational',
'Nevada',
'Poland',
'New Mexico',
'Pennsylvania',
'Arkansas',
'Maryland',
'Montana',
'South Dakota',
'Michigan',
'Utah',
'Maryland',
'Amman',
'Alabama',
'Xizang',
'Mississippi',
'New York',
'Guam',
'Virgin Islands',
'Florida',
'Madrid',
'Puerto Rico',
'ILE-DE-FRANCE',
'Abu Dhabi',
'Fujairah',
'Sharjah',
'Dubai',
'Ras al-Khaimah',
'Umm al-Quwain',
'United Arab Emirates - Abu Dhabi',
'AUSTRALIA - HOBART',
'Estonia',
'Vermont',
'Slovakia',
'Massachusetts',
'New Hampshire',
'Virginia',
'Colorado',
'Victoria (abbrev)',
'Kent',
'Ajman',
'AUSTRALIA - ADELAIDE',
'AUSTRALIA - BRISBANE',
'AUSTRALIA - DARWIN',
'AUSTRALIA - MELBOURNE',
'AUSTRALIA - PERTH',
'AUSTRALIA - SYDNEY',
'BRITISH ANTARCTIC TERRITORY',
'Yvelines',
'West Grand Bahama',
'Vilniaus miestas',
'Viljandimaa',
'Veszprem',
'Vaslui',
'Valgamaa',
'Valcea',
'Umm al Qaywayn',
'Tulcea',
'Thai Nguyen',
'Teleorman',
'Tartumaa',
'Tainan',
'Szabolcs-Szatmar-Bereg',
'Sudurland',
'Sterea Ellada',
'South West Singapore',
'South East Singapore',
'Songkhla',
'Sibiu',
'Serravalle',
'Satu Mare',
'Santa Cruz',
'San Fernando',
'Salta',
'Sakiai',
'Saint Paul Charlestown',
'Saint Louis',
'Saint James',
'Saint George',
'Saint Andrew',
'Ruse',
'Rize',
'Regiao Insular',
'Raseiniai',
'Qeqqata Kommunia',
'Prahova',
'Pohnpei',
'Pichincha',
'Penama',
'Parnumaa',
'Oost-Vlaanderen',
'Nouvelle-Ecosse',
'North West Singapore',
'Nordurland eystra',
'Nonthaburi',
'New Taipei',
'Neam?',
'Montserrado',
'Mont Buxton',
'Mersin',
'Menges',
'Mangrove Cay',
'Madinat Injamina',
'Littoral',
'Laane-Virumaa',
'La Massana',
'Kupiskis',
'Klaipeda',
'Kelme',
'Kauno miestas',
'Kaohsiung',
'Kabul',
'Joniskis',
'Jogevamaa',
'Jarvamaa',
'Ignalina',
'Ialomi?a',
'Hsinchu',
'Ho Chi Minh',
'Hhohho',
'?awalli',
'HaTsafon',
'Harbour Island',
'Hai Phong',
'Gyor-Moson-Sopron',
'Gros Islet',
'Greater Accra',
'Gorj',
'Gampaha',
'Francisco Morazan',
'Esch-sur-Alzette',
'Encamp',
'Echternach',
'Dytiki Ellada',
'Diekirch',
'Dambovita',
'Daejeon-gwangyeoksi',
'Csongrad',
'Covasna',
'Cluj',
'City of Freeport',
'Christ Church Nichola Town',
'Chon Buri',
'Centre',
'Castries',
'Cara?-Severin',
'Burgas',
'Brunei-Muara',
'Brazzaville',
'Bouches-du-Rhone',
'Blagoevgrad',
'Birzai',
'Bihor',
'Bayrut',
'Baranya',
'Bacau',
'Auvergne-Rhone-Alpes',
'Arge?',
'Alytaus miestas',
'Al Qahirah',
'Al Isma''iliyah',
'Al Fujayrah',
'Al Asimah',
'Akmene',
'Abha',
'Almaty',
'Dodoma',
'Oslo',
'Tehran',
'The Valley',
'Rockhampton',
'Banja Luka',
'Cotonou',
'Kralendijk (Bonaire)',
'The Bottom (Saba)',
'Campinas',
'Lages',
'Porto Alegre',
'Ribeirao Preto',
'Halifax',
'West Island',
'Yamoussoukro',
'Yaounde',
'Jinan',
'Cali',
'Popayan',
'Willemstad',
'Cologne',
'Essen',
'Magdeburg',
'Saarbrucken',
'Roseau',
'Asmara',
'Jaen',
'Santa Cruz (Canarias)',
'Itziar (Deba)',
'Pamplona',
'Zizur Mayor',
'Torshavn',
'Cardiff',
'St. George''s',
'St. Peter Port',
'Conakry',
'Malabo',
'Acquaviva',
'San Marino',
'Fatick',
'Kaolack',
'Saint-Louis',
'Thies',
'Awdal',
'Banaadir',
'Bay',
'Gedo',
'Jubbada Dhexe',
'Mudug',
'Sanaag',
'Shabeellaha Hoose',
'Togdheer',
'Brokopondo',
'Coronie',
'Nickerie',
'Saramacca',
'Wanica',
'Ahuachapan',
'Chalatenango',
'La Paz',
'San Miguel',
'La Union',
'Dimashq',
'Dayr az Zawr',
'Hims',
'Hamah',
'Al Ladhiqiyah',
'Ar Raqqah',
'As Suwayda''',
'Lubombo',
'Shiselweni',
'Shari Baqirmi',
'Kanim',
'Luqun al Gharbi',
'Shari al Awsat',
'Salamat',
'Centrale',
'Plateaux',
'Ang Thong',
'Sing Buri',
'Saraburi',
'Trat',
'Prachin Buri',
'Sa Kaeo',
'Buri Ram',
'Si Sa Ket',
'Yasothon',
'Amnat Charoen',
'Nong Bua Lam Phu',
'Udon Thani',
'Nong Khai',
'Roi Et',
'Sakon Nakhon',
'Mukdahan',
'Lamphun',
'Uttaradit',
'Nan',
'Chiang Rai',
'Nakhon Sawan',
'Kamphaeng Phet',
'Sukhothai',
'Phichit',
'Kanchanaburi',
'Nakhon Pathom',
'Samut Songkhram',
'Prachuap Khiri Khan',
'Krabi',
'Phuket',
'Ranong',
'Satun',
'Phatthalung',
'Yala',
'Phatthaya',
'Kuhistoni Badakhshon',
'Sughd',
'Ainaro',
'Bobonaro',
'Ermera',
'Liquica',
'Manatuto',
'Viqueque',
'Balkan',
'Lebap',
'L''Ariana',
'Nabeul',
'Bizerte',
'Jendouba',
'Siliana',
'Kasserine',
'Sousse',
'Mahdia',
'Gafsa',
'Kebili',
'Medenine',
'Adana',
'Afyonkarahisar',
'Amasya',
'Artvin',
'Balikesir',
'Bingol',
'Bolu',
'Bursa',
'cankiri',
'Denizli',
'Edirne',
'Erzincan',
'Eskisehir',
'Giresun',
'Hakkari',
'Kars',
'Kirklareli',
'Kocaeli',
'Kutahya',
'Manisa',
'Mardin',
'Mus',
'Nigde',
'Sakarya',
'Siirt',
'Sivas',
'Tokat',
'Tunceli',
'Usak',
'Yozgat',
'Aksaray',
'Karaman',
'Batman',
'Bartin',
'igdir',
'Karabuk',
'Osmaniye',
'Arima',
'Couva-Tabaquite-Talparo',
'Penal-Debe',
'Princes Town',
'Sangre Grande',
'San Juan-Laventille',
'Changhua',
'Chiayi',
'Hualien',
'Miaoli',
'Penghu',
'Yunlin',
'Iringa',
'Kaskazini Pemba',
'Kigoma',
'Kusini Pemba',
'Lindi',
'Mbeya',
'Morogoro',
'Mwanza',
'Rukwa',
'Shinyanga',
'Tabora',
'Sevastopol',
'Midway Islands',
'Wake Island',
'Howland Island',
'Kingman Reef',
'Guam',
'United States Minor Outlying Islands',
'Canelones',
'Colonia',
'Florida',
'Lavalleja',
'Paysandu',
'Rocha',
'Salto',
'Soriano',
'Treinta y Tres',
'Buxoro',
'Jizzax',
'Navoiy',
'Qoraqalpog''iston Respublikasi',
'Sirdaryo',
'Toshkent',
'Saint Patrick',
'Lao Cai',
'Cao Bang',
'Yen Bai',
'L?ng Son',
'Hoa Binh',
'Thai Binh',
'Nghe An',
'Quang Binh',
'Thua Thien-Hue',
'Kon Tum',
'Gia Lai',
'Phu Yen',
'Khanh Hoa',
'Ninh Thuan',
'Dong Nai',
'Long An',
'An Giang',
'Tien Giang',
'Vinh Long',
'Tra Vinh',
'Bac K?n',
'B?c Lieu',
'Binh Phuoc',
'Hai Duong',
'Hung Yen',
'Phu Th?',
'Da Nang',
'Sanma',
'Torba',
'Aiga-i-le-Tai',
'Fa''asaleleaga',
'Gagaifomauga',
'Satupa''itea',
'Vaisigano',
'Adan',
'Al BayDa',
'Dhamar',
'Hajjah',
'Ibb',
'LaHij',
'Al Mahrah',
'Sa?dah',
'Ta?izz',
'Eastern',
'Northern',
'Southern',
'Manicaland',
'Mashonaland East',
'Matabeleland North',
'Masvingo',
'Ain',
'Allier',
'Hautes-Alpes',
'Ardèche',
'Ariège',
'Aude',
'Calvados',
'Charente',
'Cher',
'Côte-d''Or',
'Creuse',
'Doubs',
'Eure',
'Finistère',
'Haute-Corse',
'Haute-Garonne',
'Hérault',
'Indre',
'Landes',
'Loire',
'Loire-Atlantique',
'Lot',
'Lozère',
'Manche',
'Meurthe-et-Moselle',
'Morbihan',
'Nièvre',
'Oise',
'Pas-de-Calais',
'Pyrénées-Atlantiques',
'Pyrénées-Orientales',
'Haut-Rhin',
'Haute-Saône',
'Sarthe',
'Haute-Savoie',
'Seine-et-Marne',
'Somme',
'Tarn-et-Garonne',
'Vaucluse',
'Vienne',
'Vosges',
'Territoire de Belfort',
'Seine-Saint-Denis',
'Val-d''Oise',
'Corse',
'Hauts-de-France',
'Nouvelle-Calédonie',
'Terres australes françaises',
'Estuaire',
'Moyen-Ogooué',
'Nyanga',
'Ogooué-Lolo',
'Woleu-Ntem',
'Blackburn with Darwen',
'Bexley',
'Bolton',
'Causeway Coast and Glens',
'Calderdale',
'Derby',
'Flintshire ',
'Gateshead',
'Havering',
'Kingston upon Hull',
'Lewisham',
'Mid and East Antrim',
'Merton',
'Mid Ulster',
'Neath Port Talbot ',
'Newham',
'Plymouth',
'Rhondda, Cynon, Taff',
'Sandwell',
'Stockport',
'Stoke-on-Trent',
'Sutton',
'Tameside',
'Thurrock',
'Torfaen',
'West Dunbartonshire',
'Wigan',
'Wokingham',
'Eilean Siar',
'Inverclyde',
'North Ayrshire',
'North Lanarkshire',
'Bury',
'Kwazulu-Nata',
'Greater China',
'International',
'South East Asia Region',
'BRIC',
'Varna',
'Grand-Est',
'Ards and North Down',
'Brent',
'Birmingham',
'Barnet',
'Bradford',
'Coventry',
'Conwy',
'Dumfries and Galloway',
'Dundee City',
'Dudley',
'Enfield',
'Greenwich',
'Hillingdon',
'Hammersmith and Fulham',
'Harrow',
'Islington',
'Kingston upon Thames',
'Lambeth',
'Luton',
'Milton Keynes',
'Nottingham',
'Newport',
'Perth and Kinross',
'Redcar and Cleveland    ',
'Redbridge',
'Sheffield',
'Salford',
'South Lanarkshire',
'Stockton-on-Tees',
'Southwark',
'West Berkshire',
'Wolverhampton',
'Wirral',
'Ashanti',
'Kentrikí Makedonía',
'Veszprem',
'Komarom-Esztergom',
'Eschen',
'Triesenberg',
'Schaan',
'Balzers',
'Mauren',
'Druskininkai',
'Ukmerge',
'Trakai',
'Panevezys',
'Clervaux',
'Livanu novads',
'Liepaja',
'Ropazu novads',
'Rezeknes novads',
'Marupes novads',
'Ogres novads',
'Aglonas novads',
'Kekavas novads',
'Talsu novads',
'Garkalnes novads',
'Jekabpils',
'Madonas novads',
'Incukalna novads    ',
'Salaspils novads',
'Jelgava',
'Gulbenes novads',
'Siguldas novads',
'Lija',
'Rabat Gozo',
'Naxxar',
'Paola',
'Mellieha',
'Zejtun',
'Nadur',
'Gzira',
'Safi',
'Santa Venera',
'Birkirkara',
'Swieqi',
'Bormla',
'Marsa',
'Zabbar',
'Saint Paul''s Bay',
'Xghajra',
'Msida',
'Birzebbuga',
'Saint John',
'Ta'' Xbiex',
'Iklin',
'Zebbug Malta',
'Attard',
'Rabat Malta',
'Plaines Wilhems',
'Pamplemousses',
'Moka',
'Grand Port',
'Black River',
'Gisborne',
'Waikato',
'Taranaki',
'Canterbury',
'Bay of Plenty',
'Marlborough',
'Punjab',
'Sindh',
'Portalegre',
'Guarda',
'Beja',
'Coimbra',
'Calarasi',
'Medvode',
'Hatay',
'Izmir',
'Tuamasaga',
'Wrexham',
'York',
'Principality of Asturias',
'Trøndelag',
'Ascension Island',
'Clipperton Island',
'Diego Garcia',
'Tristan da Cunha',
'Euro Market',
'United Nations',
'Unknown States',
'Saint George',
'Saint Philip',
'Sowa Town',
'Xianggang Tebiexingzhengqu',
'Aomen Tebiexingzhengqu',
'Taiwan Sheng',
'Nymburk',
'Praha-vychod',
'Praha-zapad',
'Prachatice',
'Strakonice',
'Litomerice',
'Hradec Kralove',
'Pelhrimov',
'Blansko',
'Breclav',
'Vyskov',
'Saint David',
'Saint John',
'Lomaiviti',
'La Reunion',
'Saint-Martin',
'Bungoma',
'Kilifi ',
'Machakos',
'Saint James Windward',
'Saint Paul Capisterre',
'Aakkar',
'River Gee',
'Alytus',
'Birstono',
'Kretinga',
'Moletai',
'Plunge',
'Siauliu miestas',
'Svencionys',
'Telsiai',
'Utena',
'Vianden',
'Alojas novads',
'Apes novads',
'Cesu novads',
'Karsavas novads',
'Priekulu novads',
'Rojas novads',
'Tukuma novads',
'Valmiera',
'Rabat-Sale-Kenitra',
'Casablanca-Settat',
'La Colle',
'La Gare',
'Port-Hercule',
'Vallon de la Rousse',
'Berovo',
'Prilep',
'Sopiste',
'Nouakchott Ouest',
'Ghaxaq',
'Kercem',
'Mtarfa',
'Pembroke',
'Qala',
'Sannat',
'Wilayah Persekutuan Putrajaya    ',
'Kavango East',
'Embera',
'Mimaropa',
'Hebron',
'Jenin',
'Macvanski okrug',
'Branicevski okrug',
'Borski okrug',
'Zabaykal''skiy kray',
'Grand Anse Praslin',
'Faetano',
'Central Equatoria',
'Lienchiang',
'Songwe',
'Bududa',
'Saint David',
'Creek',
'Nei Mongol (Inner Mongolia)',
'Ratchaburi',
'Atlantico',
'Ha Noi',
'Torino',
'Brussels (Bruxelles)',
'Mures',
'Constanta',
'Larnaca',
'Vrancea',
'Plovdiv',
'Buzau',
'Moravia-Silesia',
'Maramures',
'Braila',
'Richmond upon Thames',
'Castelo Branco',
'Vila Real',
'Ar Riyad',
'Makkah al Mukarramah',
'Ash Sharqiyah',
'''Asir',
'Al Madinah al Munawwarah',
'Busan',
'Ulsan',
'Incheon',
'Lagos',
'Cork',
'Lisboa',
'Majro',
'Lefkosia',
'Paris',
'Nairobi',
'Scotland',
'Sofia',
'Istanbul',
'Region of Southern Denmark',
'Northern Ireland',
'England',
'Kampala',
'Valencia',
'Capital Region of Denmark',
'Luxembourg',
'Montevideo',
'Aberdeen City',
'Bristol, City of',
'Sharjah',
'Edinburgh, City of',
'Floriana',
'Saint Michael',
'Monte-Carlo',
'Carmarthenshire',
'San Giljan',
'Attica',
'Cheshire West and Chester',
'Falkirk',
'England and Wales',
'Escaldes-Engordany',
'Qormi',
'Sliema',
'Mosta',
'Kalkara',
'Swindon',
'Capital Governorate',
'Kensington and Chelsea',
'Ciudad de Mexico',
'AlHudud ash Shamaliyah',
'Ras Al Khaimah',
'Sjaelland',
'Antrim and Newtownabbey',
'Moulins',
'National Capital Region',
'Asia Pacific Rim',
'Middle East/Africa',
'Northwest Territories',
'Heilongjiang',
'Hubei',
'Tianjin',
'Jilin',
'Hunan',
'Ningxia Hui',
'Jiangsu',
'Guizhou',
'Gansu',
'Xinjiang Uygur',
'Qinghai',
'Brestskaya vobl.',
'Homyelskaya vobl.',
'Hrodzyenskaya vobl.',
'Mahilyowskaya vobl.',
'Minskaya vobl.',
'Vitsyebskaya vobl.',
'Acre',
'Amapá',
'Amazonas',
'Bahia',
'Ceará',
'Distrito Federal',
'Espírito Santo',
'Maranhão',
'Mato Grosso do Sul',
'Minas Gerais',
'Pará',
'Paraíba',
'Piauí',
'Rio Grande do Sul',
'Roraima',
'São Paulo',
'Sergipe',
'Tocantins',
'Hainan Province',
'Hebei Province',
'Henan Province',
'Inner Mongolia Province',
'Jiangxi Province',
'Jilin Province',
'Liaoning Province',
'Ningxia Hui Province',
'Shaanxi Province',
'Xinjiang Uygur Province',
'Xizang Province',
'Co. Carlow',
'Co. Cavan',
'Co. Clare',
'Co. Donegal',
'Co. Dublin',
'Co. Galway',
'Co. Kerry',
'Co. Kildare',
'Co. Kilkenny',
'Co. Limerick',
'Co. Longford',
'Co. Louth',
'Co. Mayo',
'Co. Meath',
'Co. Monaghan',
'Co. Roscommon',
'Co. Sligo',
'Co. Tipperary',
'Co. Waterford',
'Co. Westmeath',
'Co. Wexford',
'Akita',
'Aomori',
'Chiba',
'Ehime',
'Fukui',
'Fukuoka',
'Gifu',
'Gunma',
'Hiroshima',
'Hokkaido',
'Hyogo',
'Ibaraki',
'Iwate',
'Kagawa',
'Kagoshima',
'Kanagawa',
'Kochi',
'Kumamoto',
'Miyazaki',
'Nagano',
'Nara',
'Niigata',
'Okayama',
'Saitama',
'Shimane',
'Shizuoka',
'Tochigi',
'Tokushima',
'Tottori',
'Toyama',
'Yamagata',
'Yamaguchi',
'Yamanashi',
'Chagang Province',
'Kangwon Province',
'North Hamgyong Province',
'North P''yongan Province',
'South Hamgyong Province',
'South Hwanghae Province',
'South P''yongan Province',
'Ryanggang-do',
'Adygeya',
'Altaysky kray',
'Amurskaya obl.',
'Arkhangelskaya obl.',
'Astrakhanskaya obl.',
'Bashkortostan',
'Bryanskaya obl.',
'Buryatiya',
'Chechnya',
'Chelyabinskaya obl.',
'Chitinskaya obl.',
'Chuvashiya',
'Dagestan',
'Evenkiyskiy AO',
'Evreyskaya obl.',
'Habarovsky kray',
'Hanty-Mansiysky AO',
'Ingushetiya',
'Irkutskaya obl.',
'Ivanovskaya obl.',
'Kabardino-Balkariya',
'Kalmykiya',
'Kaluzhskaya obl.',
'Kamchatskaya obl.',
'Karachaevo-Cherkessiya',
'Karelia',
'Kirovskaya obl.',
'Komi',
'Komi-Permyatsky AO',
'Koryaksky AO',
'Kostromskaya obl.',
'Krasnoyarsky kray',
'Kurganskaya obl.',
'Kurskaya obl.',
'Lipetskaya obl.',
'Magadanskaya obl.',
'Moskovskaya obl.',
'Murmanskaya obl.',
'Nenetsky AO',
'Nizhegorodskaya obl.',
'Omskaya obl.',
'Orlovskaya obl.',
'Penzenskaya obl.',
'Permskaya obl.',
'Primorsky kray',
'Pskovskaya obl.',
'Ryazanskaya obl.',
'Saha',
'Sakhalinskaya obl.',
'Samarskaya obl.',
'Saratovskaya obl.',
'Smolenskaya obl.',
'Stavropolsky kray',
'Tambovskaya obl.',
'Tatarstan',
'Taymyrsky AO',
'Tuva',
'Tverskaya obl.',
'Tyumenskaya obl.',
'Udmurtiya',
'Ulyanovskaya obl.',
'Vladimirskaya obl.',
'Vologodskaya obl.',
'Voronezhskaya obl.',
'Yamalo-Nenetsky AO',
'Yaroslavskaya obl.',
'Chungcheongnam-do',
'Gangwon-do',
'Gyeonggi-do',
'Gyeongsangbuk-do',
'Gyeongsangnam-do',
'Jeollabuk-do',
'Jeollanam-do',
'Avtonomna Respublika Krym',
'Cherkaska obl.',
'Chernihivska obl.',
'Dnipropetrovska obl.',
'Donetska obl.',
'Ivano-Frankivska obl.',
'Kharkivska obl.',
'Khersonska obl.',
'Kirovohradska obl.',
'Kyyivska obl.',
'Luhanska obl.',
'Lvivska obl.',
'Mykolayivska obl.',
'Poltavska obl.',
'Rivnenska obl.',
'Sumska obl.',
'Ternopilska obl.',
'Volynska obl.',
'Zakarpatska obl.',
'Zaporizka obl.',
'Zhytomyrska obl.',
'Angus',
'Bedfordshire',
'Buckinghamshire',
'Cambridgeshire',
'Clackmannanshire',
'Cornwall',
'County Antrim',
'County Armagh',
'County Durham',
'County Fermanagh',
'Cumbria',
'Derbyshire',
'Dorset',
'East Lothian',
'East Sussex',
'Fife',
'Gwent',
'Gwynedd',
'Hampshire',
'Herefordshire',
'Isle of Orkney',
'Isle of Wight',
'Isles of Scilly',
'Lancashire',
'Lincolnshire',
'Midlothian',
'Norfolk',
'North Yorkshire',
'Northumberland',
'Oxfordshire',
'Staffordshire',
'Suffolk',
'Warwickshire',
'West Lothian',
'West Sussex',
'Wiltshire',
'Bonaire',
'Saba',
'Saint Eustatius',
'Rutland',
'Buenos Aires',
'Catamarca',
'Chaco',
'Chubut',
'Entre Rios',
'Formosa',
'Jujuy',
'La Pampa',
'Mendoza',
'Misiones',
'Nuequen',
'Rio Negro',
'Santa Cruz',
'Santa Fe',
'Santiago del Estero',
'Tierra del Fuego',
'Amazonas',
'Anzoategui',
'Apure',
'Aragua',
'Carabobo',
'Cojedes',
'Delta Amacuro',
'Dependencias Federales',
'Falcon',
'Guarico',
'Lara',
'Merida',
'Monagas',
'Nueva Esparta',
'Portuguesa',
'Sucre',
'Trujillo',
'Vargas',
'Yaracuy',
'Araucania',
'Atacama',
'Bio-Bio',
'Los Lagos',
'Magallanes y de la Antartica Chilean',
'Maule',
'Valparaiso',
'Andaman and Nicobar Islands',
'Andhra Pradesh',
'Assam',
'Bihar',
'Chandigarh',
'Dadra and Nagar Haveli',
'Daman and Diu',
'Delhi',
'Himachal Pradesh',
'Jammu and Kashmir',
'Jharkhand',
'Kerala',
'Lakshadweep',
'Madhya Pradesh',
'Manipur',
'Meghalaya',
'Mizoram',
'Orissa',
'Pondicherry',
'Punjab',
'Sikkim',
'Tamil Nadu',
'Tripura',
'Uttar Pradesh',
'West Bengal',
'Aguascalientes',
'Baja California South',
'Chiapas',
'Coahuila',
'Distrito Federal',
'Michoacan',
'Morelos',
'Queretaro',
'San Luis Potosi',
'Tlaxcala',
'Aceh',
'Bali',
'Bengkulu',
'Jambi',
'Jawa Barat',
'Jawa Tengah',
'Kalimantan Selatan',
'Kalimantan Tengah',
'Kepulauan Bangka Belitung',
'Maluku',
'Maluku Utara',
'Nusa Tenggara Barat',
'Riau',
'Sulawesi Selatan',
'Sulawesi Tengah',
'Sulawesi Utara',
'Sumtera Barat',
'Sumtera Selatan',
'Chieti',
'L''Aquila',
'Pescara',
'Matera',
'Potenza',
'Catanzaro',
'Crotone',
'Reggio Calabria',
'Vibo Valentia',
'Benevento',
'Caserta',
'Salerno',
'Bologna',
'Forlì',
'Modena',
'Kedah',
'Kelantan',
'Melaka',
'Negeri Sembilan',
'Perak',
'Perlis',
'Sabah',
'Sarawak',
'Terengganu',
'Wilayah Persekutuan',
'Ancash',
'Apurimac',
'Ayacucho',
'Cajamarca',
'Cusco',
'Huancavelica',
'Ica',
'Junin',
'Lambayeque',
'Lima',
'Madre de Dios',
'Moquequa',
'Piura',
'Puno',
'Tacna',
'Tumbes',
'Parma',
'Piacenza',
'Rimini',
'Gorizia',
'Trieste',
'Udine',
'Latina',
'Rieti',
'Viterbo',
'Genoa',
'La Spezia',
'Savona',
'Brescia',
'Como',
'Lecco',
'Lodi',
'Pavia',
'Sondrio',
'Ancona',
'Ascoli Piceno',
'Pesaro',
'Campobasso',
'Alessandria',
'Asti',
'Cuneo',
'Novara',
'Verbano Cusio Ossola',
'Vercelli',
'Brindisi',
'Foggia',
'Taranto',
'Cagliari',
'Oristano',
'Sassari',
'Caltanissetta',
'Catania',
'Messina',
'Ragusa',
'Trapani',
'Florence',
'Livorno',
'Massa Carrara',
'Pistoia',
'Siena',
'Trento',
'Terni',
'Belluno',
'Rovigo',
'Venice',
'Co. Laois',
'Flevoland',
'Groningen',
'Noord-Holland',
'Utrecht',
'Burgenland',
'Tyrol',
'Kainuu',
'Satakunta',
'Alsace',
'Auvergne',
'Brittany',
'Centre',
'Corsica',
'French Guiana',
'Haute-Normandie',
'Languedoc-Roussillon',
'Lorraine',
'Midi-Pyrénées',
'Picardy',
'Provence-Alpes-Côte d''Azur',
'Rhône-Alpes',
'Berlin',
'Bremen',
'Hessen',
'North Rhine-Westphalia',
'Saarland',
'Akershus',
'Buskerud',
'Hedmark',
'Jan Mayen',
'Oppland',
'Østfold',
'Sogn og Fjordane',
'Svalbard',
'Troms',
'Vest-Agder',
'Vestfold',
'Eastern Cape',
'Free State',
'Limpopo',
'Mpumalanga',
'North-West',
'Blekinge County',
'Dalarna County',
'Gävleborg County',
'Gotland County',
'Halland County',
'Jämtland County',
'Jönköping County',
'Kalmar County',
'Norrbotten County',
'Örebro County',
'Östergötland County',
'Skåne County',
'Södermanland County',
'Uppsala County',
'Värmland County',
'Västerbotten County',
'Västmanland County',
'Västra Götaland County',
'Aargau',
'Appenzell Ausser Rhoden',
'Appenzell Inner Rhoden',
'Basel-Landschaft',
'Basel-Stadt',
'Fribourg',
'Geneva',
'Glarus',
'Grisons',
'Jura',
'Lucerne',
'Nidwalden',
'Obwalden',
'Schaffhausen',
'Schwyz',
'Solothurn',
'Thurgau',
'Ticino',
'Uri',
'Valais',
'Vaud',
'Brussels',
'Flemish Brabant',
'Hainaut',
'Liège',
'Luxembourg',
'Namur',
'Walloon Brabant',
'Olbia-Tempio',
'Carbonia-Iglesias',
'Medio Campidano',
'Osaka',
'Mayotte',
'Guernsey',
'Franz Josef Land',
'Gorno-Altayskaya AO',
'Argyllshire',
'Avon',
'Banffshire',
'Berkshire',
'Cleveland',
'County Londonderry',
'Dumfriesshire',
'Dyfed',
'Isle of Arran',
'Isle of Benbecula',
'Isle of Bute',
'Isle of Canna',
'Isle of Coll',
'Isle of Colonsay',
'Isle of Cumbrae',
'Isle of Eigg',
'Isle of Gigha',
'Isle of Iona',
'Isle of Lewis',
'Isle of North Uist',
'Isle of Scalpay',
'Isle of Shetland',
'Isle of Skye',
'Isle of South Uist',
'Isle of Tiree',
'Kincardineshire',
'Kinross-shire',
'Kirkudbrightshire',
'Merseyside',
'Middlesex',
'Nairnshire',
'Perthshire',
'Renfrewshire',
'Ross-shire',
'Roxburghshire',
'Selkirkshire',
'Shropshire',
'Somerset',
'South Glamorgan',
'South Yorkshire',
'Stirlingshire',
'Tyne and Wear',
'West Glamorgan',
'West Midlands',
'West Yorkshire',
'Wigtownshire',
'Yorkshire',
'American Samoa',
'Marshall Islands',
'Palau',
'Grand Cayman',
'Curacao',
'Saint Maarten',
'Tortola',
'Greater Manchester',
'Greater London',
'New Territories',
'Kowloon',
'Capital Federal',
'Aisen del General Carols Ibanez',
'Irian Jaya',
'Andalusia',
'Aragon',
'Balearic Islands',
'Canary Islands',
'Cantabria',
'Castile-La Mancha',
'Catalonia',
'Valencian Community',
'Extremadura',
'La Rioja',
'Region of Murcia',
'Navarre',
'Tayside',
'Humberside',
'Borders',
'Lower Austria',
'Styria',
'Capital Region of Denmark',
'Central Denmark Region',
'North Denmark Region',
'Region of Southern Denmark',
'Zealand Region',
'Central Finland',
'Eastern Uusimaa',
'Kymenlaakso',
'North Karelia',
'Northern Savonia',
'Ostrobothnia',
'Päijänne Tavastia',
'South Karelia',
'Southern Ostrobothnia',
'Southern Savonia',
'Tavastia Proper',
'Bavaria',
'Saxony',
'Saxony-Anhalt',
'Alentejo',
'Algarve',
'Azores',
'Centro',
'Lisbon',
'Madeira',
'Norte',
'East Flanders',
'West Flanders',
'Isle of Man',
'Kaduna',
'Abia',
'Osun',
'IMO',
'Kano',
'Edo',
'Anambra',
'Akwa Ibom',
'Giurgiu',
'Westminster',
'Timis',
'Belfast City',
'Porto',
'Isère',
'Somogy',
'Leeds',
'Bucuresti',
'Arad',
'Alba',
'Córdoba',
'Ilfov',
'Viana do Castelo',
'Santarém',
'Belize',
'North Andros',
'Viseu',
'English River',
'Braga',
'Setúbal',
'Central Singapore',
'Faro',
'Liverpool',
'Osijek-Baranja',
'Silesia',
'Jelgavas novads',
'Lower Silesia',
'Emilia-Romagna',
'Évora',
'Wakefield',
'Shéfa',
'Aveiro',
'Barcelona [Barcelona]',
'Attikí',
'Tower Hamlets',
'Mazovia',
'Bratislavský kraj',
'Harju',
'Phra Nakhon Si Ayutthaya',
'Leiria',
'Praha 9',
'Ad Dawhah',
'Praha 1',
'Dolj',
'Rugaju novads',
'Marne',
'Gironde',
'Beroun',
'Alacant',
'Burgos',
'Nitriansky kraj',
'Olomouc',
'Vesturland',
'Klaipedos Apskritis',
'Vilniaus Apskritis',
'Kauno Apskritis',
'West-Vlaanderen',
'Kuyavia-Pomerania',
'Holy Cross',
'Pomerania',
'Greater Poland',
'West Pomerania',
'Opole (Upper Silesia)',
'Lublin',
'Lubusz',
'Lesser Poland',
'Lódzkie',
'Podlaskie',
'Subcarpathia',
'Olt',
'Warmia-Masuria',
'Leymasun',
'Utenos Apskritis',
'North Humberside',
'Leipzig',
'Princeton',
'Dnipro',
'Valparaiso',
'Ceuta',
'Melilla',
'Western Australia',
'Vlaams Gewest',
'Burma',
'Neutral Zone',
'Bissau',
'Port-au-Prince',
'Pangkalpinang',
'Tangerang',
'Ahmedabad',
'Dharwad',
'Hyderabad',
'Kanpur',
'Pune',
'Rudrapur',
'Surat',
'Tiruchirapalli',
'Phnom Penh',
'Tarawa',
'Moroni',
'Basseterre',
'Pyongyang',
'Astana',
'Vientiane',
'Matara',
'Monrovia',
'Tripoli',
'Rabat',
'Monaco',
'Podgorica',
'Marigot',
'Bamako',
'Yangon',
'Saipan',
'Fort-de-France',
'Nouakchott',
'Brades',
'Male',
'Kuching',
'Sepang',
'Noumea',
'Niamey',
'Kingston (Norfolk Island)',
'Granada',
'Kongsvinger',
'Yaren',
'Alofi',
'Ruwi',
'Papeete',
'Iloilo',
'Quezon City',
'Bacolod',
'Makati City',
'Pasay City',
'Taguig City',
'Lahore',
'Saint-Pierre',
'Adamstown',
'West Bank',
'Ponta Delgada',
'Koror',
'Saint-Denis',
'Krasnoyarsk',
'Murmansk',
'Rostov-na-Donu',
'Jeddah',
'Arlandastad',
'Jamestown',
'San Marino',
'Mogadishu',
'Juba',
'La Libertad',
'Philipsburg',
'Cockburn Town',
'Lome',
'Dili',
'Fongafale (Funafuti)',
'Des Moines',
'Salt Lake City',
'Vienna (USA)',
'Vatican City',
'Kingstown',
'Charlotte Amalie',
'Mata-Utu',
'Apia',
'Sana''a',
'Mamoudzou',
'Cape Town',
'Pretoria',
'New Providence',
'Ñuble',
'    Avannaata Kommunia',
'Kommune Qeqertalik',
'Shymkent',
'Trøndelag',
'Hhohho',
'Chongqing',
'Fujian',
'Guangdong',
'Hebei',
'Jiangxi',
'Zhejiang',
'Panama Canal Zone (old)',
'Coins and precious metals',
'South Sudan',
'Zachodniopomorskie',
'Dolnoslaskie',
'Opolskie',
'Kujawsko-pomorskie',
'Wielkopolskie',
'Warminsko-mazurskie',
'Slaskie',
'Swietokrzyskie',
'Podkarpackie',
'Mazowieckie',
'Lubelskie',
'Malopolskie',
'Lubuskie',
'Podlaskie',
'Pomorskie',
'Lódzkie',
'Switzerland',
'Pasig City',
'Tashkent',
'Lilongwe',
'Various countries,Contributors',
'New York City',
'Jakarta',
'Dhaka',
'Paris',
'Saskatchewan',
'Vancouver',
'Bridgetown',
'Dalian',
'Others',
'Timor-Leste',
'Boat',
'Los Angeles',
'Lugano',
'Central America',
'Austroce',
'Montreal',
'Britain',
'Blantyre',
'Dar es Salaam',
'Rio de Janeiro',
'Outdated National Currencies',
'Santo Domingo',
'Winnipeg',
'Kobe',
'Beijing',
'Abu Dhabi',
'Kansas City',
'Mie',
'Nagasaki',
'Public Hsg/New Housing',
'Trust Bond',
'United States (agencies, treasuries)',
'Turin',
'Canal Zone',
'Port Moresby',
'Basel Land',
'Odessa',
'Yugoslavia',
'Quito',
'Tessin',
'NASDAQ - Europe',
'Appenzell Ausserrhoden',
'Unknown',
'Madrid',
'Seoul',
'Uri',
'Hamilton',
'Gaborono',
'Caribbean',
'Africa',
'W. African Eco. Monetary Union',
'Nagoya',
'Georgetown',
'Nova Scotia',
'Curacao',
'Bern',
'EU Member State',
'Bahrain',
'Mexico',
'Ljubljana',
'US Terr. of Pacific (old)',
'Valencia',
'Budapest',
'Saint Petersburg',
'U.S. Regions',
'SNAT',
'Interest Rate',
'Luxembourg',
'Kigali',
'Lusaka',
'Sarajevo',
'Alma-Ata',
'Kiev',
'U.S. Northeast',
'Default',
'Copenhagen',
'Ottawa',
'British Indian Ocean Territory (the)',
'Quebec',
'The Hague',
'Ulaan Baatar',
'CHNL',
'Gibraltar',
'U.S. Southwest',
'Bangalore',
'Lagos',
'St. Gallen',
'Zug',
'Misc',
'Whitehorse',
'Shanghai',
'Canton + Enderbury',
'San Francisco',
'Various Countries,Contributors (Internal)',
'Vienna',
'Bratislava',
'Thimphu',
'Rosario',
'Thurgau',
'Yukon Territory',
'Jersey City',
'Sao Paulo',
'French Southern Territories',
'Various Regional Groups',
'Other Terr.',
'Lisboa',
'Asia',
'Novosibirsk',
'Brisbane',
'Hong Kong',
'Ankara',
'Casablanca',
'All Countries with State Agreement',
'Seborga',
'Cairo',
'El Salvador',
'Balkan Regions',
'Duedsseldorf',
'Manila',
'Warsaw',
'Kosovo',
'Tunis',
'Colombo',
'Madras',
'Default (set by LSE)',
'San Salvador',
'British Columbia',
'Taipei',
'Managua',
'Minsk',
'Australasia',
'Tirana',
'Aichi',
'Belgrade',
'Hempstead Township',
'Samara',
'Nasau',
'Saskatchewan',
'Far East',
'Ekaterinburg',
'Christchurch',
'Western Europe/Central Europe',
'Eurex',
'Calcutta',
'Victoria',
'Ontario',
'Genf',
'Windhoek',
'Newex',
'La Paz',
'Abbr for Nebraska used in patents prior to July 4,1978 was NB rather than NE',
'Alberta',
'MTS Markets',
'Valletta',
'N.W.Territories',
'Queens',
'British Isles',
'Panama',
'Mediterranean',
'European Monetary Union',
'Niedwalden',
'Tokyo',
'Middle East',
'Brooklyn',
'Amsterdam',
'Baku',
'Road Town',
'U.S. Northwest',
'Honiara',
'Luanda',
'Labuan',
'Quebec',
'Mbabane',
'Schwyz',
'Santiago',
'Vilnius',
'Minneapolis',
'Vaud',
'Nigeria',
'Auckland',
'Olso',
'Staten Island',
'Unknown Country',
'Edmonton',
'Index',
'Serbia and Montenegro',
'North Macedonia',
'Unknown',
'U.S. Southeast',
'Exchange Rate',
'Perth',
'Europe',
'Milano',
'East European Countries',
'American Samoa',
'Curacao',
'Europe excluding UK',
'International Institution',
'Johannesburg',
'Frankfurt am Main',
'Newfoundland (Abbrev)',
'Dunedin',
'Zurich',
'Queensland (abbrev)',
'US Terr. of Pacific (old)',
'Tegucigalpa',
'U.S. New England',
'Berlin',
'Dubai',
'Nukualofa',
'Antananarivo',
'Maputo',
'Abidjan',
'Rome',
'Majuro',
'Teheran',
'Kingston',
'Boston',
'Scandinavia',
'Dar',
'Palestinian Territory Occupied',
'Surabaya',
'Arctic',
'Obwalden',
'Athens',
'Iqaluit',
'Singapore',
'Karachi',
'Anguilla',
'Nablus',
'Muscat',
'Praia',
'Nuuk',
'Brussels',
'San Juan',
'Prague',
'Oranjestad',
'Neuchatel',
'Misc',
'Baltics',
'Bangkok',
'Appezell Innerrhoden',
'Valais',
'Asia Pacific',
'Equatorial Guinea',
'AU Northern Territories',
'Telekurs AG (TK-Key)',
'Lima',
'Kampala',
'London',
'Islamabad',
'SNAT',
'Oceania',
'Freetown',
'Kuala Lumpur',
'Tallinn',
'Harare',
'Geneva',
'Guayaquil',
'Georgetown',
'Buenos Aires',
'Dummy ISIN CDS (Canada)',
'Muenchen',
'EUSD Information Jurisdiction not Provided',
'Sofia',
'Jerusalem',
'Vaduz',
'Central and Eastern Europe',
'Guernsay',
'Damascus',
'Andorra La Vella',
'Berne',
'Beyrouth',
'Euro Monetary Area',
'Alberta (Abbrev)',
'Philadelphia',
'Bremen',
'Zagreb',
'Phoenix',
'Ashkhabad',
'Canal Zone (obsolete)',
'Istambul',
'Dublin',
'Latin America',
'Riga',
'Pacific Rim',
'Not assignable to any domicile',
'Indian Subcontinent',
'Escud',
'Europe/Middle East/Africa',
'Former USSR',
'Dushanbe',
'Kharkov',
'Danzig(old)',
'Stuttgart',
'Mumbai',
'Hanoi',
'Mult',
'Jura',
'Stanley',
'U.S. Minor Outlying Islands',
'Kishinev',
'Lucerne',
'Bujumbura',
'Chisinau',
'BH',
'Jersey',
'AU Capital Territories',
'Caracas',
'Newfoundland',
'Pridneprovsk',
'France, Metropolitan (old)',
'Bronx',
'Ontario (Abbrev)',
'Hobart',
'Portugese Guinea (old)',
'Delhi',
'Zhengzhou',
'Canberra',
'Tbilisi',
'Manhattan',
'Newcastle',
'Pacific Region Excl. Japan',
'Nicosia (Lefkosia)',
'AU Other Territories',
'Tasmania (abbrev)',
'Rarotonga',
'Macau',
'St. Johns',
'Nairobi',
'Chicago',
'Basel Stadt',
'XE',
'Manama',
'Prince Edward Island',
'Basle',
'Calgary',
'Americas Zone',
'Shimonoseki',
'Suva',
'DOM ISIN (internal)',
'Algiers',
'Graubuenden',
'New York',
'Port Louis',
'Khorezm',
'Port of Spain',
'Guatemala',
'Pusan',
'Schaffhausen',
'Friburg',
'Nizhniy Novgorod',
'San Pedro Sula',
'Chittagong',
'Zaire',
'Kathmandu',
'French Antilles (old)',
'Fukuoka',
'Yerevan',
'Khartoum',
'Zurich',
'Port Vila',
'Bogota',
'Bandar Seri Begawan',
'Bilbao',
'Comoros',
'Hamburg',
'Wellington',
'South Australia (abbrev)',
'Supranat',
'Bucharest',
'Accra',
'Dummy ISIN Cusip (USA)',
'Quebec City',
'Munich',
'Guangzhou',
'World-Wide (Global)',
'Douglas',
'US American Samoa',
'Oecd Member Countries',
'Barcelona',
'Brasilia',
'Dresden',
'Northern Mariana Islands',
'Paramaribo',
'Asia Pacific Zone',
'Edison Township',
'Emerging Markets',
'Glarus',
'Reykjavik',
'XE',
'St.Helier',
'United States Minor Outlying Islands (the)',
'CHNL',
'Stockholm',
'AU Capital Territories (Abbrev)',
'Saint Martin (French part)',
'South America',
'Yokohama',
'U.S. Midwest',
'Curitiba',
'Darwin',
'iBoxx',
'Federal Agencies',
'Rijad',
'Isle of Man',
'Aargau',
'Solothurn',
'Australia/New Zealand',
'Bishkek',
'West-indian States (old)',
'Sydney',
'Rotterdam',
'Montevideo',
'San Jose',
'Cape Verde',
'Toronto',
'Moscow',
'Sapporo',
'Adelaide',
'Kuwait',
'Doha',
'Belmopan',
'New Brunswick',
'Rome',
'Shenzhen',
'Nordic Growth Market',
'Tel Aviv',
'Addis Ababa',
'Rostov',
'US Virgin Islands',
'European Zone',
'Vladivostok',
'Osaka',
'European Economic Area',
'Helsinki',
'Multi Country',
'Washington, D.C.',
'Hannover',
'European Economic Area',
'Temporary Code',
'Chix',
'Melbourne',
'Maseru',
'Pacific Region',
'Asuncion',
'Manitoba',
'European Energy Exchange Futures',
'GFI',
'ICAP',
'Euronext',
'South Sudan',
'Tianjin Shi',
'Hebei Sheng',
'Shanxi Sheng',
'Nei Mongol Zizhiqu',
'Liaoning Sheng',
'Jilin Sheng',
'Heilongjiang Sheng',
'Shanghai Shi',
'Jiangsu Sheng',
'Zhejiang Sheng',
'Anhui Sheng',
'Fujian Sheng',
'Jiangxi Sheng',
'Shandong Sheng',
'Henan Sheng',
'Hubei Sheng',
'Hunan Sheng',
'Guangdong Sheng',
'Guangxi Zhuangzu Zizhiqu',
'Hainan Sheng',
'Chongqing Shi',
'Sichuan Sheng',
'Guizhou Sheng',
'Yunnan Sheng',
'Xizang Zizhiqu',
'Shaanxi Sheng',
'Gansu Sheng',
'Qinghai Sheng',
'Ningxia Huizi Zizhiqu',
'Xinjiang Uygur Zizhiqu',
'Nampâ€™o',
'Kyotera',
'Butebo',
'Namisindwa',
'Omoro',
'Pakwach',
'Kagadi',
'Kakumiro',
'Rubanda',
'Bunyangabu',
'Rukiga',
'Ash Shi?aniyah',
'MÃ©naka',
'TaoudÃ©nit',
'Goiás',
'Paraná',
'Pernambuco',
'Rio de Janeiro',
'Rio Grande do Norte',
'Santa Catarina',
'Anhui Province',
'Chongqing Province',
'Fujian Province',
'Gansu Province',
'Guangdong Province',
'Guangxi Zhuang Province',
'Guizhou Province',
'Hubei Province',
'Jiangsu Province',
'Shandong Province',
'Shanghai Province',
'Shanxi Province',
'Sichuan Province',
'Tianjin Province',
'Yunnan Province',
'Zhejiang Province',
'Aichi',
'Mie',
'Nagasaki',
'Oita',
'Okinawa',
'Saga',
'Leningradskaya obl.',
'Mordoviya',
'Novgorodskaya obl.',
'Novosibirskaya obl.',
'Sverdlovskaya obl.',
'Tulskaya obl.',
'Volgogradskaya obl.',
'Essex',
'Kent',
'Cordoba',
'Bolivar',
'Antofagasta',
'Coquimbo',
'Region Metropolitana (Santiago)',
'Gujarat',
'Haryana',
'Campeche',
'Chihuahua',
'Durango',
'Guerrero',
'Guanajuato',
'Hidalgo',
'Jalisco',
'Mexico State',
'Nayarit',
'Oaxaca',
'Puebla',
'Quintana Roo',
'Sinaloa',
'Sonora',
'Tabasco',
'Tamaulipas',
'Veracruz',
'Yucatan',
'Banten',
'Jakarta Raya',
'Jawa Timur',
'Kalimantan Timur',
'Sumtera Utara',
'Reggio Emilia',
'Milan',
'Vicenza',
'Gelderland',
'Limburg',
'Zuid-Holland',
'Nord-Pas-de-Calais',
'Schleswig-Holstein',
'Northern Cape',
'Stockholm County',
'Zug',
'Zurich',
'Tokyo',
'Hunan Province',
'Northern Mariana Islands',
'Vienna',
'Madrid',
'Carinthia',
'Asia ex-Japan',
'Alberta',
'Capital Terr',
'American Samoa',
'Queensland',
'Tasmania',
'Victoria',
'British Columbia',
'Bonaire, Saint Eustatius and Saba',
'Bonaire, Saint Eustatius and Saba',
'Newfoundland and Labrador',
'CA Nunavut Territory',
'CA Northwest Territories (abbrev)',
'CA Yukon Territory',
'Caldas',
'Cesar',
'Cundinamarca',
'La Guajira',
'Magdalena',
'Meta',
'Quindio',
'Risaralda',
'Sucre',
'Valle Del Cauca',
'Curacao',
'Equatorial',
'Eurozone',
'Federal',
'Camden',
'Solihull',
'Cortes',
'Aomori',
'Akita',
'Chiba',
'Ehime',
'Fukui',
'Fukuoka',
'Fukushima',
'Gifu',
'Gunma',
'Hyogo',
'Hokkaido',
'Hiroshima',
'Ibaraki',
'Ishikawa',
'Iwate',
'Kagawa',
'Kochi',
'Kanagawa',
'Kagoshima',
'Kyoto',
'Kumamoto',
'Miyagi',
'Miyazaki',
'Niigata',
'Nagano',
'Nara',
'Osaka',
'Okayama',
'Shiga',
'Shimane',
'Saitama',
'Shizuoka',
'Tochigi',
'Tokyo',
'Tokushima',
'Toyama',
'Wakayama',
'Yamagata',
'Yamanashi',
'Yamaguchi',
'Corporate Bond',
'Kosovo',
'Western',
'Manitoba',
'St Martin (French part)',
'MULT',
'Newfoundland',
'Northern Terr',
'Northern Terr',
'Nunavut',
'Nunavut',
'N.W. Territories',
'Otago',
'Pr. Edward Island',
'Nunavut',
'Quebec',
'Queensland',
'Association of South-East Asian Nations',
'Gulf Cooperative Council countries',
'Nordic countries',
'South Australia',
'Saskatchewan',
'SLOVAKIA',
'SNAT',
'Santander',
'Cuscatlan',
'Sint Maarten (Dutch part)',
'Sint Maarten (Dutch part)',
'Tasmania',
'Maritime',
'East Timor (old)',
'Trust Bond',
'US Northern Mariana Islands',
'Wales',
'Okinawa',
'Oita',
'Saga',
'Supranational',
'All Regions',
'Emerging Asia(only)',
'Japan(only)',
'Unknown Region',
'United States & Canada',
'Nova Scotia',
'Cusip, subst. agency f. ISIN',
'Euroclear France, substit. agency f. ISIN',
'WM, subst. agency f. ISIN',
'East Carribean',
'Not assignable to any domicile',
'BCEAO (West African States)',
'Others',
'French Pacific Region',
'Multi Country',
'Yukon Territory',
'Various countries,Contributors (internal)',
'Al Ba?ah',
'Al Jawf',
'Al Qasim',
'Al ?udud ash Shamaliyah',
'Jazan',
'Tabuk',
'?a''il',
'SIX Telekurs (TK-Key)',
'Kosovo',
'Curacao (old)',
'World',
'Eurozone',
'Tottori',
'Trust Terr',
'Dili',
'Vorumaa',
'Vidin',
'Vas',
'Ustecky kraj',
'Tirane',
'Telangana',
'Taoyuan',
'Sudurnes',
'Suceava',
'Spanish Wells',
'South Eleuthera',
'South Andros',
'Silale',
'Siauliai',
'Sao Tome',
'Sant Julia de Loria',
'Samut Prakan',
'Salaj',
'Saint Thomas',
'Saint Mary',
'Saint John',
'Saint Andrew',
'Saaremaa',
'Roche Caiman',
'Remich',
'Rayong',
'Raplamaa',
'Polvamaa',
'Pingtung',
'Pest',
'Pathum Thani',
'Pafos',
'Occitanie',
'North East Singapore',
'Nordjylland',
'Niederosterreich',
'Nevis',
'Mubarak al Kabir',
'Mont Fleuri',
'Mersch',
'Mehedin?i',
'Manabi',
'Litoral',
'Littoral',
'Laanemaa',
'Klaipedos miestas',
'Kinshasa',
'Kayseri',
'Kaunas',
'Kalutara',
'Jurbarkas',
'Jazan',
'Irbid',
'Ida-Virumaa',
'Hunedoara',
'Hofudborgarsvaedi',
'Hiiumaa',
'Hauts-de-Seine',
'Harghita',
'HaMerkaz',
'HaDarom',
'Guayas',
'Grevenmacher',
'Keryneia',
'Gala?i',
'Fejer',
'Epirus',
'Egentliga Finland',
'East Grand Bahama',
'Demerara-Mahaica',
'Dakar',
'Daegu-gwangyeoksi',
'Crete',
'Copperbelt',
'Ciudad Autonoma de Buenos Aires',
'Christ Church',
'Charlotte',
'Centre',
'Cascade',
'Capellen',
'Bur Sa''id',
'Bra?ov',
'Boto?ani',
'Bistri?a-Nasaud',
'Bioko Norte',
'Beau Vallon',
'Batna',
'B?c Ninh',
'Austurland',
'Ammochostos',
'Alger',
'Al Mu?arraq',
'Al Gharbiyah',
'Al ''Asimah',
'Ajman',
'Abuja',
'Beirut',
'Gaborone',
'Riyadh',
'Pago Pago',
'Mariehamn',
'Ouagudougou',
'Gustavia',
'Oranjestad (Sint Eustatius)',
'Belo Horizonte',
'Niteroi',
'Recife',
'Fredericton',
'Regina',
'Bangui',
'Haikou',
'Bucaramanga',
'Medellin',
'Havana',
'The Settlement',
'Kiel',
'Mainz',
'Djibouti',
'El Aaiun',
'Las Palmas (Canarias)',
'Zaragoza',
'Palma de Mallorca',
'San Sebastian',
'Palikir',
'Libreville',
'Cayenne',
'Banjul',
'Point-a-Pitre',
'Hagatna',
'Borgo Maggiore',
'Kolda',
'Louga',
'Tambacounda',
'Ziguinchor',
'Bakool',
'Galguduud',
'Hiiraan',
'Jubbada Hoose',
'Nugaal',
'Shabeellaha Dhexe',
'Woqooyi Galbeed',
'Commewijne',
'Marowijne',
'Para',
'Sipaliwini',
'Cabañas',
'Morazan',
'Santa Ana',
'Sonsonate',
'Usulutan',
'Al Hasakah',
'Halab',
'idlib',
'Al Qunaytirah',
'Rif Dimashq',
'Manzini',
'Al BatHah',
'Qira',
'Al BuHayrah',
'Luqun ash Sharqi',
'Tanjili',
'Kara',
'Savanes',
'Lop Buri',
'Chai Nat',
'Chachoengsao',
'Nakhon Nayok',
'Nakhon Ratchasima',
'Surin',
'Ubon Ratchathani',
'Bueng Kan',
'Khon Kaen',
'Loei',
'Maha Sarakham',
'Kalasin',
'Chiang Mai',
'Lampang',
'Phrae',
'Phayao',
'Mae Hong Son',
'Tak',
'Phitsanulok',
'Phetchabun',
'Suphan Buri',
'Samut Sakhon',
'Nakhon Si Thammarat',
'Phangnga',
'Surat Thani',
'Chumphon',
'Pattani',
'Narathiwat',
'Dushanbe',
'Khatlon',
'Baucau',
'Cova Lima',
'Lautem',
'Manufahi',
'Ahal',
'Dasoguz',
'Mary',
'Ben Arous',
'Beja',
'Le Kef',
'Kairouan',
'Sidi Bouzid',
'Sfax',
'Tozeur',
'Gabes',
'Tataouine',
'Agri',
'Antalya',
'Aydin',
'Bilecik',
'Burdur',
'canakkale',
'corum',
'Diyarbakir',
'Erzurum',
'Gaziantep',
'Gumushane',
'isparta',
'Kirsehir',
'Konya',
'Malatya',
'Kahramanmaras',
'Nevsehir',
'Ordu',
'Samsun',
'Sinop',
'Trabzon',
'sanliurfa',
'Van',
'Zonguldak',
'Kirikkale',
'sirnak',
'Ardahan',
'Yalova',
'Duzce',
'Chaguanas',
'Diego Martin',
'Port of Spain',
'Siparia',
'Tunapuna-Piarco',
'Chiayi',
'Hsinchu',
'Nantou',
'Taitung',
'Arusha',
'Kagera',
'Kilimanjaro',
'Kusini Unguja',
'Mara',
'Mjini Magharibi',
'Pwani',
'Ruvuma',
'Singida',
'Tanga',
'Navassa Island',
'Baker Island',
'Jarvis Island',
'Palmyra Atoll',
'Artigas',
'Cerro Largo',
'Durazno',
'Flores',
'Rio Negro',
'Rivera',
'San Jose',
'Andijon',
'Farg''ona',
'Namangan',
'Samarqand',
'Surxondaryo',
'Xorazm',
'Ha Giang',
'Son La',
'Tuyen Quang',
'Ninh Binh',
'Thanh Hoa',
'Ha Tinh',
'Quang Nam',
'Quang Ngai',
'Binh Dinh',
'Lam Dong',
'Tay Ninh',
'Binh Thuan',
'Dong Thap',
'Kien Giang',
'Ben Tre',
'Bac Giang',
'Binh Duong',
'Ca Mau',
'Nam Dinh',
'Vinh Phuc',
'Malampa',
'A''ana',
'Atua',
'Gaga''emauga',
'Va''a-o-Fonoti',
'Abyan',
'Amran',
'HaDramawt',
'Al Hudaydah',
'Al Jawf',
'Al MaHwit',
'Shabwah',
'Central',
'North-Western',
'Bulawayo',
'Mashonaland Central',
'Matabeleland South',
'Mashonaland West',
'Aisne',
'Alpes-Maritimes',
'Ardennes',
'Aube',
'Cantal',
'Charente-Maritime',
'Corrèze',
'Dordogne',
'Drôme',
'Eure-et-Loir',
'Gard',
'Gers',
'Ille-et-Vilaine',
'Loir-et-Cher',
'Haute-Loire',
'Loiret',
'Maine-et-Loire',
'Haute-Marne',
'Meuse',
'Nord',
'Orne',
'Puy-de-Dôme',
'Bas-Rhin',
'Rhône',
'Saône-et-Loire',
'Seine-Maritime',
'Deux-Sèvres',
'Tarn',
'Vendée',
'Haute-Vienne',
'Essonne',
'Val-de-Marne',
'Centre-Val de Loire',
'Nouvelle-Aquitaine',
'Wallis-et-Futuna ',
'Haut-Ogooué',
'Ogooué-Ivindo',
'Ogooué-Maritime',
'Barking and Dagenham',
'Barnsley',
'Ceredigion',
'Denbighshire ',
'Fermanagh and Omagh',
'Halton',
'Knowsley',
'Middlesbrough',
'Merthyr Tydfil',
'North Somerset',
'Oldham',
'Portsmouth',
'Sefton',
'Southend-on-Sea',
'Swansea',
'Telford and Wrekin',
'Trafford',
'Waltham Forest',
'East Ayrshire',
'East Renfrewshire',
'North East Lincolnshire',
'South Ayrshire',
'Commonwealth of Independent States',
'Iberian Region',
'Tiger Region',
'Pazardzhik',
'Armagh, Banbridge and Craigavon',
'Bath and North East Somerset',
'Bournemouth',
'Bracknell Forest',
'Croydon',
'Darlington',
'Derry and Strabane',
'Ealing',
'Hackney',
'Highland',
'Haringey',
'Kirklees',
'Leicester',
'Manchester',
'Newry, Mourne and Down',
'Pembrokeshire',
'Rochdale',
'Reading',
'Slough',
'Sunderland',
'Vale of Glamorgan, The',
'Walsall',
'Warrington',
'Mazeikiai',
'Daugavpils novads',
'Luqa',
'Pieta',
'Nelson    ',
'Port Louis',
'Saint Joseph',
'Zlin',
'Saint George Basseterre',
'Balvu novads',
'Fontana',
'Baie Sainte Anne',
'Iasi',
'Najran',
'Panamá',
'Cheshire East',
'Southampton',
'Guangxi Zhuang',
'Alagoas',
'Rondonia',
'Qinghai Province',
'Co. Leitrim',
'Co. Wicklow',
'Ishikawa',
'Shiga',
'North Hwanghae Province',
'Belgorodskaya obl.',
'Hakassiya',
'Kemerovskaya obl.',
'Mary-El',
'Rostovskaya obl.',
'Tomskaya obl.',
'Chungcheongbuk-do',
'Chernivetska obl.',
'Odesska obl.',
'Aberdeenshire',
'County Down',
'Gloucestershire',
'Leicestershire',
'Surrey',
'Nottinghamshire',
'La Rioja',
'Tucuman',
'Distrito Federal',
'Tachira',
'Libertador General Bernardo O''Higgins',
'Arunachal Pradesh',
'Goa',
'Maharashtra',
'Rajasthan',
'Baja California North',
'Nuevo Leon',
'Gorontalo',
'Lampung',
'Sulawesi Tenggara',
'Teramo',
'Avellino',
'Ferrara',
'Labuan',
'Pahang',
'Palau Pinang',
'Selangor',
'Amazonas',
'Arequipa',
'Callao',
'Huanuco',
'La Libertad',
'Pasco',
'San Martin',
'Ucayali',
'Ravenna',
'Pordenone',
'Frosinone',
'Rome',
'Imperia',
'Cremona',
'Mantova',
'Varese',
'Macerata',
'Isernia',
'Biella',
'Turin',
'Bari',
'Nuoro',
'Agrigento',
'Enna',
'Palermo',
'Siracusa',
'Arezzo',
'Grosseto',
'Pisa',
'Prato',
'Bolzano',
'Perugia',
'Aosta',
'Padova',
'Verona',
'Drenthe',
'Friesland',
'Noord-Brabant',
'Overijssel',
'Salzburg',
'Vorarlberg',
'Pirkanmaa',
'Uusimaa',
'Aquitaine',
'Burgundy',
'Champagne-Ardenne',
'Franche Comté',
'Guadeloupe',
'Limousin',
'Martinique',
'Pays de la Loire',
'Réunion',
'Baden-Württemberg',
'Brandenburg',
'Mecklenburg-Western Pomerania',
'Rhineland-Palatinate',
'Thuringia',
'Finnmark',
'Hordaland',
'Nordland',
'Oslo',
'Telemark',
'Kronoberg County',
'Bern',
'St. Gallen',
'Limburg',
'Kyoto',
'Malyj Vysotskij Isl',
'Ayrshire',
'Caithness',
'Clwyd',
'County Tyrone',
'Dunbartonshire',
'Inverness-shire',
'Isle of Barra',
'Isle of Jura',
'Isle of Mull',
'Isle of Rhum',
'Mid Glamorgan',
'Morayshire',
'Peebleshire',
'Powys',
'Federated States Of Micronesia',
'Antartica e Islas del Atlantic',
'Castile and León',
'Basque Country',
'Upper Austria',
'Greenland',
'The Faroe Islands',
'Åland',
'Central Ostrobothnia',
'Finland Proper',
'Lapland',
'Northern Ostrobothnia',
'US Guam',
'Uzbekistan',
'Liechtenstein',
'Thailand',
'Bhutan',
'Saudi Arabia',
'Puerto Rico',
'Jamaica',
'Reunion',
'Montserrat',
'Mali',
'Jordan',
'Guernsey',
'Mozambique',
'Palestine, State of',
'Tanzania, the United Republic of',
'French Guiana',
'Taichung',
'Sejong',
'Saint George',
'Puntarenas',
'Ash Shamaliyah',
'Midtjylland',
'La Altagracia',
'Jonava',
'H_efa',
'Grand Anse Mahe',
'Distrito Nacional',
'Chuquisaca',
'Brno-mesto',
'Baghdad',
'Al A?madi',
'Washington',
'Gravatai',
'Douala',
'Dusseldorf',
'Seville',
'Glasgow',
'Diourbel',
'Bari',
'Sool',
'Principe',
'Dar''a',
'Tartus',
'Wadday',
'Chanthaburi',
'Chaiyaphum',
'Nakhon Phanom',
'Uthai Thani',
'Phetchaburi',
'Trang',
'Aileu',
'Oe-Cusse Ambeno',
'Zaghouan',
'Monastir',
'Adiyaman',
'Bitlis',
'Elazig',
'Kastamonu',
'Mugla',
'Tekirdag',
'Bayburt',
'Kilis',
'Point Fortin',
'Keelung',
'Kaskazini Unguja',
'Mtwara',
'Johnston Atoll',
'Puerto Rico',
'Maldonado',
'Tacuarembo',
'Qashqadaryo',
'Lai Chau',
'Quang Ninh',
'Quang Tri',
'Dak Lak',
'Ba Ria - Vung Tau',
'Soc Trang',
'Ha Nam',
'Tafea',
'Palauli',
'AD Dali‘',
'Marib',
'Luapula',
'Midlands',
'Alpes-de-Haute-Provence',
'Aveyron',
'Côtes-d''Armor',
'Corse-du-Sud',
'Indre-et-Loire',
'Lot-et-Garonne',
'Moselle',
'Hautes-Pyrénées',
'Savoie',
'Var',
'Yonne',
'Bourgogne-Franche-Comté',
'Normandie',
'Ngounié',
'Argyll and Bute',
'Blackpool',
'East Dunbartonshire',
'Hartlepool',
'Monmouthshire',
'North Tyneside',
'Rotherham',
'Stirling',
'Torbay',
'Wandsworth',
'Moray',
'Gauteng',
'MENA',
'Vratsa',
'Bridgend',
'Bromley',
'Doncaster',
'East Riding of Yorkshire',
'Hounslow',
'Lisburn and Castlereagh',
'Newcastle upon Tyne',
'Peterborough',
'St. Helens',
'South Tyneside',
'Windsor and Maidenhead',
'Jurmala',
'Mgarr',
'Bragança',
'Ceske Budejovice',
'Panevezio miestas',
'Souss-Massa',
'Central',
'San Vicente',
'Mayenne',
'San José',
'Antioquia',
'Brighton and Hove',
'Grenadines',
'Anhui',
'Mato Grosso',
'Heilongjiang Province',
'Co. Cork',
'Co. Offaly',
'Fukushima',
'Miyagi',
'Wakayama',
'Aginsky Buryatsky AO',
'Chukotsky AO',
'Kaliningradskaya obl.',
'Krasnodarskiy kray',
'Orenburgskaya obl.',
'Severnaya Osetiya',
'Ust-Ordynsky Buryat. AO',
'Jeju-do',
'Khmelnytska obl.',
'Vinnytska obl.',
'Cheshire',
'Devon',
'Hertfordshire',
'Northamptonshire',
'Worcestershire',
'Corrientes',
'San Luis',
'Barinas',
'Miranda',
'Zulia',
'Tarapaca',
'Chhattisgarh',
'Karnataka',
'Nagaland',
'Uttaranchal',
'Colima',
'Zacatecas',
'Kalimantan Barat',
'Nusa Tenggara Timur',
'Yogyakarta',
'Cosenza',
'Naples',
'Johor',
'Loreto',
'Bergamo',
'Lecce',
'Lucca',
'Treviso',
'Zeeland',
'Basse-Normandie',
'Ile-de-France',
'Poitou-Charentes',
'Hamburg',
'Aust-Agder',
'Møre og Romsdal',
'Rogaland',
'Western Cape',
'Västernorrland County',
'Neuchâtel',
'Antwerp',
'Ogliastra',
'Jersey',
'Lothian',
'Asturias',
'Galicia',
'Strathclyde',
'Mauritania',
'Congo (the)',
'Yemen',
'Burundi',
'Eritrea',
'Liberia',
'Djibouti',
'Cuba',
'Brunei Darussalam',
'Solomon Islands (the)',
'Russian Federation (the)',
'Turkmenistan',
'Lao, People''s Democratic Republic (the)',
'Israel',
'Saint Vincent and the Grenadines',
'Samoa',
'Egypt',
'New Caledonia',
'Tokelau',
'Central African Republic (the)',
'Niger (the)',
'Belarus',
'Viet Nam',
'Sri Lanka',
'Saint Kitts and Nevis',
'Holy See (the) [Vatican City State]',
'Iceland',
'Saint Helena, Ascension and Tristan da Cunha',
'Guinea-Bissau',
'Bosnia and Herzegovina',
'Bahrain',
'Singapore',
'Qatar',
'Eswatini',
'Colombia',
'Namibia',
'Brazil',
'Gibraltar',
'Serbia and Montenegro (old)',
'Burkina Faso',
'Scotland',
'Algeria',
'Grenada',
'Malawi',
'Monaco',
'Iraq',
'Congo (The Democratic Republic of the)',
'Cameroon',
'Cook Islands (the)',
'Botswana',
'Turks and Caicos Islands (the)',
'Australia',
'Antarctica',
'Syrian Arab Republic (the)',
'Guatemala',
'Angola',
'Tajikistan',
'Bermuda',
'Kyrgyzstan',
'Kazakhstan',
'Serbia',
'Indonesia',
'Bahamas(the)',
'Guam',
'Rwanda',
'Norfolk Island',
'Paraguay',
'Sierra Leone',
'Dominica',
'Tonga',
'Panama',
'Saint Barthelemy',
'Taiwan (Province of China)',
'Gabon',
'Falkland Islands (the) [Malvinas]',
'Georgia',
'Northern Mariana Islands (the)',
'Morocco',
'Kenya',
'Puerto Rico',
'Moldova (the Republic of)',
'Madagascar',
'Lesotho',
'French Southern Territories (the)',
'Marshall Islands (the)',
'Christmas Island',
'Guyana',
'Pakistan',
'China',
'Netherlands Antilles (old)',
'Micronesia (the Federated States of)',
'Saint Lucia',
'Nauru',
'Somalia',
'Aruba',
'Sao Tome and Principe',
'Venezuela, Bolivian Republic of',
'Argentina',
'Anguilla',
'South Africa',
'Sudan (the)',
'Aland Islands',
'Bouvet Island',
'India',
'Cayman Islands (the)',
'Heard and McDonald Islands',
'San Marino',
'Niue',
'Cocos (Keeling) Islands (the)',
'Martinique',
'Maldives',
'Ghana',
'Uganda',
'Togo',
'Norway',
'Republic of North Macedonia',
'Andorra',
'Ethiopia',
'Iran (the Islamic Republic of)',
'Antarctica',
'Pitcairn',
'Antigua and Barbuda',
'European Union',
'Macao',
'Chile',
'Armenia',
'Mayotte',
'Mexico',
'Switzerland',
'Haiti',
'Faroe Islands (the)',
'Nicaragua',
'Korea (the Republic of)',
'Channel Islands (old)',
'Virgin Islands (British)',
'Gambia (The)',
'Afghanistan',
'Malaysia',
'Lebanon',
'Benin',
'Belize',
'Guinea',
'El Salvador',
'Mauritius',
'Ukraine',
'Chad',
'United States (the)',
'Eurozone',
'Zambia',
'Virgin Islands (U.S.)',
'North America',
'Greenland',
'Albania',
'Kuwait',
'Bangladesh',
'Nepal',
'French Polynesia',
'Mongolia',
'Palau',
'Trinidad and Tobago',
'Svalbard and Jan Mayen',
'Barbados',
'Tunisia',
'the State of Libya',
'Cote d Ivoire',
'United Arab Emirates (the)',
'Guadeloupe',
'Fiji',
'Uruguay',
'Tuvalu',
'Costa Rica',
'Zimbabwe',
'Dominican Republic (the)',
'Suriname',
'Ecuador',
'Wallis and Futuna',
'Korea (the Democratic Peoples Republic of)',
'Peru',
'Western Sahara',
'Bolivia, Plurinational State of',
'Philippines (the)',
'Turkey',
'Kiribati',
'Saint Pierre and Miquelon',
'Cambodia',
'Seychelles',
'American Samoa (old)',
'Honduras',
'New Zealand',
'Oman',
'Senegal',
'Vanuatu',
'Myanmar',
'Hong Kong',
'Papua New Guinea',
'Northern Ireland',
'South Georgia and the South Sandwich Islands',
'European Union',
'Sør-Trøndelag',
'Nord-Trøndelag',
'Gauteng',
'KwaZulu-Natal',
'MOSCOW',
'NAYARIT',
'PANAMA',
'VICTORIA',
'QUINDIO',
'TENNESSE',
'MICHIGAN',
'Coahuila',
'MONTANA',
'GEORGIA',
'HAWAII',
'WYOMING',
'Distrito',
'TIANJIN',
'KENT',
'NORTH DA',
'Sinaloa',
'Aquitain',
'OTAGO',
'LUXB',
'SAPA',
'RDJA',
'AQ',
'ANHUI',
'VDCA',
'Maharash',
'HUBEI',
'DESH',
'OTGO',
'ESEX',
'ALASKA',
'OHIO',
'CALIFORN',
'UTAH',
'Zacateca',
'City of',
'HIDALGO',
'MADR',
'NEW YORK',
'NEVADA',
'IDAHO',
'SOUTH CA',
'MISSOURI',
'MISSISSI',
'LOUISIAN',
'Dublin',
'Mexico',
'Nuevo Le',
'ZC',
'DISTRICT',
'TEXAS',
'KENTUCKY',
'ALABAMA',
'MARITIME',
'DF',
'RMTP',
'MASSACHU',
'VERMONT',
'MAINE',
'ARKANSAS',
'OKLAHOMA',
'NEBRASKA',
'Moscow',
'Queretar',
'WESTERN',
'CAMPECHE',
'NO',
'PENNSYLV',
'RHODE IS',
'OREGON',
'ILLINOIS',
'ARIZONA',
'COLORADO',
'DELAWARE',
'MEXICO',
'VERACRUZ',
'GAUTENG',
'GUERRERO',
'KNET',
'GELA',
'GUJARAT',
'MH',
'DUBLIN',
'PARANA',
'LIMBURG',
'SINALOA',
'MILANO',
'GOIAS',
'JKRY',
'MINNESOT',
'WEST VIR',
'GUAM',
'VICENZA',
'DSCP',
'CYLO',
'ZUHO',
'AN',
'GUML',
'NRCA',
'Jalisco',
'BEJN',
'BS',
'NOHO',
'PRLO',
'PRNA',
'NEW JERS',
'FLORIDA',
'PUERTO R',
'NEW HAMP',
'KANSAS',
'VIRGIN I',
'Campeche',
'NO. MARI',
'Baja Cal',
'MADRID',
'SONORA',
'PANA',
'WISCONSI',
'CONNECTI',
'INDIANA',
'IOWA',
'NEW MEXI',
'Vicenza',
'MEXI',
'Noord-Ho',
'NEW SOUT',
'Antioqui',
'ESSEX',
'JALISCO',
'PUEBLA',
'CMDN',
'BEIJING',
'OAXACA',
'ZUG',
'ONTARIO',
'SHANGHAI',
'CAMDEN',
'DURANGO',
'SHNG',
'QA',
'AHUI',
'MOSC',
'WASHINGT',
'SOUTH DA',
'CR',
'LMBG',
'VNZA',
'NORTH CA' 
];
BEGIN
    FOR i IN 1..array_length(name_list, 1) LOOP
        INSERT INTO ft_t_idmv (
            intrnl_dmn_val_id,
            fld_data_cl_id,
            fld_id,
            appl_id,
            last_chg_tms,
            last_chg_usr_id,
            mod_rst_ind,
            intrnl_dmn_val_nme,
            intrnl_dmn_val_txt,
            intrnl_dmn_desc,
            tbl_id,
            col_nme,
            ds_id,
            qual_fld_id,
            qual_val_txt,
            dmn_set_id,
            meta_src_id,
            data_stat_typ,
            org_id,
            dmn_val_purp_typ,
            data_src_id
        )
         (select
            new_oid(),
            null,
            '00002710',
            null,
            '2017-10-21 08:55:59.000',
            'MHI:CSTM:XXXXX',
            'N',
            name_list[i],
            name_list[i],
            name_list[i],
            null, null, null, null, null, null, null,
            'ACTIVE',
            null,
            null,
            'MHI'
        from dual where not exists(select 1 from ft_t_idmv where fld_id = '00002710' and intrnl_dmn_val_txt = name_list[i]));
    END LOOP;
END $$;