update ft_t_xmgs 
set last_chg_tms=now(), last_chg_usr_id='MZHO:CSTM', msg_set_blob='<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MSGSET SYSTEM "msgtype.dtd">
<MSGSET SET="BASEL3STREETREF">
	<SEGMENT TYPE="Initial">
		<RULE ORDER_TYP="B" RULE_NME="CGSCRealignALIDAfterMerge">
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCIssuerDerivation">
			<PARAM>INITIAL</PARAM>
			<PARAM>CUSIP-3,CINS-3</PARAM>
			<PARAM>CUSIP,CINS</PARAM>
			<PARAM>MarkitREDEntity,SPGISFEntityIdentifiers,MoodysRDS_Organization,SP_XF_EntityRatings,SP_XF_SecurityRatings,MoodysRDS_Instrument</PARAM>
			<PARAM>ISIDPLUS,CRSSWALK,MOODYS_RDS,SNPXF_RT</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCModelForcedReevaluation">
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCRatioNormalization">
			<PARAM>MT564</PARAM>
			<PARAM>IssueActionParticipant-BASE_FOR_RATIO=EV_BAS_PRT_CAMT,ORIG_BASE_FOR_RATIO=ORIG_EV_BAS_PRT_CAMT;DERIVE_FROM_RATIO=EV_PART_CAMT-10,ORIG_DERIVE_FROM_RATIO=ORIG_EV_PART_CAMT</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCInvokeJavaRule">
			<PARAM>CJavaMIZNonUniqueIdentifier</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCInvokeJavaRule">
			<PARAM>CJavaMHIBasel3IssuerRatingDerivation</PARAM>
			<PARAM>EBA,PRA</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCInvokeJavaRule">
			<PARAM>CJavaMHIBasel3AssetRatingDerivationWVR</PARAM>
			<PARAM>EBA,PRA</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCInvokeJavaRule">
			<PARAM>CJavaMHIBasel3AssetRatingDerivationWoVR</PARAM>
			<PARAM>EBA,PRA</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTIUniqueCheckAndIDLookup">
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrIssueActionID">
			<PARAM>NULLVALUEMATCH=Y</PARAM>
			<PARAM>PROPRIETARY_IDENTIFIERS=BB-CRPACTID=NM;FIDELITY ISO15022-CAFIDEL=NM;IDCISO-CRPACTID=NM;REUTERS-DVMKEVID,CRPACTID,CPCGMKID,RTCPACID=NM;TELEKURS-CRPACTID=NM;TRDSSISO-CRPACTID=NM</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTIModelDefault">
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCCheckPrimaryMktIdentifier">
			<PARAM>TELEKURS,BB,REUTERS</PARAM>
			<PARAM>INITIAL</PARAM>
			<PARAM>EQSHR,OPTIONS,COMMON,CVTPFD,FUND,FUTURES,INDEXOP,PFD,RECEIPTS,RIGHTS,UNIT,UNITTRST,WARRANTS,HYBRID,LTDPART,REALESTA</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCEquateListing">
			<PARAM>EQSHR,OPTIONS,COMMON,CVTPFD,FUND,FUTURES,INDEXOP,PFD,RECEIPTS,RIGHTS,UNIT,UNITTRST,WARRANTS,HYBRID,LTDPART,REALESTA,ETF,ETN,ETP</PARAM>
			<PARAM>BBCMPSEC,BBUNIQUE,BBCPTICK,LISTSYMB,PREFSYMB,TELEKURS,TICKER,RIC,TRDGSYMB,CPBBUNIQ,CPTICKER,EQFUNDTK,CPGLOBAL,BBGLOBAL,BBTRDGSYMB,SECREF,CCASS</PARAM>
			<PARAM>Y</PARAM>
			<PARAM>SEDOL,CPSEDOL</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="Issue">
		<RULE ORDER_TYP="B" RULE_NME="CFTIValIssueOverride">
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCPricingFXRT">
			<PARAM>ReutersEquityPricing,TKPRD</PARAM>
		</RULE>
		<RULE ORDER_TYP="F" RULE_NME="CFTIInternalIdentifierCreator">
			<PARAM>MIZUHO</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCEndDateISID">
		</RULE>
		<!--RULE ORDER_TYP="A" RULE_NME="CGSCHandleMultiGuarantorDataForSecurity">
		<PARAM>BB</PARAM>
		</RULE-->
	</SEGMENT>
	<SEGMENT TYPE="IssueIdentifier">
		<RULE ORDER_TYP="A" RULE_NME="CGSCSetGlobalIdentifierIndicator">
		</RULE>
		<RULE ORDER_TYP="A" RULE_NME="CFTICheckPrimaryIDToBeUpdated">
		</RULE>
		<RULE ORDER_TYP="F" RULE_NME="CGSCCreateUnderlyingLink">
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IssueActionDeclaration">
		<RULE ORDER_TYP="A" RULE_NME="CFTILoadLogicalKey">
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>IADC_IMGID_ISSU_ISSR_ISCTP</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstructGeoUnit">
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrMKTOID">
			<PARAM>N</PARAM>
			<PARAM>N</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCMergeEntity">
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCSetMatchKeyForMergeMsg">
			<PARAM>IssueActionStatistic:IASS_MATCH_1,IssueActionPrtComment:GNCM_MATCH</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="EmployeeCustomerRole">
	</SEGMENT>
	<SEGMENT TYPE="ISSUIssueActionDeclaration">
		<RULE ORDER_TYP="A" RULE_NME="CFTILoadLogicalKey">
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>IADC_IMGID_ISSU_ISSR_ISCTP</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstructGeoUnit">
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrMKTOID">
			<PARAM>N</PARAM>
			<PARAM>N</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IssueActionParticipant">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrFieldValue">
			<PARAM>ISSACT_PROC_ID</PARAM>
			<PARAM>PRNT_ISSACT_PROC_ID</PARAM>
			<PARAM>STRING</PARAM>
			<PARAM>W</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrInstrIDForIAIP">
			<PARAM>DENOM_CURR_CDE</PARAM>
			<PARAM>ISID</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IssuerClassification">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstructClassification">
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IssuerGeoUnit">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstructGeoUnit">
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IssuerRating">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstructIssueRating"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>IRRT_MATCH_4</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IssueDescription">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrMKTOID">
			<PARAM>N</PARAM>
			<PARAM>N</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IssueRating">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstructIssueRating"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>ISRT_MATCH_5</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IssueStatistic">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrMKTOID">
			<PARAM>Y</PARAM>
			<PARAM>N</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IssueCrossReference">
	</SEGMENT>
	<SEGMENT TYPE="MarketIssueCharacteristics">
		<RULE ORDER_TYP="B" RULE_NME="CGSCCheckPrimaryMktIdentifier">
			<PARAM>TELEKURS,BB,REUTERS</PARAM>
			<PARAM>MARKET</PARAM>
			<PARAM>EQSHR,OPTIONS,COMMON,CVTPFD,FUND,FUTURES,INDEXOP,PFD,RECEIPTS,RIGHTS,UNIT,UNITTRST,WARRANTS,HYBRID,LTDPART,REALESTA</PARAM>
		</RULE>
		<RULE ORDER_TYP="A" RULE_NME="CGSCCreateMIXR">
			<PARAM/>
			<PARAM>WARNING</PARAM>
		</RULE>
		<RULE ORDER_TYP="A" RULE_NME="CGSCListingUniqueIdentifier">
			<PARAM>Rule to Add MHI Listing ID</PARAM>
			<PARAM>MHILIST</PARAM>
			<PARAM>MHI_LISTING_ID</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="CompositeMarketIssueCharacteristics">
		<RULE ORDER_TYP="B" RULE_NME="CGSCCheckPrimaryMktIdentifier">
			<PARAM>TELEKURS,BB,REUTERS</PARAM>
			<PARAM>MARKET</PARAM>
			<PARAM>EQSHR,OPTIONS,COMMON,CVTPFD,FUND,FUTURES,INDEXOP,PFD,RECEIPTS,RIGHTS,UNIT,UNITTRST,WARRANTS,HYBRID,LTDPART,REALESTA</PARAM>
		</RULE>
		<RULE ORDER_TYP="A" RULE_NME="CGSCCreateMIXR">
			<PARAM/>
			<PARAM>WARNING</PARAM>
		</RULE>
		<RULE ORDER_TYP="A" RULE_NME="CGSCListingUniqueIdentifier">
			<PARAM>Rule to Add MHI Listing ID</PARAM>
			<PARAM>MHILIST</PARAM>
			<PARAM>MHI_LISTING_ID</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="RelatedIssueDefinition">
	</SEGMENT>
	<SEGMENT TYPE="RelatedIssue">
		<RULE ORDER_TYP="F" RULE_NME="CGSCUpdateMissingUnderlyingInfo">
			<PARAM>Y</PARAM>
			<PARAM>ENABLE_DATA_CORRECTION=UNDERLYG:UNDLYING,CERTDPST:UNDLYING</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="UnderwriterCharacteristics">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrMKTOID">
			<PARAM>N</PARAM>
			<PARAM>N</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrOFFERNUM">
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="FinsRoleIssueParticipant">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstFINS">
			<PARAM>N</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTIValInFuture">
			<PARAM>.FIRST_TRD_TNS</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="DepositoryOptions">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstFINS">
			<PARAM>N</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IssueDocument">
	</SEGMENT>
	<SEGMENT TYPE="IncomeEventDefinition">
	</SEGMENT>
	<SEGMENT TYPE="IncomeEventDefReplace">
		<RULE ORDER_TYP="B" RULE_NME="CFTIReplaceIncomeEventDef">
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IncomePaymentDefinition">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrCurrency">
			<PARAM>.PAY_CURR_CDE</PARAM>
			<PARAM>.EV_INSTR_ID</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IncomePaymentDefReplace">
		<RULE ORDER_TYP="B" RULE_NME="CGSCIncomePaymentDefReplace">
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="StandardIndexStatistics">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrSourceFINS">
			<PARAM>N</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="PrincipalPaymentDefinition">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrCurrency">
			<PARAM>.PAY_CURR_CDE</PARAM>
			<PARAM>.EV_INSTR_ID</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="PrincipalPaymentDefReplace">
		<RULE ORDER_TYP="B" RULE_NME="CGSCPrincipalPaymentDefReplace">
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="PrincipalEventDefReplace">
		<RULE ORDER_TYP="B" RULE_NME="CFTIReplacePrincipalEventDef">
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="Final">
		<RULE ORDER_TYP="B" RULE_NME="CFTIValIssueIdentifiers">
			<PARAM>INTERNAL_IDENTIFIERS=INTERNAL,COMMON</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CGSCInvokeJavaRule">
			<PARAM>CJavaMHIUpdatedTMS</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="FinancialInstitutionStatistic">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrSTDFOID">
			<PARAM>Y</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="FinancialInstitutionIdentifier">
	</SEGMENT>
	<SEGMENT TYPE="FinancialMarket">
	</SEGMENT>
	<SEGMENT TYPE="CompanyStatistics">
	</SEGMENT>
	<SEGMENT TYPE="IssueGeoUnit">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstructGeoUnit">
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IssueGeoStatistics">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstructGeoUnit">
			<PARAM>N</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IssueRegulatoryCharacteristics">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstructGeoUnit">
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="GeoUnitCalendarParticipant">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstructGeoUnit">
			<PARAM>E</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="MarketIssueStatistic">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstrSourceFINS">
			<PARAM>N</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="MarketIndexDefinition">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstructGeoUnit">
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="PrincipalEventDefinition">
	</SEGMENT>
	<SEGMENT TYPE="AddressType">
		<RULE ORDER_TYP="B" RULE_NME="CFTIADTPProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="MailingAddress">
		<RULE ORDER_TYP="B" RULE_NME="CFTIAddressProcessing">
			<PARAM>MADR</PARAM>
			<PARAM>AddressType</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="ElectronicAddress">
		<RULE ORDER_TYP="B" RULE_NME="CFTIAddressProcessing">
			<PARAM>EADR</PARAM>
			<PARAM>AddressType</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="CentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_MATCH_FINS</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="FINSCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_MATCH_FINS</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="ACCTCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_MATCH_ACCT</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="CUSTCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_MATCH_CUST</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="ENTRCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_ENTR_MATCH</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="AUSRCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="EMPLCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_MATCH_9</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="CNTCCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_CNTC_MATCH</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="ISSRCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_MATCH_5</PARAM>
			<PARAM>L</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="DLERCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_MATCH_15</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="DLBRCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_MATCH_16</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="DREPCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_MATCH_17</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="FPROCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_MATCH_18</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="FINRCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_MATCH_6</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="ISSUCentralCrossReference">
		<RULE ORDER_TYP="B" RULE_NME="CFTIGetEntityDetailsForCCRF"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>CCRF_MATCH_13</PARAM>
		</RULE>
		<RULE ORDER_TYP="B" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="A" RULE_NME="CFTICCRFProcessing"/>
		<RULE ORDER_TYP="F" RULE_NME="CFTICCRFProcessing"/>
	</SEGMENT>
	<SEGMENT TYPE="FinancialInstitutionRole">
		<RULE ORDER_TYP="A" RULE_NME="CFTIRemoveIfUpdate">
			<PARAM>CROSS_REF_ID</PARAM>
			<PARAM>STRING</PARAM>
			<PARAM>N</PARAM>
		</RULE>
		<RULE ORDER_TYP="A" RULE_NME="CFTIRemoveIfUpdate">
			<PARAM>START_TMS</PARAM>
			<PARAM>TMS</PARAM>
			<PARAM>N</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="FinancialInstitutionRating">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstructIssueRating"/>
		<RULE ORDER_TYP="B" RULE_NME="CFTISetMatchKey">
			<PARAM>FIRT_MATCH_5</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="FinancialInstitutionGroupPrt">
		<RULE ORDER_TYP="B" RULE_NME="CFTIConstFINS">
			<PARAM>N</PARAM>
		</RULE>
		<RULE ORDER_TYP="A" RULE_NME="CFTISeqNumGenerator">
			<PARAM>PRT_NUM</PARAM>
			<PARAM>LNUM</PARAM>
			<PARAM>E</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="FINSFinancialInstitutionGroupPrt">
		<RULE ORDER_TYP="A" RULE_NME="CFTISeqNumGenerator">
			<PARAM>PRT_NUM</PARAM>
			<PARAM>LNUM</PARAM>
			<PARAM>E</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="ApplicationUserGroupParticipant">
		<RULE ORDER_TYP="A" RULE_NME="CFTISeqNumGenerator">
			<PARAM>PRT_NUM</PARAM>
			<PARAM>LNUM</PARAM>
			<PARAM>E</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="AUSRApplicationUserGroupParticipant">
		<RULE ORDER_TYP="A" RULE_NME="CFTISeqNumGenerator">
			<PARAM>PRT_NUM</PARAM>
			<PARAM>LNUM</PARAM>
			<PARAM>E</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="FeeTypeGroupParticipant">
		<RULE ORDER_TYP="A" RULE_NME="CFTISeqNumGenerator">
			<PARAM>PRT_NUM</PARAM>
			<PARAM>LNUM</PARAM>
			<PARAM>E</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="FTGRFeeTypeGroupParticipant">
		<RULE ORDER_TYP="A" RULE_NME="CFTISeqNumGenerator">
			<PARAM>PRT_NUM</PARAM>
			<PARAM>LNUM</PARAM>
			<PARAM>E</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="IssuerGroupParticipant">
		<RULE ORDER_TYP="A" RULE_NME="CFTISeqNumGenerator">
			<PARAM>PRT_NUM</PARAM>
			<PARAM>LNUM</PARAM>
			<PARAM>E</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="MarketIndexGroupParticipant">
		<RULE ORDER_TYP="A" RULE_NME="CFTISeqNumGenerator">
			<PARAM>PRT_NUM</PARAM>
			<PARAM>LNUM</PARAM>
			<PARAM>E</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="MRKXMarketIndexGroupParticipant">
		<RULE ORDER_TYP="A" RULE_NME="CFTISeqNumGenerator">
			<PARAM>PRT_NUM</PARAM>
			<PARAM>LNUM</PARAM>
			<PARAM>E</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="ISSRIssuerGroupParticipant">
		<RULE ORDER_TYP="A" RULE_NME="CFTISeqNumGenerator">
			<PARAM>PRT_NUM</PARAM>
			<PARAM>LNUM</PARAM>
			<PARAM>E</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="ElectronicAddressPreference">
		<RULE ORDER_TYP="B" RULE_NME="CFTICopyFieldFromStorage">
			<PARAM>CNTL_CROSS_REF_OID</PARAM>
			<PARAM>CCRF</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="Customer">
	</SEGMENT>
	<SEGMENT TYPE="CustomerIdentifier">
	</SEGMENT>
	<SEGMENT TYPE="FundInvestmentCriteriaDetail">
	</SEGMENT>
	<SEGMENT TYPE="LegalAgreement">
	</SEGMENT>
	<SEGMENT TYPE="ChangeAuditLog">
		<RULE ORDER_TYP="A" RULE_NME="CGSCBulkApproval">
		</RULE>
		<RULE ORDER_TYP="A" RULE_NME="CGSCChangeApproval">
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="ISSUIssueGroupParticipant">
	</SEGMENT>
	<SEGMENT TYPE="Employee">
		<RULE ORDER_TYP="A" RULE_NME="CFTISeqNumGenerator">
			<PARAM>PREF_EMPLOYEE_ID</PARAM>
			<PARAM>STRING</PARAM>
			<PARAM>E</PARAM>
		</RULE>
	</SEGMENT>
	<SEGMENT TYPE="EntityUpdateTimestamp">
		<RULE ORDER_TYP="D" RULE_NME="CGSCInvokeJavaRule">
			<PARAM>CJavaMHIUpdatedTMS</PARAM>
		</RULE>
	</SEGMENT>
</MSGSET>'
where msg_set_nme ='BASEL3STREETREF';