UPDATE FT_T_RTVL
SET RANK_NUM=230 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='RD' AND RTNG_VALUE_OID='(MxBm>mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=250 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='D' AND RTNG_VALUE_OID='(MBC0FmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=250 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='RD' AND RTNG_VALUE_OID='(MBE08mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=3 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='C/D' AND RTNG_VALUE_OID='(MB304mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=4 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='D/E' AND RTNG_VALUE_OID='(MB205mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=1 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='A/B' AND RTNG_VALUE_OID='(MB20FmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=2 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='B/C' AND RTNG_VALUE_OID='(MB20JmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='E' AND RTNG_VALUE_OID='(MB302mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=190 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='CC' AND RTNG_VALUE_OID='(MBJ0JmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=250 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='RD' AND RTNG_VALUE_OID='(MBQ04mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=1 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='F1+/F1+' AND RTNG_VALUE_OID='(MBZ0JmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=2 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='F1/F1' AND RTNG_VALUE_OID='(MBZ0KmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=1 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='F1+/F1+' AND RTNG_VALUE_OID='(MBN0GmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=200 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='C' AND RTNG_VALUE_OID='(MBH08mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='A' AND RTNG_VALUE_OID='(MB(0KmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='P-1' AND RTNG_VALUE_OID='(MB)0KmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=2 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='F1/F1' AND RTNG_VALUE_OID='(MBX07mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=1 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='F1+/F1' AND RTNG_VALUE_OID='(MBc07mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='Ba' AND RTNG_VALUE_OID='(MBB17mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='NP' AND RTNG_VALUE_OID='(MBF1BmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='MIG 2' AND RTNG_VALUE_OID='(MB719mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=1 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='F1+/F1' AND RTNG_VALUE_OID='(MBP0AmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=2 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='F1/F1' AND RTNG_VALUE_OID='(MBT0CmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=1 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='F1+/F1+' AND RTNG_VALUE_OID='(MBa0CmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='Caa' AND RTNG_VALUE_OID='(MB%0CmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='Caa' AND RTNG_VALUE_OID='(MB?0CmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='Aa' AND RTNG_VALUE_OID='(MB51FmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=80 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='RD' AND RTNG_VALUE_OID='(MxXm>mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='Caa' AND RTNG_VALUE_OID='(MB212mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='MIG 1' AND RTNG_VALUE_OID='(MB614mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='SG' AND RTNG_VALUE_OID='(MB~0EmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='E' AND RTNG_VALUE_OID='(MBK0DmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=1 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='F1+/F1' AND RTNG_VALUE_OID='(MBP0DmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=250 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='RD' AND RTNG_VALUE_OID='(MBN0FmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=1 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='F1+/F1+' AND RTNG_VALUE_OID='(MBY0FmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=80 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='RD' AND RTNG_VALUE_OID='(MBc0FmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=80 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='RD' AND RTNG_VALUE_OID='(MBf0FmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='B' AND RTNG_VALUE_OID='(MB013mfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=NULL ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='Baa' AND RTNG_VALUE_OID='(MB01HmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=2 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='F1/F1' AND RTNG_VALUE_OID='(MBT0ImfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=220 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='RD' AND RTNG_VALUE_OID='(MBI0HmfG1';
UPDATE FT_T_RTVL
SET RANK_NUM=1 ,LAST_CHG_TMS=SYSDATE(), last_chg_usr_id = 'MHI:CSTM' WHERE  RTNG_CDE='F1+/F1' AND RTNG_VALUE_OID='(MBg0HmfG1';
