--{$$-STATEMENT-$$} FT_T_CCRF
/* ALTER TABLE FT_T_CCRF ADD COLUMN IF NOT EXISTS LAAN_OID VARCHAR(10); */

--{$$-STATEMENT-$$} FT_T_EQCH
/* ALTER TABLE FT_T_EQCH ADD COLUMN IF NOT EXISTS FULLY_FUNDED_IND
CHAR(1); */

--{$$-STATEMENT-$$} FT_T_FLAR
/* ALTER TABLE FT_T_FLAR ADD COLUMN IF NOT EXISTS BILLS_ANNEX_IND
CHAR(1);
ALTER TABLE FT_T_FLAR ADD COLUMN IF NOT EXISTS ED_ATE_APPLS_IND
CHAR(1);
ALTER TABLE FT_T_FLAR ADD COLUMN IF NOT EXISTS EQUITY_ANNEX_IND
CHAR(1); */
/* ALTER TABLE FT_T_FLAR ADD COLUMN IF NOT EXISTS ESCROW_MIN_RTNG_CDE
VARCHAR(40);
ALTER TABLE FT_T_FLAR ADD COLUMN IF NOT EXISTS ESCROW_MIN_RTNG_SET_OID
VARCHAR(10); */
/* ALTER TABLE FT_T_FLAR ADD COLUMN IF NOT EXISTS GILT_ANNEX_IND
CHAR(1);
ALTER TABLE FT_T_FLAR ADD COLUMN IF NOT EXISTS ITALIAN_ANNEX_IND
CHAR(1);
ALTER TABLE FT_T_FLAR ADD COLUMN IF NOT EXISTS PRNCPL_TRAN_APPLIES_IND
CHAR(1); */

--{$$-STATEMENT-$$} FT_T_LAAN
/* ALTER TABLE FT_T_LAAN ADD COLUMN IF NOT EXISTS ANNEX_INSTRCN_DTE
TIMESTAMP;
ALTER TABLE FT_T_LAAN ADD COLUMN IF NOT EXISTS ANNEX_LOC_TXT
VARCHAR(500);
ALTER TABLE FT_T_LAAN ADD COLUMN IF NOT EXISTS ANNEX_VERSION 
numeric(10, 0);	*/
/* ALTER TABLE FT_T_LAAN ADD COLUMN IF NOT EXISTS COL_DISP_IND
CHAR(1); */
/* ALTER TABLE FT_T_LAAN ADD COLUMN IF NOT EXISTS LEG_AGRMNT_ID
VARCHAR(10);
ALTER TABLE FT_T_LAAN ADD COLUMN IF NOT EXISTS ORG_ID
VARCHAR(4);
 */
--{$$-STATEMENT-$$} FT_T_LAAP
/* ALTER TABLE FT_T_LAAP ADD COLUMN IF NOT EXISTS ANNEX_MODL_TYP
VARCHAR(10);
ALTER TABLE FT_T_LAAP ADD COLUMN IF NOT EXISTS INDEPENDENT_METH_TXT
VARCHAR(20);
ALTER TABLE FT_T_LAAP ADD COLUMN IF NOT EXISTS INDEPENDENT_STAT_TMS
TIMESTAMP; */
/* ALTER TABLE FT_T_LAAP ADD COLUMN IF NOT EXISTS MIN_COLL_RTNG_CDE
VARCHAR(40);
ALTER TABLE FT_T_LAAP ADD COLUMN IF NOT EXISTS MIN_COLL_RTNG_SET_OID
VARCHAR(10);
ALTER TABLE FT_T_LAAP ADD COLUMN IF NOT EXISTS MIN_RTNG_CDE
VARCHAR(40);
ALTER TABLE FT_T_LAAP ADD COLUMN IF NOT EXISTS MIN_RTNG_SET_OID
VARCHAR(10); */

--{$$-STATEMENT-$$} FT_T_LAAT
/* ALTER TABLE FT_T_LAAT ADD COLUMN IF NOT EXISTS ANNEX_MODL_TYP
VARCHAR(10);
ALTER TABLE FT_T_LAAT ADD COLUMN IF NOT EXISTS CALC_CURR
VARCHAR(3);
ALTER TABLE FT_T_LAAT ADD COLUMN IF NOT EXISTS EARLY_TER_CURR
VARCHAR(3);
ALTER TABLE FT_T_LAAT ADD COLUMN IF NOT EXISTS EOD_TER_CURR
VARCHAR(3); */
/* ALTER TABLE FT_T_LAAT ADD COLUMN IF NOT EXISTS EXT_RTNG_CDE
VARCHAR(40); */
/* ALTER TABLE FT_T_LAAT ADD COLUMN IF NOT EXISTS INST_MNEM
VARCHAR(10);
ALTER TABLE FT_T_LAAT ADD COLUMN IF NOT EXISTS INT_ADJ_IND
VARCHAR(20); */
/* ALTER TABLE FT_T_LAAT ADD COLUMN IF NOT EXISTS INT_RTNG_CDE
VARCHAR(40); */
/* ALTER TABLE FT_T_LAAT ADD COLUMN IF NOT EXISTS INT_TSFR_IND
VARCHAR(20); */
/* ALTER TABLE FT_T_LAAT ADD COLUMN IF NOT EXISTS MARGIN_CAMT
numeric(31,5);
ALTER TABLE FT_T_LAAT ADD COLUMN IF NOT EXISTS RL_TYP
numeric(31,5); */
/* ALTER TABLE FT_T_LAAT ADD COLUMN IF NOT EXISTS THSHLD_CURR
VARCHAR(3);
 */
--{$$-STATEMENT-$$} FT_T_LACD
/* ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS COLL_CALL_ACTION_IF_HOL
VARCHAR(40); */
/* ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS COLL_CALL_FQ_DY_TYP
VARCHAR(4);
ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS COLL_CALL_FQ_SP_TYP
VARCHAR(2);
ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS COLL_CALL_NOTFCN_TME
TIMESTAMP; */
/* ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS COLL_CALL_NOTFCN_TMZ
VARCHAR(8); */
/* ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS COLL_RTNG_CDE
VARCHAR(40);
ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS COLL_RTNG_SET_OID
VARCHAR(10); */
/* ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS COLL_SETTLE_DTE_OF_CNT
numeric(8,0);
ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS COLL_VAL_DTE_OF_CNT
numeric(8,0); */
/* ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS HLD_MIN_INT_RTNG_CDE
VARCHAR(40);
ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS HLD_MIN_INT_RTNG_SET_OID
VARCHAR(10);
ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS HLD_MIN_RTNG_CDE
VARCHAR(40);
ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS HLD_MIN_RTNG_SET_OID
VARCHAR(10); */
/* ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS INTRST_CRTE
numeric(18,12); */
/* ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS ISSR_CDE
VARCHAR(20);
ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS MATURITY_RULE_TXT_MAX
VARCHAR(20); */
/* ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS SEC_MIN_INT_RTNG_CDE
VARCHAR(40);
ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS SEC_MIN_INT_RTNG_SET_OID
VARCHAR(10);
ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS SEC_MIN_RTNG_CDE
VARCHAR(40);
ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS SEC_MIN_RTNG_SET_OID
VARCHAR(10); */
/* ALTER TABLE FT_T_LACD ADD COLUMN IF NOT EXISTS TICKER_CDE
VARCHAR(40); */

--{$$-STATEMENT-$$} FT_T_LACV
/* ALTER TABLE FT_T_LACV ADD COLUMN IF NOT EXISTS BRNCH_NME
VARCHAR(40); */
/* ALTER TABLE FT_T_LACV ADD COLUMN IF NOT EXISTS ISS_TYP
VARCHAR(8);
ALTER TABLE FT_T_LACV ADD COLUMN IF NOT EXISTS ORG_ID
VARCHAR(4);
ALTER TABLE FT_T_LACV ADD COLUMN IF NOT EXISTS PRC_SRCE_TYP
VARCHAR(40); */
/* ALTER TABLE FT_T_LACV ADD COLUMN IF NOT EXISTS PROD_ID
VARCHAR(8);
 */
--{$$-STATEMENT-$$} FT_T_LAGR
/* ALTER TABLE FT_T_LAGR ADD COLUMN IF NOT EXISTS AGRMNT_INSTRCN_DTE
TIMESTAMP;
ALTER TABLE FT_T_LAGR ADD COLUMN IF NOT EXISTS AGRMNT_VERSION
numeric(10,0); */
/* ALTER TABLE FT_T_LAGR ADD COLUMN IF NOT EXISTS PRNT_LEG_AGRMNT_ID
VARCHAR(10);
ALTER TABLE FT_T_LAGR ADD COLUMN IF NOT EXISTS PRNT_ORG_ID
VARCHAR(4); */


--{$$-STATEMENT-$$} FT_T_LAID
/* ALTER TABLE FT_T_LAID ADD COLUMN IF NOT EXISTS LEG_AGRMNT_ID
VARCHAR(40);
ALTER TABLE FT_T_LAID ADD COLUMN IF NOT EXISTS ORG_ID
VARCHAR(4); */

--{$$-STATEMENT-$$} FT_T_LAIP
/* ALTER TABLE FT_T_LAIP ADD COLUMN IF NOT EXISTS TRN_PY_NETTING
VARCHAR(40); */

/* --{$$-STATEMENT-$$} FT_T_PRPU
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_BILATERAL
VARCHAR(2);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_BLMBRG_CDE
VARCHAR(100);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_CASH
VARCHAR(100);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_CLEARED
VARCHAR(1);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_CSA_FLAG
VARCHAR(1);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_DVP
VARCHAR(100);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_FUT_AGRMNT
VARCHAR(100);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_HO_APPR_RECD
VARCHAR(100);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_HO_APPR_REQ
VARCHAR(1);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_ISDA_DATE
TIMESTAMP;
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_ISDA_FLAG
VARCHAR(1);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_ISDA_NETTING
VARCHAR(1);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_LIMIT_QUALIFIER
VARCHAR(100);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_LIMIT_RQST
VARCHAR(100);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_REPO_DATE
TIMESTAMP;
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_REPO_NETTING
VARCHAR(1);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_REPO_WRTN_AGRMNT
VARCHAR(1);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_RISK_APPR_RECD
VARCHAR(100);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_RISK_APPR_REQ
VARCHAR(1);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_TENOR
VARCHAR(100);
ALTER TABLE FT_T_PRPU ADD COLUMN IF NOT EXISTS MHI_TRDNG_CDE
VARCHAR(100); */

--{$$-STATEMENT-$$} FT_T_SSIA
/* ALTER TABLE FT_T_SSIA ADD COLUMN IF NOT EXISTS ACCT_ORG_ID
VARCHAR(4); */

/* --{$$-STATEMENT-$$} FT_T_INLM
ALTER TABLE FT_T_INLM ADD COLUMN IF NOT EXISTS MHI_FUT_AGRMNT
VARCHAR(100);
ALTER TABLE FT_T_INLM ADD COLUMN IF NOT EXISTS MHI_LIMIT_QUALIFIER
VARCHAR(100);
ALTER TABLE FT_T_INLM ADD COLUMN IF NOT EXISTS MHI_REPO_NETTING
VARCHAR(1);
ALTER TABLE FT_T_INLM ADD COLUMN IF NOT EXISTS MHI_REPO_WRTN_AGRMNT
VARCHAR(1);
ALTER TABLE FT_T_INLM ADD COLUMN IF NOT EXISTS MHI_SWAP_NETTING
VARCHAR(1); */

-- For EADR, IEDF, LMST (Confirm)
ALTER TABLE	FT_T_EADR ADD COLUMN IF NOT EXISTS FAX_IND VARCHAR(1);
ALTER TABLE	FT_T_EADR ADD COLUMN IF NOT EXISTS VOICE_IND VARCHAR(1);
--ALTER TABLE	FT_T_IEDF ADD COLUMN IF NOT EXISTS FLT_SPRD_CQTY numeric(31,11);			-- Search is in progress with connections.
--ALTER TABLE	FT_T_LMST ADD COLUMN IF NOT EXISTS ORIG_PRIN_CAMT numeric(31,5);			-- OOB Migration will happen into UWST.ORIG_PRIN_CAMT

-- PROVIDED BY DM TEAM (COLUMNS TO BE ADDED IN V10)

ALTER TABLE	FT_T_CCRF	ADD 	LAAN_OID	VARCHAR(10);
ALTER TABLE	FT_T_FLAR	ADD 	BILLS_ANNEX_IND	CHAR(1)	;
ALTER TABLE	FT_T_FLAR	ADD 	ED_ATE_APPLS_IND	CHAR(1)	;
ALTER TABLE	FT_T_FLAR	ADD 	GILT_ANNEX_IND	CHAR(1)	;
ALTER TABLE	FT_T_FLAR	ADD 	EQUITY_ANNEX_IND	CHAR(1)	;
ALTER TABLE	FT_T_FLAR	ADD 	ITALIAN_ANNEX_IND	CHAR(1)	;
ALTER TABLE	FT_T_FLAR	ADD 	PRNCPL_TRAN_APPLIES_IND	CHAR(1)	;
ALTER TABLE	FT_T_LAAP	ADD 	COLL_DISPUTE_IND	CHAR(1)	;
ALTER TABLE	FT_T_LAAP	ADD 	THSHLD_METH_STAT_TMS	VARCHAR(256)	;
ALTER TABLE	FT_T_LAAT	ADD 	THSHLD_CURR_CDE	VARCHAR(3)	;
ALTER TABLE	FT_T_LACD	ADD 	COLL_CALL_FQ_SP_TYP	VARCHAR(2)	;
ALTER TABLE	FT_T_LACD	ADD 	COLL_CALL_FQ_QTY BIGINT;							-- needs to be changed (BIGINT)
ALTER TABLE	FT_T_LACD	ADD 	COLL_CALL_FQ_DY_TYP	VARCHAR(4)	;
--ALTER TABLE	FT_T_LACD	ADD 	COLL_CALL_PRD_FQ_QTY	NUMERIC(10)	;
--ALTER TABLE	FT_T_LACD	ADD 	COLL_CALL_PRD_FQ_DY_TYP	VARCHAR(4)	;
ALTER TABLE	FT_T_LACD	ADD 	COLL_CALL_NOTFCN_TMZ	VARCHAR(8)	;