INSERT INTO FT_T_FCDF
(FLD_DATA_CL_ID, LAST_CHG_TMS, LAST_CHG_USR_ID, ALLOW_MOD_IND, DATA_TYP, FLD_LEN, FLD_SCALE_LEN, MN_LEN, FILL_CHAR, JUST_TYP, CL_NME, CL_DESC, DSPY_DATA_TYP, DSPY_INT_NUM, DSPY_DEC_NUM, INFO_TYP_NME)
VALUES('LIMTQUAL', TIMESTAMP '2014-05-27 13:14:21.000000', 'MHI:CSTM', 'N', 'CHAR    ', 256, 0, 0, ' ', 'L', 'Indicator', 'CHAR(1)', NULL, NULL, NULL, 'INDICATOR');
commit;

INSERT INTO FT_T_FLDF
(FLD_ID, LAST_CHG_TMS, LAST_CHG_USR_ID, FLD_DATA_CL_ID, FLD_TAG_TYP, PRNT_FLD_ID, FLD_DFLT_METH_NME, FLD_EDIT_METH_NME, DDL_NME, FILL_CHAR, JUST_TYP, CTL_TOT_ELIG_IND, FLD_USED_BY_TYP, DMN_TBL_TYP, FLD_DFLT_VAL_TXT, FLD_NME, FLD_DESC, DSPY_DATA_TYP, DSPY_INT_NUM, DSPY_DEC_NUM, DSPY_CAPTION_TXT, MN_VAL_CAMT, MX_VAL_CAMT, FLD_DFLT_CAMT)
SELECT '00074067', TIMESTAMP '2012-06-30 00:00:00.000000', 'GS:MSYS', 'IND', NULL, NULL, NULL, NULL, 'FAX_IND', ' ', 'L', NULL, 'T', NULL, NULL, 'FAX Indicator', 'This field indicates whether a telephone number can be used for FAX communication.
Note: This field is obsolete and is subject to removal in a future release.', 'TEXT', NULL, NULL, 'FAX Indicator', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM FT_T_FLDF WHERE FLD_ID = '00074067');
commit;

INSERT INTO FT_T_FLDF
(FLD_ID, LAST_CHG_TMS, LAST_CHG_USR_ID, FLD_DATA_CL_ID, FLD_TAG_TYP, PRNT_FLD_ID, FLD_DFLT_METH_NME, FLD_EDIT_METH_NME, DDL_NME, FILL_CHAR, JUST_TYP, CTL_TOT_ELIG_IND, FLD_USED_BY_TYP, DMN_TBL_TYP, FLD_DFLT_VAL_TXT, FLD_NME, FLD_DESC, DSPY_DATA_TYP, DSPY_INT_NUM, DSPY_DEC_NUM, DSPY_CAPTION_TXT, MN_VAL_CAMT, MX_VAL_CAMT, FLD_DFLT_CAMT)
SELECT '00074302', TIMESTAMP '2012-06-30 00:00:00.000000', 'GS:MSYS', 'IND', NULL, NULL, NULL, NULL, 'VOICE_IND', ' ', 'L', NULL, 'T', NULL, NULL, 'Voice Indicator', 'This field indicates whether a telephone number can be used for voice communication.
Note: This field is obsolete and is subject to removal in a future release.', 'TEXT', NULL, NULL, 'Voice Indicator', NULL, NULL, NULL
WHERE NOT EXISTS (SELECT 1 FROM FT_T_FLDF WHERE FLD_ID = '00074302');
commit;

INSERT INTO FT_T_CLDF
(TBL_ID, COL_NME, FLD_ID, PRNT_TBL_ID, PRNT_COL_NME, COL_REQ_IND, DDL_DATA_TYP, COL_SQ_NUM, LAST_CHG_TMS, LAST_CHG_USR_ID, NATIVE_COL_IND, LOGL_NME, COL_DESC, DDL_BASE_DATA_TYP, DDL_DATA_LEN, DDL_DATA_PREC_NUM, DDL_DATA_SCALE_NUM, DDL_DATA_DFLT_TXT, COL_VIEW_NME, ORACLE_LOB_TXT, DB2_LOB_TXT, INFO_TYP_NME, COL_OBSOLETE_IND, COL_CMNT_TXT, DSPY_CAPTION_TXT, DMN_SET_ID, EDMV_USED_IND)
VALUES('EADR', 'FAX_IND', '00074067', NULL, NULL, 'N', 'CHAR(1)', 90, TIMESTAMP '2012-06-30 00:00:00.000000', 'GS:MSYS', 'Y', 'FAX Indicator', 'This field indicates whether a telephone number can be used for FAX communication.
Note: This field is obsolete and is subject to removal in a future release.', 'CHAR', 1, NULL, NULL, NULL, 'FAX_Indicator', NULL, NULL, 'INDICATOR', NULL, 'Column is Obsolete', NULL, NULL, NULL);
commit;

INSERT INTO FT_T_CLDF
(TBL_ID, COL_NME, FLD_ID, PRNT_TBL_ID, PRNT_COL_NME, COL_REQ_IND, DDL_DATA_TYP, COL_SQ_NUM, LAST_CHG_TMS, LAST_CHG_USR_ID, NATIVE_COL_IND, LOGL_NME, COL_DESC, DDL_BASE_DATA_TYP, DDL_DATA_LEN, DDL_DATA_PREC_NUM, DDL_DATA_SCALE_NUM, DDL_DATA_DFLT_TXT, COL_VIEW_NME, ORACLE_LOB_TXT, DB2_LOB_TXT, INFO_TYP_NME, COL_OBSOLETE_IND, COL_CMNT_TXT, DSPY_CAPTION_TXT, DMN_SET_ID, EDMV_USED_IND)
VALUES('EADR', 'VOICE_IND', '00074302', NULL, NULL, 'N', 'CHAR(1)', 80, TIMESTAMP '2012-06-30 00:00:00.000000', 'GS:MSYS', 'Y', 'Voice Indicator', 'This field indicates whether a telephone number can be used for voice communication.
Note: This field is obsolete and is subject to removal in a future release.', 'CHAR', 1, NULL, NULL, NULL, 'Voice_Indicator', NULL, NULL, 'INDICATOR', NULL, 'Column is Obsolete', NULL, NULL, NULL);
commit;
