CREATE TABLE FT_T_RGM1(
RGM1_OID VARCHAR(10) NOT NULL,
REGIME_NME VARCHAR(40) NOT NULL,
NOTES VARCHAR(1000),
START_TMS TIMESTAMP(0) NOT NULL,
END_TMS TIMESTAMP(0),
LAST_CHG_TMS TIMESTAMP(0) NOT NULL,
LAST_CHG_USR_ID VARCHAR(256) NOT NULL,
DATA_STAT_TYP VARCHAR(20),
DATA_SRC_ID VARCHAR(40)) TABLESPACE pg_default;

ALTER TABLE FT_T_RGM1 ADD CONSTRAINT FT_T_RGM1_PK PRIMARY KEY (RGM1_OID);
CREATE UNIQUE INDEX FT_X_RGM1_U001 ON FT_T_RGM1(REGIME_NME) TABLESPACE pg_default;

CREATE TABLE CMFSOIADDITION_LOCK(
KEYS VARCHAR(80) NOT NULL,
JOB_ID VARCHAR(80),
LOCK_TMS TIMESTAMP(0)) TABLESPACE pg_default;

CREATE TABLE FT_T_AFD1(
AFD1_OID VARCHAR(10) NOT NULL,
FREQ_SP_TYP VARCHAR(2),
FREQ_DY_WEEK_TYP VARCHAR(10),
FREQ_DY_MNTH_TYP VARCHAR(2),
FREQ_MNTH_ORD_TYP VARCHAR(10),
RL_TYP VARCHAR(10) NOT NULL,
START_TMS TIMESTAMP(0) NOT NULL,
END_TMS TIMESTAMP(0),
LAST_CHG_TMS TIMESTAMP(0) NOT NULL,
LAST_CHG_USR_ID VARCHAR(256) NOT NULL,
DATA_STAT_TYP VARCHAR(20),
LEG_AGRMNT_ID VARCHAR(10) NOT NULL,
ORG_ID VARCHAR(4) NOT NULL) TABLESPACE pg_default;

ALTER TABLE FT_T_AFD1 ADD CONSTRAINT FT_T_AFD1_PK PRIMARY KEY (AFD1_OID);

CREATE TABLE FT_T_CLM1(
CLM1_OID VARCHAR(10) NOT NULL,
LEG_AGRMNT_ID VARCHAR(10) NOT NULL,
ORG_ID VARCHAR(4) NOT NULL,
START_TMS TIMESTAMP(0) NOT NULL,
END_TMS TIMESTAMP(0),
LAST_CHG_TMS TIMESTAMP(0) NOT NULL,
LAST_CHG_USR_ID VARCHAR(256) NOT NULL,
DATA_STAT_TYP VARCHAR(20),
COL_DISP_IND CHAR(1),
MHI_MIN_TSFR_CAMT NUMERIC(31,5),
CPTY_MIN_TSFR_CAMT NUMERIC(31,5),
MHI_THSHLD_CAMT NUMERIC(31,5),
CPTY_THSHLD_CAMT NUMERIC(31,5),
MHI_INDEPENDENT_CAMT NUMERIC(31,5),
CPTY_INDEPENDENT_CAMT NUMERIC(31,5),
LAAN_OID VARCHAR(10)) TABLESPACE pg_default;

ALTER TABLE FT_T_CLM1 ADD CONSTRAINT FT_T_CLM1_PK PRIMARY KEY (CLM1_OID);

CREATE TABLE FT_T_CPT1(
CPT1_OID VARCHAR(10) NOT NULL,
TODAY_DATE TIMESTAMP(0),
CUSTOMER_COUNT BIGINT,
ACCOUNT_COUNT BIGINT,
FINS_COUNT BIGINT,
ISSUER_COUNT BIGINT,
MIGRATION_END_TMS TIMESTAMP(0),
MIGRATION_SQL_START_TMS TIMESTAMP(0),
MIGRATION_SQL_END_TMS TIMESTAMP(0),
BUSINESS_REVIEW_TMS TIMESTAMP(0),
COMMENT_TXT_LOAD VARCHAR(4000),
COMMENT_TXT_SQL VARCHAR(4000),
COMMENT_TXT_BUSINESS VARCHAR(4000)) TABLESPACE pg_default;

ALTER TABLE FT_T_CPT1 ADD CONSTRAINT FT_T_CPT1_PK PRIMARY KEY (CPT1_OID);
CREATE UNIQUE INDEX FT_X_CPT1_U001 ON FT_T_CPT1(COALESCE(TODAY_DATE,'9999-12-31 00:00:00')) TABLESPACE pg_default;

 CREATE TABLE FT_T_CVT1(
CVT1_OID VARCHAR(10) NOT NULL,
RGM1_OID VARCHAR(10) NOT NULL,
TRAN_TYP VARCHAR(40),
CVRD_IND VARCHAR(1000),
EFF_TMS TIMESTAMP(0),
IM_IND VARCHAR(20),
VM_IND VARCHAR(20),
START_TMS TIMESTAMP(0) NOT NULL,
END_TMS TIMESTAMP(0),
LAST_CHG_TMS TIMESTAMP(0) NOT NULL,
LAST_CHG_USR_ID VARCHAR(256) NOT NULL,
DATA_STAT_TYP VARCHAR(20),
DATA_SRC_ID VARCHAR(40)) TABLESPACE pg_default;

ALTER TABLE FT_T_CVT1 ADD CONSTRAINT FT_T_CVT1_PK PRIMARY KEY (CVT1_OID);
ALTER TABLE FT_T_CVT1 ADD CONSTRAINT FT_T_CVT1_F001 FOREIGN KEY (RGM1_OID) REFERENCES FT_T_RGM1 NOT VALID;

CREATE TABLE FT_T_IOI_MHSS(
INSTR_ISSR_ID VARCHAR(10) NOT NULL,
UPDATING CHAR(1),
UPDATED CHAR(1),
ASSET_SOI CHAR(1),
GTOR CHAR(1),
CUST CHAR(1),
ASSET_RUP CHAR(1),
GTOR_RUP CHAR(1),
CUST_RUP CHAR(1),
CUST_IP CHAR(1),
LAGR_FLAR CHAR(1),
LAGR_FLAR_RUP CHAR(1),
DELETE_FROM_IOI CHAR(1),
NEW_IOI_MEMBER CHAR(1)) TABLESPACE pg_default;

 CREATE TABLE FT_T_IOI1(
INSTR_ISSR_ID VARCHAR(10) NOT NULL,
UPDATING CHAR(1),
UPDATED CHAR(1),
ASSET_SOI CHAR(1),
GTOR CHAR(1),
CUST CHAR(1),
ASSET_RUP CHAR(1),
GTOR_RUP CHAR(1),
CUST_RUP CHAR(1),
CUST_IP CHAR(1),
FENERGO CHAR(1),
FENERGO_IP CHAR(1),
FENERGO_RUP CHAR(1),
LAGR_FLAR CHAR(1),
LAGR_FLAR_RUP CHAR(1),
DELETE_FROM_IOI CHAR(1),
NEW_IOI_MEMBER CHAR(1)) TABLESPACE pg_default;

CREATE TABLE FT_T_IOI2(
ORG_ID VARCHAR(4) NOT NULL,
INSTR_ISSR_ID VARCHAR(10) NOT NULL,
RUN_WORKFLOW CHAR(1),
UPDATING CHAR(1),
UPDATED CHAR(1),
ASSET_SOI CHAR(1),
ASSET_RUP CHAR(1),
GTOR CHAR(1),
GTOR_RUP CHAR(1),
CUST CHAR(1),
CUST_IP CHAR(1),
CUST_RUP CHAR(1),
LAGR_FLAR CHAR(1),
LAGR_FLAR_RUP CHAR(1),
DELETE_FROM_IOI CHAR(1),
NEW_IOI_MEMBER CHAR(1)) TABLESPACE pg_default;

CREATE TABLE FT_T_LAAC(
LAAC_OID VARCHAR(10) NOT NULL,
LAAP_OID VARCHAR(10) NOT NULL,
CAL_ID VARCHAR(10) NOT NULL,
CAL_PURP_TYP VARCHAR(8) NOT NULL,
START_TMS TIMESTAMP(0) NOT NULL,
END_TMS TIMESTAMP(0),
LAST_CHG_TMS TIMESTAMP(0) NOT NULL,
LAST_CHG_USR_ID VARCHAR(256) NOT NULL,
CAL_PRT_DESC VARCHAR(254),
DATA_STAT_TYP VARCHAR(20),
DATA_SRC_ID VARCHAR(40)) TABLESPACE pg_default;

ALTER TABLE FT_T_LAAC ADD CONSTRAINT FT_T_LAAC_F001 FOREIGN KEY (LAAP_OID) REFERENCES FT_T_LAAP NOT VALID;
ALTER TABLE FT_T_LAAC ADD CONSTRAINT FT_T_LAAC_F002 FOREIGN KEY (CAL_ID) REFERENCES FT_T_CADF NOT VALID;
CREATE UNIQUE INDEX FT_X_LAAC_U001 ON FT_T_LAAC(LAAC_OID) TABLESPACE pg_default;

 CREATE TABLE FT_T_LAV1(
LAV1_OID VARCHAR(10) NOT NULL,
VERSION_NO BIGINT,
DOC_LINK VARCHAR(500),
AMEND_DESC VARCHAR(1024),
VER_AMEND_DTE TIMESTAMP(0),
START_TMS TIMESTAMP(0) NOT NULL,
END_TMS TIMESTAMP(0),
LAST_CHG_TMS TIMESTAMP(0) NOT NULL,
LAST_CHG_USR_ID VARCHAR(256) NOT NULL,
DATA_STAT_TYP VARCHAR(20),
LEG_AGRMNT_ID VARCHAR(10),
LAAN_OID VARCHAR(10),
ORG_ID VARCHAR(4),
INSTRUC_RELEASE_TMS TIMESTAMP(0),
FLAR_OID VARCHAR(10),
SIGN_DTE TIMESTAMP(0),
AGRMNT_STAT_TYP VARCHAR(20)) TABLESPACE pg_default;

ALTER TABLE FT_T_LAV1 ADD CONSTRAINT FT_T_LAV1_PK PRIMARY KEY (LAV1_OID);
ALTER TABLE FT_T_LAV1 ADD CONSTRAINT FT_T_LAV1_F001 FOREIGN KEY (LAAN_OID) REFERENCES FT_T_LAAN NOT VALID;
 
CREATE UNIQUE INDEX FT_X_LAV1_U001 ON FT_T_LAV1(COALESCE(VERSION_NO,9999999999),COALESCE(DOC_LINK,'=NULL='),COALESCE(LAAN_OID,'=NULL='),START_TMS,COALESCE(LEG_AGRMNT_ID,'=NULL='),COALESCE(ORG_ID,'=NULL='),COALESCE(FLAR_OID,'=NULL=')) TABLESPACE pg_default;

CREATE TABLE FT_T_MAC1(
MAC1_OID VARCHAR(10) NOT NULL,
INSTR_CLASSIFY VARCHAR(256) NOT NULL,
CNTRY_OF_RISK VARCHAR(256),
SECTOR_TYP VARCHAR(256),
INSTR_CATEGORY VARCHAR(256),
GOV_GUARANTEED_FLAG VARCHAR(1),
MHI_ACCT_CLASS VARCHAR(256),
LAST_CHG_TMS TIMESTAMP(0) NOT NULL,
LAST_CHG_USR_ID VARCHAR(256) NOT NULL) TABLESPACE pg_default;

ALTER TABLE FT_T_MAC1 ADD CONSTRAINT FT_T_MAC1_PK PRIMARY KEY (MAC1_OID);
CREATE UNIQUE INDEX FT_X_MAC1_U001 ON FT_T_MAC1(INSTR_CLASSIFY,COALESCE(CNTRY_OF_RISK,'=NULL='),COALESCE(SECTOR_TYP,'=NULL='),COALESCE(INSTR_CATEGORY,'=NULL='),COALESCE(GOV_GUARANTEED_FLAG,'=NULL='),COALESCE(MHI_ACCT_CLASS,'=NULL=')) TABLESPACE pg_default;

CREATE TABLE FT_T_REG1(
REG1_OID VARCHAR(10) NOT NULL,
RGM1_OID VARCHAR(10) NOT NULL,
LAAT_OID VARCHAR(10) NOT NULL,
SIMM_EXCEPTION VARCHAR(20),
EXP_DESC VARCHAR(1000),
RETRO_EXCEPTION VARCHAR(20),
RETRO_DATE TIMESTAMP(0),
START_TMS TIMESTAMP(0) NOT NULL,
END_TMS TIMESTAMP(0),
LAST_CHG_TMS TIMESTAMP(0) NOT NULL,
LAST_CHG_USR_ID VARCHAR(256) NOT NULL,
DATA_STAT_TYP VARCHAR(20),
DATA_SRC_ID VARCHAR(40)) TABLESPACE pg_default;

ALTER TABLE FT_T_REG1 ADD CONSTRAINT FT_T_REG1_PK PRIMARY KEY (REG1_OID);
ALTER TABLE FT_T_REG1 ADD CONSTRAINT FT_T_REG1_F001 FOREIGN KEY (RGM1_OID) REFERENCES FT_T_RGM1 NOT VALID;
ALTER TABLE FT_T_REG1 ADD CONSTRAINT FT_T_REG1_F002 FOREIGN KEY (LAAT_OID) REFERENCES FT_T_LAAT NOT VALID;

CREATE TABLE FT_T_RTG1(
RTG1_OID VARCHAR(10) NOT NULL,
RTNG_SRCE_TYP VARCHAR(10),
RTNG_CDE VARCHAR(40),
RTNG_CAMT NUMERIC(31,11),
RTNG_GRID_PURP_TYP VARCHAR(10),
START_TMS TIMESTAMP(0) NOT NULL,
END_TMS TIMESTAMP(0),
LAST_CHG_TMS TIMESTAMP(0) NOT NULL,
LAST_CHG_USR_ID VARCHAR(256) NOT NULL,
DATA_STAT_TYP VARCHAR(20),
LAAP_OID VARCHAR(10),
LAAT_OID VARCHAR(10),
MIN_RTNG_CDE VARCHAR(40),
RTNG_CDE_RANK BIGINT,
MIN_RTNG_CDE_RANK BIGINT) TABLESPACE pg_default;

ALTER TABLE FT_T_RTG1 ADD CONSTRAINT FT_T_RTG1_PK PRIMARY KEY (RTG1_OID);
ALTER TABLE FT_T_RTG1 ADD CONSTRAINT FT_T_RTG1_F001 FOREIGN KEY (LAAP_OID) REFERENCES FT_T_LAAP NOT VALID;
ALTER TABLE FT_T_RTG1 ADD CONSTRAINT FT_T_RTG1_F002 FOREIGN KEY (LAAT_OID) REFERENCES FT_T_LAAT NOT VALID;
CREATE UNIQUE INDEX FT_X_RTG1_U001 ON FT_T_RTG1(COALESCE(RTNG_SRCE_TYP,'=NULL='),COALESCE(RTNG_CDE,'=NULL='),COALESCE(RTNG_CAMT,9999999999999999999999999999999),START_TMS,COALESCE(RTNG_GRID_PURP_TYP,'=NULL='),COALESCE(MIN_RTNG_CDE,'=NULL=')) TABLESPACE pg_default;

CREATE TABLE FT_T_SFTR1(
SFTR_OID VARCHAR(10) NOT NULL,
ASSET_TYPE VARCHAR(8) NOT NULL,
MARKET_SECTOR VARCHAR(256),
SECURITY_TYPE VARCHAR(256),
INDUSTRY_SECTOR VARCHAR(256),
INDUSTRY_GROUP VARCHAR(256),
INDUSTRY_SUBGROUP VARCHAR(256),
MAIN_INDEX VARCHAR(10),
SFTR_TYPE VARCHAR(10) NOT NULL,
LAST_CHG_TMS TIMESTAMP(0) NOT NULL,
LAST_CHG_USR_ID VARCHAR(256) NOT NULL) TABLESPACE pg_default;

ALTER TABLE FT_T_SFTR1 ADD CONSTRAINT FT_T_SFTR1_PK PRIMARY KEY (SFTR_OID);
CREATE UNIQUE INDEX FT_X_SFTR1_U001 ON FT_T_SFTR1(ASSET_TYPE,COALESCE(MARKET_SECTOR,'=NULL='),COALESCE(SECURITY_TYPE,'=NULL='),COALESCE(INDUSTRY_SECTOR,'=NULL='),COALESCE(INDUSTRY_GROUP,'=NULL='),COALESCE(INDUSTRY_SUBGROUP,'=NULL='),COALESCE(MAIN_INDEX,'=NULL=')) TABLESPACE pg_default;

CREATE TABLE FT_T_SOI1(
SOI1_OID VARCHAR(10) NOT NULL,
SOI_NME VARCHAR(256) NOT NULL,
INSTR_ID VARCHAR(10) NOT NULL,
DATA_SRC_ID VARCHAR(40),
START_TMS TIMESTAMP(0) NOT NULL,
END_TMS TIMESTAMP(0),
LAST_CHG_TMS TIMESTAMP(0) NOT NULL,
LAST_CHG_USR_ID VARCHAR(256) NOT NULL,
INSTR_ISSR_ID VARCHAR(10)) TABLESPACE pg_default;

ALTER TABLE FT_T_SOI1 ADD CONSTRAINT FT_T_SOI1_PK PRIMARY KEY (SOI1_OID);
CREATE UNIQUE INDEX FT_X_SOI1_U001 ON FT_T_SOI1(SOI_NME,INSTR_ID,START_TMS) TABLESPACE pg_default;

CREATE TABLE FT_T_STR1(
STAT_ID VARCHAR(10) NOT NULL,
STAT_DEF_ID VARCHAR(8) NOT NULL,
TBL_ID VARCHAR(4) NOT NULL,
XREF_ID VARCHAR(12) NOT NULL,
START_TMS TIMESTAMP(0) NOT NULL,
END_TMS TIMESTAMP(0),
LAST_CHG_TMS TIMESTAMP(0) NOT NULL,
LAST_CHG_USR_ID VARCHAR(256) NOT NULL,
STAT_VAL_DTE TIMESTAMP(0),
STAT_VAL_TMS TIMESTAMP(0),
STAT_INT_VAL_NUM BIGINT,
STAT_CHAR_VAL_TXT VARCHAR(254),
DATA_STAT_TYP VARCHAR(20),
DATA_SRC_ID VARCHAR(40)) TABLESPACE pg_default;

ALTER TABLE FT_T_STR1 ADD CONSTRAINT FT_T_STR1_PK PRIMARY KEY (STAT_ID);
ALTER TABLE FT_T_STR1 ADD CONSTRAINT STR1F001 FOREIGN KEY (STAT_DEF_ID) REFERENCES FT_T_STDF NOT VALID;

CREATE TABLE FT_T_TAX1(
TAX1_OID VARCHAR(10) NOT NULL,
MHI_REF_NO VARCHAR(10),
START_TMS TIMESTAMP(0),
TAXONOMY_DESC VARCHAR(4000),
LAST_CHG_USR_ID VARCHAR(256),
LAST_CHG_TMS TIMESTAMP(0),
END_TMS TIMESTAMP(0),
TAX_PROD_GRP_OID VARCHAR(10),
TAX_ASST_GRP_OID VARCHAR(10),
TAX_PROD_ID VARCHAR(8),
TAX_PROD_ORG_ID VARCHAR(4),
TAX_SUB_PROD_ID VARCHAR(8),
TAX_SUB_PROD_ORG_ID VARCHAR(4)) TABLESPACE pg_default;

ALTER TABLE FT_T_TAX1 ADD CONSTRAINT FT_T_TAX1_PK PRIMARY KEY (TAX1_OID);
ALTER TABLE FT_T_TAX1 ADD CONSTRAINT FT_T_TAX1_FK03 FOREIGN KEY (TAX_PROD_GRP_OID) REFERENCES FT_T_PDGR NOT VALID;
ALTER TABLE FT_T_TAX1 ADD CONSTRAINT FT_T_TAX1_FK04 FOREIGN KEY (TAX_ASST_GRP_OID) REFERENCES FT_T_PDGR NOT VALID;
CREATE UNIQUE INDEX FT_X_TAX1_U001 ON FT_T_TAX1(COALESCE(MHI_REF_NO,'=NULL=')) TABLESPACE pg_default;
CREATE UNIQUE INDEX FT_X_TAX1_U002 ON FT_T_TAX1(COALESCE(TAX_PROD_GRP_OID,'=NULL='),COALESCE(TAX_ASST_GRP_OID,'=NULL='),COALESCE(TAX_PROD_ID,'=NULL='),COALESCE(TAX_PROD_ORG_ID,'=NULL='),COALESCE(TAX_SUB_PROD_ID,'=NULL='),COALESCE(TAX_SUB_PROD_ORG_ID,'=NULL=')) TABLESPACE pg_default;

CREATE TABLE FT_T_UPD1(
UPD1_OID VARCHAR(10) NOT NULL,
ENTITY_TBL_TYP VARCHAR(4),
XREF_TBL_ROW_OID VARCHAR(12),
UPDATED_TMSMP TIMESTAMP(0),
TRN_ID VARCHAR(16),
REFERENCE VARCHAR(100),
ENTITY_CHG_IND CHAR(1),
VERSION BIGINT,
SEQUENCENO NUMERIC(38)) TABLESPACE pg_default;

ALTER TABLE FT_T_UPD1 ADD CONSTRAINT FT_T_UPD1_PK PRIMARY KEY (UPD1_OID);
CREATE INDEX FT_X_UPD1_I001 ON FT_T_UPD1(ENTITY_TBL_TYP,XREF_TBL_ROW_OID,SEQUENCENO) TABLESPACE pg_default;
CREATE INDEX ft_x_upd1_p001 ON ft_t_upd1 USING btree (xref_tbl_row_oid);

CREATE TABLE MHI_SETTLECODE_MAP1(
MAP1_OID VARCHAR(10) NOT NULL,
INSTR_CLASSIFY VARCHAR(256) NOT NULL,
ISSUE_TYPE VARCHAR(256),
START_TMS TIMESTAMP(0) NOT NULL,
END_TMS TIMESTAMP(0),
LAST_CHG_TMS TIMESTAMP(0) NOT NULL,
LAST_CHG_USR_ID VARCHAR(256) NOT NULL) TABLESPACE pg_default;

ALTER TABLE MHI_SETTLECODE_MAP1 ADD CONSTRAINT MHI_SETTLECODE_MAP1_PK PRIMARY KEY (MAP1_OID);
CREATE UNIQUE INDEX FT_X_MAP1_U001 ON MHI_SETTLECODE_MAP1(INSTR_CLASSIFY,COALESCE(ISSUE_TYPE,'=NULL='),COALESCE(END_TMS,'9999-12-31 00:00:00')) TABLESPACE pg_default;

CREATE TABLE MHI_TB_CLEANUPFILES(
VENDOR_NAME VARCHAR(100) NOT NULL,
FILESYSTEM_DIRECTORY_PATH VARCHAR(500) NOT NULL,
FILE_PATTERN VARCHAR(500) NOT NULL,
PURGE_THRESHOLD_DAYS NUMERIC,
ARCHIVE_FLAG CHAR(1) NOT NULL DEFAULT 'N' ,
ARCHIVE_THRESHOLD_DAYS NUMERIC) TABLESPACE pg_default;

CREATE TABLE MHI_TB_EVENTLOG(
EVENT_ID NUMERIC NOT NULL,
EVENT_CREATOR VARCHAR(100),
EVENT_DESC VARCHAR(250),
EVENT_VALUE VARCHAR(4000),
EVENT_TYPE VARCHAR(25),
EVENT_TMS TIMESTAMP(0),
EVENT_JOB_ID VARCHAR(16)) TABLESPACE pg_default;

ALTER TABLE MHI_TB_EVENTLOG ADD CONSTRAINT MHI_TB_EVENTLOG_PK PRIMARY KEY (EVENT_ID);

CREATE TABLE MHI_URL(
URL VARCHAR(100) NOT NULL) TABLESPACE pg_default;

CREATE TABLE UP_CHILDREN(
OID VARCHAR(20) NOT NULL,
TRN_ID VARCHAR(20),
JOB_NUM VARCHAR(16),
START_TMS TIMESTAMP(0) DEFAULT (sysdate()),
PRNT_INST_MNEM VARCHAR(20) NOT NULL,
CROSS_REF_ID VARCHAR(20) NOT NULL,
ENTITY_TYPE VARCHAR(20) NOT NULL) TABLESPACE pg_default;

ALTER TABLE UP_CHILDREN ADD CONSTRAINT UP_CHILDREN_PK PRIMARY KEY (OID);

CREATE TABLE ft_t_prpu_datamig (
    prod_id CHAR(8) NOT NULL,
    prod_org_id CHAR(4) NOT NULL,
    acct_org_id CHAR(4),
    acct_bk_id CHAR(4),
    acct_id CHAR(12),
    pr_dte DATE NOT NULL,
    plne_prodln_id CHAR(8),
    plne_org_id CHAR(4),
    lagr_leg_agrmnt_id CHAR(10),
    lagr_org_id CHAR(4),
    cst_id CHAR(12),
    pr_desc VARCHAR(254),
    last_chg_usr_id VARCHAR(256) NOT NULL,
    last_chg_tms TIMESTAMP NOT NULL,
    data_stat_typ VARCHAR(20),
    data_src_id VARCHAR(40),
    prpu_oid CHAR(10) NOT NULL,
    pr_stat_typ VARCHAR(20),
    pr_stat_tms TIMESTAMP,
    inst_mnem CHAR(10),
    finr_inst_mnem CHAR(10),
    finsrl_typ CHAR(8),
    start_tms TIMESTAMP,
    end_tms TIMESTAMP,
    mhi_limit_rqst VARCHAR(100),
    mhi_tenor VARCHAR(100),
    mhi_cash VARCHAR(100),
    mhi_trdng_cde VARCHAR(100),
    mhi_blmbrg_cde VARCHAR(100),
    mhi_fut_agrmnt VARCHAR(100),
    mhi_limit_qualifier VARCHAR(100),
    mhi_repo_netting CHAR(1),
    mhi_repo_wrtn_agrmnt CHAR(1),
    mhi_risk_appr_req CHAR(1),
    mhi_risk_appr_recd VARCHAR(100),
    mhi_ho_appr_req CHAR(1),
    mhi_ho_appr_recd VARCHAR(100),
    mhi_isda_flag CHAR(1),
    mhi_isda_netting CHAR(1),
    mhi_isda_date DATE,
    mhi_repo_date DATE,
    mhi_csa_flag CHAR(1),
    mhi_dvp VARCHAR(100),
    mhi_bilateral CHAR(1),
    mhi_cleared CHAR(1)
) TABLESPACE pg_default;

ALTER TABLE FT_T_PRPU_DATAMIG ADD CONSTRAINT FT_T_PRPU_DATAMIG_PK PRIMARY KEY (PRPU_OID);

CREATE TABLE ft_t_inlm_datamig (
    inlm_oid CHAR(10) NOT NULL,
    org_id CHAR(4),
    bk_id CHAR(4),
    acct_id CHAR(12),
    engr_oid CHAR(10),
    acct_grp_oid CHAR(10),
    cst_id CHAR(12),
    cst_grp_oid CHAR(10),
    inst_mnem CHAR(10),
    finr_inst_mnem CHAR(10),
    finsrl_typ CHAR(8),
    instr_id CHAR(10),
    iss_grp_oid CHAR(10),
    iss_typ CHAR(8),
    iss_typ_grp_oid CHAR(10),
    instr_issr_id CHAR(10),
    gu_id CHAR(8),
    gu_typ CHAR(8),
    gu_cnt INTEGER,
    gu_grp_oid CHAR(10),
    clsf_oid CHAR(10),
    cl_value VARCHAR(40),
    rtng_value_oid CHAR(10),
    rtng_cde VARCHAR(40),
    limit_typ VARCHAR(20),
    limit_purp_typ VARCHAR(20),
    limit_curr_cde CHAR(3),
    risk_lvl_num INTEGER,
    limit_tenor_typ VARCHAR(8),
    limit_eff_tms DATE,
    limit_end_tms DATE,
    start_tms TIMESTAMP NOT NULL,
    end_tms TIMESTAMP,
    limit_camt NUMERIC(31,5),
    limit_cqty NUMERIC(31,11),
    limit_lcl_curr_cde CHAR(3),
    limit_stat_typ VARCHAR(20),
    limit_stat_tms TIMESTAMP,
    limit_desc VARCHAR(254),
    last_chg_tms TIMESTAMP NOT NULL,
    last_chg_usr_id VARCHAR(256) NOT NULL,
    data_stat_typ VARCHAR(20),
    data_src_id VARCHAR(40),
    prod_org_id CHAR(4),
    prod_id CHAR(8),
    prpu_oid CHAR(10),
    limit_auth_stat_typ VARCHAR(20),
    limit_auth_stat_tms TIMESTAMP,
    mhi_fut_agrmnt VARCHAR(100),
    mhi_repo_wrtn_agrmnt CHAR(1),
    mhi_repo_netting CHAR(1),
    mhi_swap_netting CHAR(1),
    mhi_limit_qualifier VARCHAR(100)
) TABLESPACE pg_default;

ALTER TABLE FT_T_INLM_DATAMIG ADD CONSTRAINT FT_T_INLM_DATAMIG_PK PRIMARY KEY (INLM_OID);


----------------------------------------------------------------------------------------
							--- Basel 3 Tables ---
----------------------------------------------------------------------------------------

CREATE TABLE FT_T_BBX1 (
    BBX1_OID           CHAR(10)      NOT NULL,				-- change it to VARCHAR(10)
    BOE_CDE_EXPR       VARCHAR(20)   NOT NULL,
    INIT_EXP_CLS_CDE   VARCHAR(40)   NOT NULL,
    INIT_EXP_CLS_NME   VARCHAR(256),
    RTNG_JURIS_NME     VARCHAR(8),
    START_TMS          TIMESTAMP     NOT NULL,
    END_TMS            TIMESTAMP,
    LAST_CHG_TMS       TIMESTAMP     NOT NULL,
    LAST_CHG_USR_ID    VARCHAR(256)  NOT NULL
);

CREATE UNIQUE INDEX FT_X_BBX1_U001 ON FT_T_BBX1 (BOE_CDE_EXPR, RTNG_JURIS_NME, END_TMS);
ALTER TABLE FT_T_BBX1 ADD CONSTRAINT FT_T_BBX1_PK PRIMARY KEY (BBX1_OID);

CREATE TABLE FT_T_BCQ1 (
    BCQ1_OID           CHAR(10)      NOT NULL,	-- change it to VARCHAR(10)
    RTNG_SET_TBL_TYP   CHAR(4),					-- change it to VARCHAR(4)
    RTNG_JURIS_NME     VARCHAR(8),
    DATA_SRC_ID        VARCHAR(40)   NOT NULL,
    RTNG_CDE           VARCHAR(40)   NOT NULL,
    RTNG_RANK_NUM      NUMERIC(10)   NOT NULL,
    RTNG_CQS_NUM       NUMERIC(10)   NOT NULL,
    START_TMS          TIMESTAMP     NOT NULL,
    END_TMS            TIMESTAMP,
    LAST_CHG_TMS       TIMESTAMP     NOT NULL,
    LAST_CHG_USR_ID    VARCHAR(256)  NOT NULL
);

CREATE UNIQUE INDEX FT_X_BCQ1_U001 ON FT_T_BCQ1 (RTNG_SET_TBL_TYP, RTNG_JURIS_NME, DATA_SRC_ID, RTNG_CDE, RTNG_RANK_NUM, RTNG_CQS_NUM, END_TMS);
ALTER TABLE FT_T_BCQ1 ADD CONSTRAINT FT_T_BCQ1_PK PRIMARY KEY (BCQ1_OID);

CREATE TABLE FT_T_BIX1 (
    BIX1_OID              CHAR(10)     NOT NULL,	-- change it to VARCHAR(10)
    INIT_EXP_CLS_CDE      VARCHAR(40)  NOT NULL,
    CNTRY_GU_ID           CHAR(8),					-- change it to VARCHAR(256)
    PRA_TRDCNTRY_EQ_VAL   VARCHAR(40),
    EBA_TRDCNTRY_EQ_VAL   VARCHAR(40),
    PRA_INTER_EXPR_CLS    VARCHAR(40)  NOT NULL,
    EBA_INTER_EXPR_CLS    VARCHAR(40)  NOT NULL,
    START_TMS             TIMESTAMP    NOT NULL,
    END_TMS               TIMESTAMP,
    LAST_CHG_TMS          TIMESTAMP    NOT NULL,
    LAST_CHG_USR_ID       VARCHAR(256) NOT NULL
);

CREATE UNIQUE INDEX FT_X_BIX1_U001 ON FT_T_BIX1 (INIT_EXP_CLS_CDE, CNTRY_GU_ID, PRA_TRDCNTRY_EQ_VAL, EBA_TRDCNTRY_EQ_VAL, END_TMS);
ALTER TABLE FT_T_BIX1 ADD CONSTRAINT FT_T_BIX1_PK PRIMARY KEY (BIX1_OID);

CREATE TABLE FT_T_BLG1 (
    BLG1_OID                  CHAR(10)     NOT NULL,	 -- change it to VARCHAR(10)
    B3_RTNG_SET_OID           CHAR(10)     NOT NULL,     -- change it to VARCHAR(10)
    INST_MNEM                 CHAR(10),                  -- change it to VARCHAR(10)
    INSTR_ID                  CHAR(10),                  -- change it to VARCHAR(10)
    FINS_RTNG_OID             CHAR(10),                  -- change it to VARCHAR(10)
    ISS_RTNG_OID              CHAR(10),                  -- change it to VARCHAR(10)
    TRN_ID                    CHAR(16),                  -- change it to VARCHAR(16)
    DRV_RTNG_SRC_INST_MNEM    CHAR(10),                  -- change it to VARCHAR(10)
    DRV_RTNG_SRC_INSTR_ID     CHAR(10),                  -- change it to VARCHAR(10)
    STATUS_TYP                VARCHAR(40)  NOT NULL,
    ADDL_INFO_TXT             VARCHAR(1000),
    TRACE_PATH                VARCHAR(4000),
    ERROR_TXT                 VARCHAR(1000),
    CREATED_TMS               TIMESTAMP    NOT NULL,
    LAST_CHG_TMS              TIMESTAMP    NOT NULL,
    LAST_CHG_USR_ID           VARCHAR(256) NOT NULL
);

ALTER TABLE FT_T_BLG1 ADD CONSTRAINT FT_T_BLG1_PK PRIMARY KEY (BLG1_OID);

CREATE TABLE FT_T_BRM1 (
    BRM1_OID               CHAR(10)     NOT NULL,	   -- change it to VARCHAR(10)
    VND_RTNG_SET_OID       CHAR(10)     NOT NULL,      -- change it to VARCHAR(10)
    B3_RTNG_SET_OID        CHAR(10)     NOT NULL,      -- change it to VARCHAR(10)
    VND_RTNG_CURR_TYP      VARCHAR(20),
    B3_RTNG_CURR_TYP       VARCHAR(20),
    RTNG_JURIS_NME         VARCHAR(8),
    BRM1_CONFIG_DESC       VARCHAR(1024),
    RTNG_SET_TBL_TYP       CHAR(4)      NOT NULL,	-- change it to VARCHAR(4)
    MDY_RTNG_DEBT_CL_TYP   CHAR(8),					-- change it to VARCHAR(8)
    START_TMS              TIMESTAMP    NOT NULL,
    END_TMS                TIMESTAMP,
    LAST_CHG_TMS           TIMESTAMP    NOT NULL,
    LAST_CHG_USR_ID        VARCHAR(256) NOT NULL
);

CREATE UNIQUE INDEX FT_X_BRM1_U001 ON FT_T_BRM1 (VND_RTNG_SET_OID, B3_RTNG_SET_OID, B3_RTNG_CURR_TYP, VND_RTNG_CURR_TYP, RTNG_JURIS_NME, END_TMS, MDY_RTNG_DEBT_CL_TYP);
ALTER TABLE FT_T_BRM1 ADD CONSTRAINT FT_T_BRM1_PK PRIMARY KEY (BRM1_OID);
ALTER TABLE FT_T_BRM1 ADD CONSTRAINT BRM1F001 FOREIGN KEY (VND_RTNG_SET_OID) REFERENCES FT_T_RTNG(RTNG_SET_OID);
ALTER TABLE FT_T_BRM1 ADD CONSTRAINT BRM1F002 FOREIGN KEY (B3_RTNG_SET_OID) REFERENCES FT_T_RTNG(RTNG_SET_OID);

CREATE TABLE FT_T_BRQ1 (
    BRQ1_OID          CHAR(10)     NOT NULL,	-- change it to VARCHAR(10)
    RTNG_JURIS_NME    VARCHAR(8),
    EXP_CLS_NME       VARCHAR(40)  NOT NULL,
    CGOV_CQS          VARCHAR(8),
    RTNG_CQS_NUM      NUMERIC(10)  NOT NULL,
    QLTY_CDE          VARCHAR(8)   NOT NULL,
    START_TMS         TIMESTAMP    NOT NULL,
    END_TMS           TIMESTAMP,
    LAST_CHG_TMS      TIMESTAMP    NOT NULL,
    LAST_CHG_USR_ID   VARCHAR(256) NOT NULL
);

CREATE UNIQUE INDEX FT_X_BRQ1_U001 ON FT_T_BRQ1 (RTNG_JURIS_NME, EXP_CLS_NME, CGOV_CQS, RTNG_CQS_NUM, QLTY_CDE, END_TMS);
ALTER TABLE FT_T_BRQ1 ADD CONSTRAINT FT_T_BRQ1_PK PRIMARY KEY (BRQ1_OID);

CREATE TABLE FT_T_BTC1 (
    BTC1_OID           CHAR(10)     NOT NULL,	-- change it to VARCHAR(10)
    CNTRY_GU_ID        CHAR(8)      NOT NULL,	-- change it to VARCHAR(256)
    RTNG_JURIS_NME     VARCHAR(8)   NOT NULL,
    INIT_EXP_CLS_CDE   VARCHAR(40)  NOT NULL,
    THIRD_CNTRY_EQ     VARCHAR(8)   NOT NULL,
    START_TMS          TIMESTAMP    NOT NULL,
    END_TMS            TIMESTAMP,
    LAST_CHG_TMS       TIMESTAMP    NOT NULL,
    LAST_CHG_USR_ID    VARCHAR(256) NOT NULL
);

CREATE UNIQUE INDEX FT_X_BTC1_U001 ON FT_T_BTC1 (CNTRY_GU_ID, RTNG_JURIS_NME, INIT_EXP_CLS_CDE, END_TMS);
ALTER TABLE FT_T_BTC1 ADD CONSTRAINT FT_T_BTC1_PK PRIMARY KEY (BTC1_OID);

-----------------------------------------------------------------
		---	BASEL III ALTER SCRIPT FOR DATA TYPE CHANGE ---
-----------------------------------------------------------------


ALTER TABLE FT_T_BBX1 
    ALTER COLUMN BBX1_OID TYPE VARCHAR(10);

ALTER TABLE FT_T_BCQ1
    ALTER COLUMN BCQ1_OID TYPE VARCHAR(10),
    ALTER COLUMN RTNG_SET_TBL_TYP TYPE VARCHAR(4);

ALTER TABLE FT_T_BIX1
    ALTER COLUMN BIX1_OID TYPE VARCHAR(10),
    ALTER COLUMN CNTRY_GU_ID TYPE VARCHAR(256);

ALTER TABLE FT_T_BLG1
    ALTER COLUMN BLG1_OID TYPE VARCHAR(10),
    ALTER COLUMN B3_RTNG_SET_OID TYPE VARCHAR(10),
    ALTER COLUMN INST_MNEM TYPE VARCHAR(10),
    ALTER COLUMN INSTR_ID TYPE VARCHAR(10),
    ALTER COLUMN FINS_RTNG_OID TYPE VARCHAR(10),
    ALTER COLUMN ISS_RTNG_OID TYPE VARCHAR(10),
    ALTER COLUMN TRN_ID TYPE VARCHAR(16),
    ALTER COLUMN DRV_RTNG_SRC_INST_MNEM TYPE VARCHAR(10),
    ALTER COLUMN DRV_RTNG_SRC_INSTR_ID TYPE VARCHAR(10);

ALTER TABLE FT_T_BRM1
    ALTER COLUMN BRM1_OID TYPE VARCHAR(10),
    ALTER COLUMN VND_RTNG_SET_OID TYPE VARCHAR(10),
    ALTER COLUMN B3_RTNG_SET_OID TYPE VARCHAR(10),
    ALTER COLUMN RTNG_SET_TBL_TYP TYPE VARCHAR(4),
    ALTER COLUMN MDY_RTNG_DEBT_CL_TYP TYPE VARCHAR(8);

ALTER TABLE FT_T_BRQ1
    ALTER COLUMN BRQ1_OID TYPE VARCHAR(10);

ALTER TABLE FT_T_BTC1
    ALTER COLUMN BTC1_OID TYPE VARCHAR(10),
    ALTER COLUMN CNTRY_GU_ID TYPE VARCHAR(256);
