import java.util.Date;
import java.util.List;

import org.apache.log4j.Logger;

import com.thegoldensource.jbre.DatabaseAccess;
import com.thegoldensource.jbre.DatabaseObjectContainer;
import com.thegoldensource.jbre.GSException;
import com.thegoldensource.jbre.JavaRule;
import com.thegoldensource.jbre.NotificationCreator;
import com.thegoldensource.jbre.ProcessorContext;
import com.thegoldensource.jbre.SegmentId;
import com.thegoldensource.jbre.XMLMessage;


public class CJavaMHIIdentiferCorrection implements JavaRule {
	
	private static final Logger logger = Logger.getLogger(CJavaMHIListingIdUnlisted.class.getName());
	String prtPurpTyp;
	
	 private static String[] idTypeList={"MHILIST","SECREF"};
	
		@Override
	public boolean initialize(String[] arg0) {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public boolean process(XMLMessage xmlMsg, DatabaseObjectContainer dboc,
			ProcessorContext pContext, DatabaseAccess dbAccess, NotificationCreator notcfcn)
			throws GSException {
		
		String mainIssueType  = xmlMsg.getStringField("MAIN_ENTITY_TBL_TYP", new SegmentId(0));
		
		 if(logger.isDebugEnabled())
           logger.debug("xml: " + xmlMsg.getXMLString());
		
		
		log("Main Entity Table:  "+mainIssueType);
		
		if (!"ISSU".equals(mainIssueType)){
			log("Exiting Rule as it is not an ISSU entity");
			return true;
		}
		// Exit rule if the message is generated by GS UI
		String msgClassification = xmlMsg.getStringField("MSG_CLASSIFICATION", new SegmentId(0));
		log("MSGCLASSIFICATION:  "+msgClassification);
		
		if("WEBMSG".equalsIgnoreCase(msgClassification))
		{
			logger.info("Exiting Rule as it is UI message");
			return true;
		}
		
		if (pContext.isNewIssue()){
			log("Exiting Rule as it is an new ISSU entity");
			return true;
		}
				
		String instr_id=pContext.getInstrId();
		String sqlQuery="select isid_oid,iss_id from ft_t_isid where id_ctxt_typ=:1<char[40]> and mkt_oid='MKTMICXXXX' and (end_tms is null or end_tms > SYSDATE()) and instr_id=:2<char[11]>";
		
		for(int i=0;i<idTypeList.length;i++)
		{
			log("Inside for loop: "+i);
			String idType=idTypeList[i];
		
			dbAccess.setSQL(sqlQuery);
		try {
			dbAccess.addParameter(idType);
			dbAccess.addParameter(instr_id);
		} catch (Exception e) {
			
			e.printStackTrace();
		}
		dbAccess.execute();
		
		String dbIsidOid=null;
		
		String dbIssId=null;
		
		
		if(!dbAccess.isEndOfStream()){
			dbIsidOid=dbAccess.getNextString();
			dbIssId=dbAccess.getNextString();
		}
		log ("dbIsidOid: "+dbIsidOid);
		log ("dbIssId: "+dbIssId);
		
		if (dbIssId==null){
			log("Exiting Rule as there is no existing "+idType+" with mkt oid as MKTMICXXXX in DB for same instr id");
			continue;
		}
		
		List<SegmentId> segIds=Common.getSegmentIds("IssueIdentifier", xmlMsg);
		
		SegmentId segIdMhi=null;
		String mhiListIdmsg=null;
		
		for(SegmentId segid: segIds){
			if(idType.equals(xmlMsg.getStringField("ID_CTXT_TYP", segid))){
				segIdMhi=segid;
				mhiListIdmsg=xmlMsg.getStringField("ISS_ID", segid);
			}
		}
		
		if(segIdMhi==null || mhiListIdmsg==null){
			log("Exiting Rule as it doesn't have "+idType+" seg id");
			continue;
		}
		log("segIdMhi: "+segIdMhi);
//		xmlMsg.removeField("ISS_ID", segIdMhi);
//		log("temp1 XML: "+xmlMsg.getXMLString());
//		xmlMsg.addField("ISS_ID", segIdMhi, dbIssId);
//		log("temp2 XML: "+xmlMsg.getXMLString());
		
		SegmentId mhiListSeg = xmlMsg.addSegment(XMLMessage.A_D_UPDATE,"IssueIdentifier");		
//		xmlMsg.setSegmentAttribute(mhiListSeg, "MATCH", "ISID6_CTX_ID_MKT_USG");
		xmlMsg.addField("ISID_OID", mhiListSeg, dbIsidOid);
		xmlMsg.addField("ISS_ID", mhiListSeg, mhiListIdmsg);
		xmlMsg.addField("END_TMS", mhiListSeg, new Date());
		
		SegmentId mhiListSegnew = xmlMsg.addSegment(XMLMessage.A_D_UPDATE,"IssueIdentifier");		
//		xmlMsg.setSegmentAttribute(mhiListSeg, "MATCH", "ISID6_CTX_ID_MKT_USG");
		xmlMsg.addField("ISID_OID", mhiListSegnew, xmlMsg.getStringField("ISID_OID", segIdMhi));
		xmlMsg.addField("ISS_ID", mhiListSegnew, dbIssId);
		}
		
		// TODO Auto-generated method stub
		return true;
	}
	
	public void log(Object s){
		if(logger.isDebugEnabled())
			logger.debug(s);
	}
	
}
