--STEP--1--

ALTER TABLE FT_t_LAV1 ADD COLUMN lagr_oid VARCHAR(10);

ALTER TABLE FT_t_AFD1 ADD COLUMN lagr_oid VARCHAR(10);

ALTER TABLE FT_t_CLM1 ADD COLUMN lagr_oid VARCHAR(10);

--STEP--2--

INSERT INTO FT_T_CLDF
(TBL_ID, COL_NME, FLD_ID, PRNT_TBL_ID, PRNT_COL_NME, COL_REQ_IND, DDL_DATA_TYP, COL_SQ_NUM, LAST_CHG_TMS, LAST_CHG_USR_ID, NATIVE_COL_IND, LOGL_NME, COL_DESC, DDL_BASE_DATA_TYP, DDL_DATA_LEN, DDL_DATA_PREC_NUM, DDL_DATA_SCALE_NUM, DDL_DATA_DFLT_TXT, COL_VIEW_NME, ORACLE_LOB_TXT, DB2_LOB_TXT, INFO_TYP_NME, COL_OBSOLETE_IND, COL_CMNT_TXT, DSPY_CAPTION_TXT, DMN_SET_ID, EDMV_USED_IND, VIRTUAL_COL_IND)
VALUES('AFD1', 'LAGR_OID', '01871233', 'LAGR', 'LAGR_OID', 'Y', 'VARCHAR(10)', 20, sysdate(), 'GS:MSYS', 'N', 'Legal Agreement OID', 'This is a required foreign key column referencing the Legal Agreement (FT_T_LAGR) table with relationship ''annexure for''.', 'VARCHAR', 10, NULL, NULL, NULL, NULL, NULL, NULL, 'OBJECT_IDENTIFIER', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO FT_T_CLDF
(TBL_ID, COL_NME, FLD_ID, PRNT_TBL_ID, PRNT_COL_NME, COL_REQ_IND, DDL_DATA_TYP, COL_SQ_NUM, LAST_CHG_TMS, LAST_CHG_USR_ID, NATIVE_COL_IND, LOGL_NME, COL_DESC, DDL_BASE_DATA_TYP, DDL_DATA_LEN, DDL_DATA_PREC_NUM, DDL_DATA_SCALE_NUM, DDL_DATA_DFLT_TXT, COL_VIEW_NME, ORACLE_LOB_TXT, DB2_LOB_TXT, INFO_TYP_NME, COL_OBSOLETE_IND, COL_CMNT_TXT, DSPY_CAPTION_TXT, DMN_SET_ID, EDMV_USED_IND, VIRTUAL_COL_IND)
VALUES('CLM1', 'LAGR_OID', '01871233', 'LAGR', 'LAGR_OID', 'Y', 'VARCHAR(10)', 20, sysdate(), 'GS:MSYS', 'N', 'Legal Agreement OID', 'This is a required foreign key column referencing the Legal Agreement (FT_T_LAGR) table with relationship ''annexure for''.', 'VARCHAR', 10, NULL, NULL, NULL, NULL, NULL, NULL, 'OBJECT_IDENTIFIER', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO FT_T_CLDF
(TBL_ID, COL_NME, FLD_ID, PRNT_TBL_ID, PRNT_COL_NME, COL_REQ_IND, DDL_DATA_TYP, COL_SQ_NUM, LAST_CHG_TMS, LAST_CHG_USR_ID, NATIVE_COL_IND, LOGL_NME, COL_DESC, DDL_BASE_DATA_TYP, DDL_DATA_LEN, DDL_DATA_PREC_NUM, DDL_DATA_SCALE_NUM, DDL_DATA_DFLT_TXT, COL_VIEW_NME, ORACLE_LOB_TXT, DB2_LOB_TXT, INFO_TYP_NME, COL_OBSOLETE_IND, COL_CMNT_TXT, DSPY_CAPTION_TXT, DMN_SET_ID, EDMV_USED_IND, VIRTUAL_COL_IND)
VALUES('LAV1', 'LAGR_OID', '01871233', 'LAGR', 'LAGR_OID', 'Y', 'VARCHAR(10)', 20, sysdate(), 'GS:MSYS', 'N', 'Legal Agreement OID', 'This is a required foreign key column referencing the Legal Agreement (FT_T_LAGR) table with relationship ''annexure for''.', 'VARCHAR', 10, NULL, NULL, NULL, NULL, NULL, NULL, 'OBJECT_IDENTIFIER', NULL, NULL, NULL, NULL, NULL, NULL);

--STEP--3--

delete from ft_t_tbrn where tbrl_oid in (
select tbrl_oid from ft_t_tbrl where ref_tbl_id ='LAGR' and tbl_id like '%1') and col_nme='ORG_ID';
 
update ft_T_tbrn set col_nme='LAGR_OID' where  tbrl_oid in (
select tbrl_oid from ft_t_tbrl where ref_tbl_id ='LAGR' and tbl_id like '%1') and col_nme='LEG_AGRMNT_ID';

----------- insert if not exists ------------------
------------ TBRL (LAV1, CLM1, AFD1) -------------

INSERT INTO FT_T_TBRL
(TBRL_OID, TBL_ID, REF_TBL_ID, TBL_FGN_KEY_ID, TBL_MERGE_TYP, TBL_DUP_ERROR_IND, LAST_CHG_TMS, LAST_CHG_USR_ID, PRIM_KEY_CMPNT_IND, LOGL_ONLY_IND, RFI_RULE_TYP, CHILD_TO_PRNT_TXT, CHILD_TO_PRNT_REQ_IND, CHILD_TO_PRNT_CARD_TYP, PRNT_TO_CHILD_TXT, PRNT_TO_CHILD_REQ_IND, PRNT_TO_CHILD_CARD_TYP, ALT_LOGL_KEY, REF_PARTITION_IND)
SELECT 'LAV1LAGR01', 'LAV1', 'LAGR', 'FT_T_LAV1_F002', NULL, NULL, SYSDATE(), 'MHICSTM', NULL, 'N', 'R', 'can represent a', 'N', '0,1', 'acts as', 'N', '0,M', NULL, NULL FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM FT_T_TBRL WHERE TBL_ID = 'LAV1' AND REF_TBL_ID = 'LAGR');

INSERT INTO FT_T_TBRL
(TBRL_OID, TBL_ID, REF_TBL_ID, TBL_FGN_KEY_ID, TBL_MERGE_TYP, TBL_DUP_ERROR_IND, LAST_CHG_TMS, LAST_CHG_USR_ID, PRIM_KEY_CMPNT_IND, LOGL_ONLY_IND, RFI_RULE_TYP, CHILD_TO_PRNT_TXT, CHILD_TO_PRNT_REQ_IND, CHILD_TO_PRNT_CARD_TYP, PRNT_TO_CHILD_TXT, PRNT_TO_CHILD_REQ_IND, PRNT_TO_CHILD_CARD_TYP, ALT_LOGL_KEY, REF_PARTITION_IND)
SELECT 'CLM1LAGR01', 'CLM1', 'LAGR', 'FT_T_CLM1_F002', NULL, NULL, SYSDATE(), 'MHICSTM', NULL, 'N', 'R', 'can represent a', 'N', '0,1', 'acts as', 'N', '0,M', NULL, NULL FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM FT_T_TBRL WHERE TBL_ID = 'CLM1' AND REF_TBL_ID = 'LAGR');

INSERT INTO FT_T_TBRL
(TBRL_OID, TBL_ID, REF_TBL_ID, TBL_FGN_KEY_ID, TBL_MERGE_TYP, TBL_DUP_ERROR_IND, LAST_CHG_TMS, LAST_CHG_USR_ID, PRIM_KEY_CMPNT_IND, LOGL_ONLY_IND, RFI_RULE_TYP, CHILD_TO_PRNT_TXT, CHILD_TO_PRNT_REQ_IND, CHILD_TO_PRNT_CARD_TYP, PRNT_TO_CHILD_TXT, PRNT_TO_CHILD_REQ_IND, PRNT_TO_CHILD_CARD_TYP, ALT_LOGL_KEY, REF_PARTITION_IND)
SELECT 'AFD1LAGR01', 'AFD1', 'LAGR', 'FT_T_AFD1_F002', NULL, NULL, SYSDATE(), 'MHICSTM', NULL, 'N', 'R', 'can represent a', 'N', '0,1', 'acts as', 'N', '0,M', NULL, NULL FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM FT_T_TBRL WHERE TBL_ID = 'AFD1' AND REF_TBL_ID = 'LAGR');

--------------- TBRN (LAV1, CLM1, AFD1) -----------------

INSERT INTO FT_T_TBRN
(TBRN_OID, TBRL_OID, TBL_ID, COL_NME, COL_SQ_NUM, LAST_CHG_TMS, LAST_CHG_USR_ID)
VALUES('AFD1F00101', 'AFD1LAGR01', 'AFD1', 'LAGR_OID', 1, SYSDATE(), 'MHICSTM');
INSERT INTO FT_T_TBRN
(TBRN_OID, TBRL_OID, TBL_ID, COL_NME, COL_SQ_NUM, LAST_CHG_TMS, LAST_CHG_USR_ID)
VALUES('CLM1F00101', 'CLM1LAGR01', 'CLM1', 'LAGR_OID', 1, SYSDATE(), 'MHICSTM');
INSERT INTO FT_T_TBRN
(TBRN_OID, TBRL_OID, TBL_ID, COL_NME, COL_SQ_NUM, LAST_CHG_TMS, LAST_CHG_USR_ID)
VALUES('LAV1F00201', 'LAV1LAGR01', 'LAV1', 'LAGR_OID', 1, SYSDATE(), 'MHICSTM');

--Step--4--

ALTER TABLE FT_T_CLM1
ALTER COLUMN leg_agrmnt_id DROP NOT NULL,
ALTER COLUMN org_id DROP NOT NULL;

ALTER TABLE FT_T_LAV1
ALTER COLUMN leg_agrmnt_id DROP NOT NULL,
ALTER COLUMN org_id DROP NOT NULL;

ALTER TABLE FT_T_AFD1
ALTER COLUMN leg_agrmnt_id DROP NOT NULL,
ALTER COLUMN org_id DROP NOT NULL;

--Step--5--

------------- DROP THE CONSTRAINT -------------------

ALTER TABLE FT_T_AFD1 DROP CONSTRAINT FT_T_AFD1_F002;

ALTER TABLE FT_T_CLM1 DROP CONSTRAINT FT_T_CLM1_F002;

ALTER TABLE FT_T_LAV1 DROP CONSTRAINT FT_T_LAV1_F002;


--Step--6--

---- Run the migration script provided by Mihir ----------


   UPDATE FT_T_LAV1 A
      SET LAGR_OID =
             (SELECT /*+PARALLEL(16) FULL(B) */
                    LAGR_OID
                FROM FT_T_LAGR B
               WHERE     A.LEG_AGRMNT_ID = B.LEG_AGRMNT_ID
                     AND A.ORG_ID = B.ORG_ID);
   COMMIT;



   UPDATE FT_T_CLM1 A
      SET LAGR_OID =
             (SELECT /*+PARALLEL(16) FULL(B) */
                    LAGR_OID
                FROM FT_T_LAGR B
               WHERE     A.LEG_AGRMNT_ID = B.LEG_AGRMNT_ID
                     AND A.ORG_ID = B.ORG_ID);
   COMMIT;



   UPDATE FT_T_AFD1 A
      SET LAGR_OID =
             (SELECT /*+PARALLEL(16) FULL(B) */
                    LAGR_OID
                FROM FT_T_LAGR B
               WHERE     A.LEG_AGRMNT_ID = B.LEG_AGRMNT_ID
                     AND A.ORG_ID = B.ORG_ID);
   COMMIT;

--Add the constraint

ALTER TABLE FT_T_LAV1 ADD CONSTRAINT FT_T_LAV1_F002 FOREIGN KEY (LAGR_OID) REFERENCES FT_T_LAGR NOT VALID;
ALTER TABLE FT_T_AFD1 ADD CONSTRAINT FT_T_AFD1_F002 FOREIGN KEY (LAGR_OID) REFERENCES FT_T_LAGR NOT VALID;
ALTER TABLE FT_T_CLM1 ADD CONSTRAINT FT_T_CLM1_F002 FOREIGN KEY (LAGR_OID) REFERENCES FT_T_LAGR NOT VALID;

ALTER TABLE FT_T_CLM1
ALTER COLUMN leg_agrmnt_id SET NOT NULL,
ALTER COLUMN org_id SET NOT NULL;

ALTER TABLE FT_T_AFD1
ALTER COLUMN leg_agrmnt_id SET NOT NULL,
ALTER COLUMN org_id SET NOT NULL;

ALTER TABLE FT_T_LAV1
ALTER COLUMN org_id SET NOT NULL;

-------------------------------------- Shubham's script for LAAP --------------------------------

ALTER TABLE FT_T_LAAP
ALTER COLUMN LAAN_OID DROP NOT NULL;
update FT_t_CLDF set col_req_ind ='N' where tbl_id ='LAAP' and col_nme ='LAAN_OID';